import { analyzeAnswer } from './src/utils/smartCheck.js';
const t1=['Luna went to the forest with her dad.'];
const t2=['The bird was blue and yellow.'];
const t3=['The grass felt soft and warm.'];
const t4=['No, you are not tall.'];
const run=(i,m,t,l)=>{const r=analyzeAnswer(i,t,m);console.log((r.isCorrect?'OK':'X')+' ['+l+'] => '+r.message);};
run('Her dad.','academic',t1,'Q1: fragment 2w');
run('Luna went to the forest with her dad.','academic',t1,'Q1: correct');
run('luna went to the forest with her dad.','academic',t1,'Q1: no capital');
run('Luna went to the forest with her dad','academic',t1,'Q1: no punct');
run('luna went to the forest with her dad','academic',t1,'Q1: no cap no punct');
run('Blue and yellow.','academic',t2,'Q2: fragment 3w');
run('The bird was blue and yellow.','academic',t2,'Q2: correct');
run('the bird was blue and yellow.','academic',t2,'Q2: no capital');
run('The bird was blue and yellow','academic',t2,'Q2: no punct');
run('warm','academic',t3,'Q3: 1 word');
run('Soft and warm.','academic',t3,'Q3: fragment 3w no verb');
run('The grass felt soft and warm.','academic',t3,'Q3: correct');
run('no','academic',t4,'Q4: 1 word');
run('No, I am not.','academic',t4,'Q4: missing tall');
run('No, I am not tall.','academic',t4,'Q4: correct variant');
run('No, you are not tall.','academic',t4,'Q4: exact match');
run('I am not tall.','academic',t4,'Q4: valid without No');
run('I see my face.','academic',['I can see my face in the mirror.'],'Q5: similar but missing mirror');
