#!/usr/bin/env python3
"""
Merge chunks_dataset into dictionary.json with Vietnamese definitions.
"""

import json
from pathlib import Path

DICT = Path('/Users/binhnguyen/Downloads/Engquest3k/src/data/dictionary.json')
DATASET = Path('/Users/binhnguyen/Downloads/Engquest3k/production_kit/data/chunks_dataset.json')

# Vietnamese definitions for common ESL chunks
VI_DEFINITIONS = {
    # Time/place chunks
    "2,500 years ago": "2.500 năm trước",
    "a big part of": "một phần lớn của",
    "a little upset": "hơi buồn/bực",
    "accidents happen": "tai nạn xảy ra",
    "across the world": "khắp thế giới",
    "act now": "hành động ngay",
    "all around us": "khắp xung quanh chúng ta",
    "all over the world": "khắp thế giới",
    "all winter long": "suốt cả mùa đông",
    "amazing abilities": "khả năng đáng kinh ngạc",
    "ancient greece": "Hy Lạp cổ đại",
    "animal characters": "nhân vật động vật",
    "answers questions": "trả lời câu hỏi",
    "apply first aid": "sơ cứu",
    "around the earth": "xung quanh Trái Đất",
    "around the world": "khắp thế giới",
    "as time passed": "khi thời gian trôi qua",
    "at a time": "mỗi lần",
    "at once": "ngay lập tức",
    "at one's own pace": "theo tốc độ của riêng mình",
    "at the same moment": "cùng một lúc",
    "at the very end": "ở cuối cùng",
    "at the zoo": "tại vườn thú",
    "be a perfect day": "là một ngày hoàn hảo",
    "be so happy": "vui như vậy",
    "beautiful park": "công viên đẹp",
    "because of": "bởi vì",
    "before dinner": "trước bữa tối",
    "begin to grow": "bắt đầu phát triển",
    "big brother": "anh trai",
    "big brown eyes": "đôi mắt nâu to",
    "big green field": "cánh đồng xanh rộng",
    "blank paper": "giấy trắng",
    "blue oceans": "đại dương xanh",
    "brush one's teeth": "đánh răng",
    "brushed all one's teeth": "đã đánh răng xong",
    "build one's strength": "tăng cường sức mạnh",
    "burn fossil fuels": "đốt nhiên liệu hóa thạch",
    "carry passengers": "chở hành khách",
    "carbon emissions": "lượng khí thải carbon",
    "carry hundreds of passengers": "chở hàng trăm hành khách",
    "carry thousands of passengers": "chở hàng nghìn hành khách",
    "carry many people": "chở nhiều người",
    "cave walls": "vách hang",
    "chase after": "đuổi theo",
    "cheese sandwich": "bánh sandwich phô mai",
    "chemical reaction": "phản ứng hóa học",
    "city street": "đường phố thành phố",
    "clap loudly": "vỗ tay to",
    "climate change": "biến đổi khí hậu",
    "collect eggs": "thu gom trứng",
    "cold pack": "túi lạnh",
    "cold metal": "kim loại lạnh",
    "come from": "đến từ",
    "comic strip": "truyện tranh",
    "correct answer": "câu trả lời đúng",
    "create a comic strip": "tạo truyện tranh",
    "cross the ocean": "vượt đại dương",
    "cut down trees": "đốn cây",
    "cut out shapes": "cắt hình",
    "cut the long grass": "cắt cỏ dài",
    "daily routine": "thói quen hàng ngày",
    "day after day": "ngày qua ngày",
    "deeply rooted": "ăn sâu",
    "delicious food": "đồ ăn ngon",
    "comfortable": "thoải mái",
    "cross the sea": "vượt biển",
    "do photosynthesis": "quang hợp",
    "do homework": "làm bài tập về nhà",
    "draw a picture": "vẽ tranh",
    "draw pictures": "vẽ tranh",
    "eat breakfast": "ăn sáng",
    "eat dinner": "ăn tối",
    "eat lunch": "ăn trưa",
    "endangered animals": "động vật có nguy cơ tuyệt chủng",
    "enormous and": "khổng lồ và",
    "every evening": "mỗi tối",
    "every afternoon": "mỗi chiều",
    "every single day": "từng ngày một",
    "every single time": "mỗi lần",
    "every year": "mỗi năm",
    "explore the city": "khám phá thành phố",
    "exploring the city": "đang khám phá thành phố",
    "fall asleep": "ngủ thiếp đi",
    "fast asleep": "ngủ say",
    "feel calm": "cảm thấy bình tĩnh",
    "feel confident": "cảm thấy tự tin",
    "feel happy": "cảm thấy vui",
    "feel proud": "cảm thấy tự hào",
    "feed the animals": "cho động vật ăn",
    "field journal": "nhật ký thực địa",
    "first of all": "trước hết",
    "fish and chips": "cá và khoai tây chiên",
    "fly a kite": "thả diều",
    "follow safety rules": "tuân theo quy tắc an toàn",
    "follow steps": "làm theo các bước",
    "food chain": "chuỗi thức ăn",
    "for everyone": "cho mọi người",
    "for thousands of years": "hàng nghìn năm",
    "for us": "cho chúng ta",
    "forest animals": "động vật rừng",
    "fresh food": "thức ăn tươi",
    "fresh strawberry": "dâu tây tươi",
    "fresh fruit": "trái cây tươi",
    "from place to place": "từ nơi này sang nơi khác",
    "from that day on": "từ ngày đó trở đi",
    "from right to left": "từ phải sang trái",
    "from sunrise to sunset": "từ bình minh đến hoàng hôn",
    "full of energy": "tràn đầy năng lượng",
    "fun place": "nơi vui vẻ",
    "gather seeds": "thu thập hạt giống",
    "get hurt": "bị thương",
    "get somewhere": "đến đâu đó",
    "get ready for school": "chuẩn bị đến trường",
    "get better": "khá hơn",
    "go to bed": "đi ngủ",
    "go to school": "đi học",
    "go to the store": "đi đến cửa hàng",
    "go to the market": "đi chợ",
    "good for the environment": "tốt cho môi trường",
    "good for": "tốt cho",
    "great choice": "lựa chọn tuyệt vời",
    "great place": "nơi tuyệt vời",
    "great race": "cuộc đua vĩ đại",
    "green fields": "cánh đồng xanh",
    "greenhouse effect": "hiệu ứng nhà kính",
    "greenhouse gases": "khí nhà kính",
    "grow food": "trồng thức ăn",
    "grow strong": "lớn lên khỏe mạnh",
    "had fun": "đã vui",
    "hard work pays off": "làm việc chăm chỉ được đền đáp",
    "have a picnic": "đi picnic",
    "have an accident": "bị tai nạn",
    "have breakfast": "ăn sáng",
    "have dinner": "ăn tối",
    "have fun": "vui vẻ",
    "have lunch": "ăn trưa",
    "have questions": "có câu hỏi",
    "have to": "phải",
    "healthy food": "thức ăn lành mạnh",
    "hear good news": "nghe tin tốt",
    "help each other": "giúp đỡ lẫn nhau",
    "help mom": "giúp mẹ",
    "help you grow": "giúp bạn lớn lên",
    "high mountains": "núi cao",
    "high-speed trains": "tàu cao tốc",
    "hide and seek": "trốn tìm",
    "his audience": "khán giả của anh ấy",
    "home is where": "nhà là nơi",
    "house keys": "chìa khóa nhà",
    "how do people travel": "mọi người đi lại bằng cách nào",
    "hundreds of years": "hàng trăm năm",
    "ice cream": "kem",
    "in danger": "trong nguy hiểm",
    "in danger of": "có nguy cơ",
    "in detail": "chi tiết",
    "in different ways": "theo những cách khác nhau",
    "in front of": "phía trước",
    "in hoi an": "tại Hội An",
    "in modern cities": "trong các thành phố hiện đại",
    "in nice bedroom": "trong phòng ngủ đẹp",
    "in real life": "trong đời thực",
    "in the box": "trong hộp",
    "in the classroom": "trong lớp học",
    "in the countryside": "ở nông thôn",
    "in the future": "trong tương lai",
    "in the morning": "vào buổi sáng",
    "in the pool": "trong hồ bơi",
    "in the same way": "theo cùng một cách",
    "in the sky": "trên bầu trời",
    "in the world": "trên thế giới",
    "instead of": "thay vì",
    "introduce oneself": "tự giới thiệu",
    "introduce themselves": "tự giới thiệu (số nhiều)",
    "invisible vapor": "hơi nước vô hình",
    "is a wonderful choice": "là một lựa chọn tuyệt vời",
    "is enormous and": "khổng lồ và",
    "is in danger": "đang gặp nguy hiểm",
    "is like a": "giống như",
    "is the most": "là nhất",
    "it is raining": "trời đang mưa",
    "jog around": "chạy bộ xung quanh",
    "juicy watermelon": "dưa hấu ngon ngọt",
    "jump ahead": "nhảy lên phía trước",
    "jump high": "nhảy cao",
    "jump in puddles": "nhảy trong vũng nước",
    "just like": "giống như",
    "keep one quiet place": "giữ một nơi yên tĩnh",
    "keep one's house tidy": "giữ nhà ngăn nắn",
    "keep one's room tidy": "giữ phòng ngăn nắn",
    "kick a ball": "đá bóng",
    "kilometre per hour": "ki lô mét mỗi giờ",
    "know how to": "biết cách",
    "laughing loudly": "cười to",
    "learn new things": "học điều mới",
    "learn to read": "học đọc",
    "learn about": "học về",
    "learn one's lesson": "rút kinh nghiệm",
    "leave the": "rời khỏi",
    "left hand": "tay trái",
    "less busy": "bận rộn hơn",
    "let us": "hãy để chúng ta",
    "lie down": "nằm xuống",
    "life cycle": "vòng đời",
    "light clothes": "quần áo mỏng",
    "little by little": "từ từ",
    "little brother": "em trai",
    "little sister": "em gái",
    "live together": "sống cùng nhau",
    "live broadcast": "phát sóng trực tiếp",
    "living room": "phòng khách",
    "long ago": "lâu rồi",
    "long brown hair": "tóc nâu dài",
    "long time": "lâu",
    "look after": "chăm sóc",
    "look around": "nhìn quanh",
    "look at": "nhìn vào",
    "look for": "tìm kiếm",
    "look on the floor": "nhìn xuống sàn",
    "look out the window": "nhìn ra ngoài cửa sổ",
    "look under": "nhìn bên dưới",
    "look up": "nhìn lên",
    "lots of water": "nhiều nước",
    "loudly": "to tiếng",
    "loved reading": "thích đọc",
    "make a difference": "tạo ra sự khác biệt",
    "make a discovery": "tạo ra khám phá",
    "make a fire": "tạo lửa",
    "make a sandwich": "làm bánh sandwich",
    "make food": "làm thức ăn",
    "make one's bed": "dọn giường",
    "make one's own": "tự làm cho mình",
    "make sure": "đảm bảo",
    "many animals": "nhiều động vật",
    "many trees": "nhiều cây",
    "matter where": "vấn đề ở đâu",
    "may be": "có thể",
    "mealtime": "giờ ăn",
    "modern technology": "công nghệ hiện đại",
    "mood of the story": "tâm trạng câu chuyện",
    "mode of transport": "phương thức vận chuyển",
    "more than": "nhiều hơn",
    "most popular": "phổ biến nhất",
    "most popular vehicle": "phương tiện phổ biến nhất",
    "must protect": "phải bảo vệ",
    "narrator": "người kể chuyện",
    "native speaker": "người bản xứ",
    "natural world": "thế giới tự nhiên",
    "near the": "gần",
    "next door": "bên cạnh",
    "next summer": "mùa hè tới",
    "next to": "bên cạnh",
    "next time": "lần tới",
    "night sky": "bầu trời đêm",
    "no matter where": "không quan trọng ở đâu",
    "noisy place": "nơi ồn ào",
    "now and then": "thỉnh thoảng",
    "of the year": "của năm",
    "of their own": "của riêng chúng",
    "older brother": "anh trai",
    "on monday": "vào thứ Hai",
    "on sunday": "vào chủ nhật",
    "on the wall": "trên tường",
    "on time": "đúng giờ",
    "on weekends": "vào cuối tuần",
    "open my bag": "mở cặp của tôi",
    "open your": "mở của bạn",
    "open the door": "mở cửa",
    "our planet": "hành tinh của chúng ta",
    "out of": "hết",
    "over time": "theo thời gian",
    "over there": "ở đằng kia",
    "ox": "bò",
    "page number": "số trang",
    "pass the ball": "chuyền bóng",
    "pay attention": "chú ý",
    "pay for": "trả tiền cho",
    "perfect choice": "lựa chọn hoàn hảo",
    "perfect day": "ngày hoàn hảo",
    "pick up": "nhặt lên",
    "picture books": "sách tranh",
    "pink and": "hồng và",
    "place name": "tên địa danh",
    "play soccer": "chơi bóng đá",
    "play with": "chơi với",
    "play with friends": "chơi với bạn bè",
    "pocket money": "tiền tiêu vặt",
    "polar ice": "băng ở hai cực",
    "poor soil": "đất nghèo",
    "popular vehicle": "phương tiện phổ biến",
    "popular water": "nước phổ biến",
    "pour a glass": "rót một ly",
    "practice every day": "luyện tập mỗi ngày",
    "pretty flower": "hoa đẹp",
    "protect one's planet": "bảo vệ hành tinh của mình",
    "public speaking": "nói trước công chúng",
    "pull up": "kéo lên",
    "purple and": "tím và",
    "push the": "đẩy",
    "put everything away": "dọn dẹp mọi thứ",
    "put on": "mặc",
    "put out": "dập tắt",
    "put out a fire": "dập lửa",
    "queue": "xếp hàng",
    "quiet place": "nơi yên tĩnh",
    "quiet street": "đường phố yên tĩnh",
    "race against": "đua với",
    "rainforest": "rừng nhiệt đới",
    "rainy days": "những ngày mưa",
    "read a book": "đọc sách",
    "read a story book": "đọc sách truyện",
    "read books": "đọc sách",
    "read every": "đọc từng",
    "reading a book": "đang đọc sách",
    "reading carefully": "đọc cẩn thận",
    "really hard-working": "chăm chỉ thật sự",
    "rebuild": "xây dựng lại",
    "receive": "nhận",
    "recipe": "công thức nấu ăn",
    "recycle paper": "tái chế giấy",
    "red bus": "xe buýt đỏ",
    "reduce carbon emissions": "giảm khí thải carbon",
    "reduce swelling": "giảm sưng",
    "reduce waste": "giảm rác thải",
    "relaxing under the trees": "thư giãn dưới tán cây",
    "renewable energy": "năng lượng tái tạo",
    "ride a motorbike": "đi xe máy",
    "ride a bike": "đi xe đạp",
    "ride a bicycle": "đi xe đạp",
    "right now": "ngay bây giờ",
    "right order": "đúng thứ tự",
    "river bank": "bờ sông",
    "room number": "số phòng",
    "round face": "khuôn mặt tròn",
    "run fast": "chạy nhanh",
    "run quickly": "chạy nhanh",
    "run very fast": "chạy rất nhanh",
    "safe place": "nơi an toàn",
    "safe places": "những nơi an toàn",
    "safety rules": "quy tắc an toàn",
    "sand and": "cát và",
    "sat down": "ngồi xuống",
    "sat down with": "ngồi xuống cùng",
    "save energy": "tiết kiệm năng lượng",
    "save lives": "cứu mạng",
    "save the planet": "cứu hành tinh",
    "save one's planet": "cứu hành tinh của mình",
    "save the day": "cứu vãn tình thế",
    "school corridor": "hành lang trường học",
    "school day": "ngày đi học",
    "school gate": "cổng trường",
    "school uniform": "đồng phục học sinh",
    "science fiction": "khoa học viễn tưởng",
    "scientific evidence": "bằng chứng khoa học",
    "sea level": "mực nước biển",
    "sea levels": "mực nước biển",
    "second caption": "chú thích thứ hai",
    "see you": "gặp lại",
    "see you soon": "gặp lại sau",
    "sell food": "bán thức ăn",
    "sense of touch": "giác quan xúc giác",
    "set the table": "dọn bàn ăn",
    "shake hands": "bắt tay",
    "share my world": "chia sẻ thế giới của tôi",
    "shiny": "sáng bóng",
    "ship across the ocean": "tàu vượt đại dương",
    "shop owner": "chủ cửa hàng",
    "shop": "cửa hàng",
    "short story": "truyện ngắn",
    "shout with excitement": "la hét hào hứng",
    "shouted with excitement": "đã la hét hào hứng",
    "side by side": "cạnh nhau",
    "sing happy songs": "hát những bài hát vui",
    "sing songs": "hát những bài hát",
    "sit down": "ngồi xuống",
    "sit on": "ngồi trên",
    "sit on the fence": "ngồi trên hàng rào",
    "slow and steady": "chậm mà chắc",
    "slow and steady wins": "chậm mà chắc sẽ thắng",
    "slow tortoise": "con rùa chậm",
    "small and": "nhỏ và",
    "small boat": "thuyền nhỏ",
    "small notebook": "sổ tay nhỏ",
    "small plants": "cây nhỏ",
    "small villages": "làng nhỏ",
    "smart and": "thông minh và",
    "smell the flowers": "ngửi hoa",
    "smile and agree": "cười và đồng ý",
    "smile and clap": "cười và vỗ tay",
    "smile brightly": "cười tươi",
    "snake and ladder": "rắn và thang",
    "snow white": "bạch tuyết",
    "soft blanket": "chăn mềm",
    "soft brush": "bàn chải mềm",
    "soft cotton": "bông mềm",
    "solar panels": "tấm pin mặt trời",
    "solar power": "năng lượng mặt trời",
    "solid": "rắn",
    "solve a case": "giải quyết vụ án",
    "solve problems": "giải quyết vấn đề",
    "some more": "thêm một số",
    "sort by": "sắp xếp theo",
    "sound like": "nghe giống như",
    "spaghetti": "mỳ Ý",
    "sparkle in the sunlight": "lấp lánh dưới ánh nắng",
    "special visitor": "khách đặc biệt",
    "spell correctly": "đánh vần đúng",
    "spelling": "đánh vần",
    "spend time": "dành thời gian",
    "splendid": "tuyệt vời",
    "spring festival": "lễ hội mùa xuân",
    "stage by stage": "từng giai đoạn",
    "stand up": "đứng dậy",
    "star": "ngôi sao",
    "star wars": "chiến tranh giữa các vì sao",
    "stay safe": "giữ an toàn",
    "stay healthy": "giữ sức khỏe",
    "steel rail": "đường ray thép",
    "steel rails": "đường ray thép",
    "steep hill": "đồi dốc",
    "step by step": "từng bước một",
    "stick together": "dính lại với nhau",
    "still stands": "vẫn đứng vững",
    "stone bowl": "bát đá",
    "stop and": "dừng lại và",
    "store food": "dự trữ thức ăn",
    "stormy weather": "thời tiết bão",
    "strange": "kỳ lạ",
    "stranger": "người lạ",
    "street musician": "nhạc sĩ đường phố",
    "strong and": "mạnh và",
    "strong and kind": "mạnh mẽ và tốt bụng",
    "student life": "đời sống sinh viên",
    "study hard": "học chăm chỉ",
    "substances": "chất",
    "sunny days": "những ngày nắng",
    "super strength": "sức mạnh siêu phàm",
    "superhero": "siêu anh hùng",
    "swim in the pool": "bơi trong hồ",
    "swim far": "bơi xa",
    "swimming pool": "hồ bơi",
    "take a deep breath": "hít một hơi thật sâu",
    "take a taxi": "đi taxi",
    "take a photo": "chụp ảnh",
    "take care of": "chăm sóc",
    "take off my coat": "cởi áo khoác",
    "take one's hat": "cởi mũ",
    "take photos": "chụp ảnh",
    "take turns": "lần lượt",
    "talk about": "nói về",
    "talk to": "nói chuyện với",
    "tall building": "tòa nhà cao",
    "tall stem": "thân cao",
    "tall trees": "cây cao",
    "talk about your feelings": "nói về cảm xúc của bạn",
    "tallest buildings": "những tòa nhà cao nhất",
    "tall trees": "những cây cao",
    "tasty snack": "đồ ăn vặt ngon",
    "taxi driver": "tài xế taxi",
    "teach": "dạy",
    "teach English": "dạy tiếng Anh",
    "teach yourself": "tự học",
    "team sport": "thể thao đồng đội",
    "tell stories": "kể chuyện",
    "tell a story": "kể một câu chuyện",
    "tell the truth": "nói sự thật",
    "thank you for listening": "cảm ơn bạn đã lắng nghe",
    "thanks to": "nhờ vào",
    "that is the": "đó là",
    "the answer lies in": "câu trả lời nằm ở",
    "the best": "tốt nhất",
    "the first": "đầu tiên",
    "the next day": "ngày hôm sau",
    "the park": "công viên",
    "the right": "đúng",
    "the same": "giống nhau",
    "the school": "trường học",
    "their bedroom": "phòng ngủ của họ",
    "their children": "con cái của họ",
    "their families": "gia đình của họ",
    "their parents": "bố mẹ của họ",
    "theoretical physicist": "nhà vật lý lý thuyết",
    "this is the": "đây là",
    "this is a": "đây là một",
    "this morning": "sáng nay",
    "thousands of": "hàng nghìn",
    "thousands of years": "hàng nghìn năm",
    "throw away": "vứt đi",
    "throw away plastic": "vứt bỏ nhựa",
    "throw a ball": "ném bóng",
    "time to go": "đến lúc đi",
    "tiny insects": "côn trùng nhỏ",
    "tiny sprout": "mầm nhỏ",
    "tired of": "mệt với",
    "to explore": "để khám phá",
    "to get somewhere": "để đến đâu đó",
    "to have": "để có",
    "to have fun": "để vui vẻ",
    "to know": "để biết",
    "to learn": "để học",
    "to play": "để chơi",
    "to school": "đến trường",
    "today is": "hôm nay là",
    "tonnes of goods": "hàng tấn hàng hóa",
    "tortoise and the hare": "rùa và thỏ",
    "tossed and turned": "trở mình",
    "touch the": "chạm vào",
    "tough": "khó khăn",
    "tower": "tháp",
    "town": "thị trấn",
    "track and field": "điền kinh",
    "tractor": "máy kéo",
    "traffic lights": "đèn giao thông",
    "trail": "đường mòn",
    "train station": "nhà ga",
    "travel by car": "đi bằng ô tô",
    "travel on water": "đi bằng đường thủy",
    "travel through": "đi xuyên qua",
    "tree house": "nhà trên cây",
    "tree leaves": "lá cây",
    "trees and": "cây và",
    "trick and treat": "cho kẹo hay bị ghẹo",
    "try not to": "cố gắng không",
    "try to": "cố gắng",
    "turn on": "bật",
    "turn over": "lật",
    "turn around": "quay lại",
    "twist and turn": "xoay và quay",
    "type of transport": "loại phương tiện",
    "types of transport": "các loại phương tiện",
    "uncle bob": "chú Bob",
    "uncomfortable": "không thoải mái",
    "under her bed": "dưới gầm giường",
    "under the bed": "dưới gầm giường",
    "under the tree": "dưới gốc cây",
    "understand": "hiểu",
    "unit": "đơn vị",
    "use less plastic": "sử dụng ít nhựa hơn",
    "use less energy": "sử dụng ít năng lượng hơn",
    "use solar power": "sử dụng năng lượng mặt trời",
    "use wind power": "sử dụng năng lượng gió",
    "valley": "thung lũng",
    "various": "đa dạng",
    "vegetable soup": "súp rau",
    "very busy": "rất bận",
    "very fast": "rất nhanh",
    "very good": "rất tốt",
    "very happy": "rất vui",
    "very high": "rất cao",
    "very large": "rất lớn",
    "very nice": "rất đẹp",
    "very quietly": "rất yên lặng",
    "very special": "rất đặc biệt",
    "very special day": "ngày rất đặc biệt",
    "very tall": "rất cao",
    "very tired": "rất mệt",
    "wake up": "thức dậy",
    "wake up early": "thức dậy sớm",
    "walk to school": "đi bộ đến trường",
    "walk carefully": "đi cẩn thận",
    "walk through": "đi qua",
    "walk to": "đi đến",
    "warm blanket": "chăn ấm",
    "warm climate": "khí hậu ấm",
    "warm milk": "sữa ấm",
    "warm planet": "hành tinh ấm",
    "warm smile": "nụ cười ấm",
    "warm sunshine": "nắng ấm",
    "warm water": "nước ấm",
    "warn": "cảnh báo",
    "wash one's hands": "rửa tay",
    "wash your hands": "rửa tay bạn",
    "waste paper": "giấy lộn",
    "water cycle": "chu trình nước",
    "water droplets": "giọt nước",
    "wave back": "vẫy tay lại",
    "wave goodbye": "vẫy tay chào tạm biệt",
    "wear glasses": "đeo kính",
    "wear one's hat": "đội mũ",
    "weekend": "cuối tuần",
    "well done": "làm tốt lắm",
    "wet": "ướt",
    "what makes you": "điều gì khiến bạn",
    "what the": "cái gì",
    "when i": "khi tôi",
    "when you": "khi bạn",
    "where the": "nơi mà",
    "white and": "trắng và",
    "white board": "bảng trắng",
    "white teeth": "răng trắng",
    "whole story": "toàn bộ câu chuyện",
    "why do you": "tại sao bạn",
    "wide range": "phạm vi rộng",
    "wild chimps": "tinh tinh hoang dã",
    "wild chimpanzees": "tinh tinh hoang dã",
    "wind power": "năng lượng gió",
    "window of opportunity": "cơ hội",
    "winter morning": "sáng mùa đông",
    "winter time": "mùa đông",
    "with each other": "với nhau",
    "with pride": "với niềm tự hào",
    "with water": "với nước",
    "wonderful day": "ngày tuyệt vời",
    "wonderful place": "nơi tuyệt vời",
    "wonderful time": "thời gian tuyệt vời",
    "wooden bridge": "cầu gỗ",
    "wooden shelf": "kệ gỗ",
    "work carefully": "làm việc cẩn thận",
    "work hard": "làm việc chăm chỉ",
    "work out": "tập thể dục",
    "work together": "làm việc cùng nhau",
    "worked hard": "đã làm việc chăm chỉ",
    "world around us": "thế giới xung quanh chúng ta",
    "world war": "chiến tranh thế giới",
    "would like to": "muốn",
    "would rather": "thà",
    "write a letter": "viết thư",
    "write down": "viết ra",
    "write in notebooks": "viết vào sổ",
    "write the": "viết",
    "write your": "viết của bạn",
    "yell at": "quát vào",
    "yelled for help": "la hét cầu cứu",
    "yellow and": "vàng và",
    "yellow bus": "xe buýt vàng",
    "yellow taxi": "taxi vàng",
    "young scientist": "nhà khoa học trẻ",
    "your bedroom": "phòng ngủ của bạn",
    "your family": "gia đình bạn",
    "your home": "nhà bạn",
    "your room": "phòng bạn",
    "zero": "không",
    "every minute": "mỗi phút",
}

# Load
with open(DICT) as f:
    dict_entries = json.load(f)

with open(DATASET) as f:
    dataset = json.load(f)

existing_words = {e['word'].lower() for e in dict_entries}

# Generate new entries
new_entries = []
seen_words = set(existing_words)
for item in dataset:
    chunk = item['standardized_chunk']
    if chunk.lower() in seen_words:
        continue

    # Get definition
    vi_def = VI_DEFINITIONS.get(chunk, item.get('standardized_chunk', '').lower())

    # Generate example (simple)
    example = f"This is an example: {chunk}."

    new_entry = {
        "word": chunk,
        "meaning": vi_def,
        "pronounce": "",
        "definition_en": "",
        "first_taught_week": 28,  # Most recent week with chunks
        "example": example,
    }
    new_entries.append(new_entry)
    seen_words.add(chunk.lower())

# Append to dictionary
final_dict = dict_entries + new_entries

# Save
DICT.write_text(json.dumps(final_dict, indent=2, ensure_ascii=False) + "\n")
print(f'Original: {len(dict_entries)}')
print(f'Added: {len(new_entries)}')
print(f'Final: {len(final_dict)}')

# Show sample
for e in new_entries[:10]:
    print(f"  + {e['word']:30} → {e['meaning']}")
