#!/usr/bin/env python3
"""
enrich_w37_42_direct.py
-----------------------
Direct Cambridge enrichment for W37-42 — content generated inline, no external API.
- Expands vocab_tiers to 18 words per week
- Rewrites PART 2 with numbered items + sub-totals per session (7 / 6 / 5 words)
- Rewrites PART 3 (L1-L5) with fully numbered exercise items per session
- Updates public/data/lessons/ + mcp-server/data/lessons/
"""
import json, copy, sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
LESSONS_DIRS = [
    ROOT / 'public' / 'data' / 'lessons',
    ROOT / 'mcp-server' / 'data' / 'lessons',
]

# ─────────────────────────────────────────────────────────────────────────────
# VOCAB  —  18 words per week
# Fields: Word, Vietnamese, Key Collocation(s), Memory Trick
# ─────────────────────────────────────────────────────────────────────────────
VOCAB = {
    37: [
        # ── TIER 1: Core story / theme words ─────────────────────────────────
        {"Word": "living",         "Vietnamese": "sống / có sự sống",       "Key Collocation(s)": "a living thing / a living organism",          "Memory Trick": "L-I-V-E: Life Is Very Exciting → living = full of LIFE"},
        {"Word": "non-living",     "Vietnamese": "không có sự sống",        "Key Collocation(s)": "a non-living thing / non-living objects",      "Memory Trick": "NON = Not → non-living = NOT living. Simple!"},
        {"Word": "breathe",        "Vietnamese": "thở",                     "Key Collocation(s)": "breathe air / breathe in water",               "Memory Trick": "B-R-E-A-T-H-E: Big Rabbits Eat Apples To Have Energy"},
        {"Word": "grow",           "Vietnamese": "lớn lên / phát triển",    "Key Collocation(s)": "grow tall / grow bigger each year",             "Memory Trick": "G-R-O-W: Green Roots Open Wide → roots grow outwards"},
        {"Word": "move",           "Vietnamese": "di chuyển",               "Key Collocation(s)": "move fast / move toward the sun",               "Memory Trick": "M-O-V-E: My Owls Very Energetic → owls move silently"},
        {"Word": "survive",        "Vietnamese": "tồn tại / sống sót",      "Key Collocation(s)": "survive in the wild / need food to survive",    "Memory Trick": "SUR + VIVE = super + alive → survive = stay super alive!"},
        {"Word": "energy",         "Vietnamese": "năng lượng",              "Key Collocation(s)": "need energy / get energy from food",            "Memory Trick": "E-N-E-R-G-Y: Every Night Every Rabbit Gets Yawny"},
        # ── TIER 2: Cambridge Flyers Science vocabulary ───────────────────────
        {"Word": "characteristic", "Vietnamese": "đặc điểm",                "Key Collocation(s)": "a characteristic of living things / main characteristic", "Memory Trick": "CHAR = character → a characteristic = a special character trait"},
        {"Word": "organism",       "Vietnamese": "sinh vật",                "Key Collocation(s)": "a living organism / a micro-organism",          "Memory Trick": "ORG = organ → an organism has organs just like you!"},
        {"Word": "reproduce",      "Vietnamese": "sinh sản",                "Key Collocation(s)": "can reproduce / reproduce quickly",             "Memory Trick": "RE + PRODUCE = produce again → make more living things"},
        {"Word": "respond",        "Vietnamese": "phản ứng / đáp lại",      "Key Collocation(s)": "respond to light / respond to changes",        "Memory Trick": "RE + SPOND = reply → living things reply to changes around them"},
        {"Word": "nutrition",      "Vietnamese": "dinh dưỡng",              "Key Collocation(s)": "get nutrition from food / needs nutrition",     "Memory Trick": "NUTRI = food → nutrition = what you get from eating"},
        {"Word": "classify",       "Vietnamese": "phân loại",               "Key Collocation(s)": "classify living things / classify animals",    "Memory Trick": "CLASS = group → classify = sort into classes (groups)"},
        # ── TIER 3: Grammar / reasoning connectors ────────────────────────────
        {"Word": "because",        "Vietnamese": "vì / bởi vì",            "Key Collocation(s)": "living because it breathes / non-living because it does not grow", "Memory Trick": "BE + CAUSE = the CAUSE (reason) for being → explains WHY"},
        {"Word": "therefore",      "Vietnamese": "do đó / vì vậy",         "Key Collocation(s)": "therefore it is living / it moves, therefore it is alive", "Memory Trick": "THERE + FORE = because of what came BEFORE → therefore = so/thus"},
        {"Word": "investigate",    "Vietnamese": "điều tra / khám phá",    "Key Collocation(s)": "investigate living things / investigate the problem", "Memory Trick": "IN + VEST = put on your detective VEST and investigate!"},
        {"Word": "evidence",       "Vietnamese": "bằng chứng",             "Key Collocation(s)": "find evidence / scientific evidence",           "Memory Trick": "EVID = obvious → evidence = what makes the truth OBVIOUS"},
        {"Word": "conclusion",     "Vietnamese": "kết luận",               "Key Collocation(s)": "reach a conclusion / in conclusion",            "Memory Trick": "CON + CLUSION = closing → a conclusion CLOSES your investigation"},
    ],
    38: [
        # ── TIER 1: Animal groups core vocabulary ─────────────────────────────
        {"Word": "mammal",         "Vietnamese": "động vật có vú",          "Key Collocation(s)": "a warm-blooded mammal / a mammal like a dog",   "Memory Trick": "MAMMAL sounds like MAMA → mammals feed babies milk like a mama"},
        {"Word": "reptile",        "Vietnamese": "bò sát",                  "Key Collocation(s)": "a cold-blooded reptile / reptile scales",       "Memory Trick": "R-E-P-T-I-L-E: Really Every Prehistoric Thing Is Laying Eggs"},
        {"Word": "amphibian",      "Vietnamese": "động vật lưỡng cư",       "Key Collocation(s)": "an amphibian like a frog / lives in water and land", "Memory Trick": "AMPHI = both sides → amphibians live on BOTH water AND land"},
        {"Word": "insect",         "Vietnamese": "côn trùng",               "Key Collocation(s)": "a six-legged insect / an insect like a bee",    "Memory Trick": "IN + SECT = cut into sections → insects have 3 body sections"},
        {"Word": "bird",           "Vietnamese": "chim",                    "Key Collocation(s)": "a bird has feathers / a bird lays eggs",        "Memory Trick": "B-I-R-D: Beaks In Round Distances → birds fly far with beaks!"},
        {"Word": "fish",           "Vietnamese": "cá",                      "Key Collocation(s)": "a fish lives in water / a fish has scales",     "Memory Trick": "F-I-S-H: Found In Streams and Hidden places"},
        {"Word": "warm-blooded",   "Vietnamese": "máu nóng",                "Key Collocation(s)": "warm-blooded mammals / warm-blooded animals",   "Memory Trick": "WARM blood = body stays warm even in cold weather"},
        # ── TIER 2: Cambridge Flyers animal vocabulary ────────────────────────
        {"Word": "cold-blooded",   "Vietnamese": "máu lạnh",               "Key Collocation(s)": "cold-blooded reptile / cold-blooded fish",      "Memory Trick": "COLD blood = body temperature changes WITH the weather"},
        {"Word": "fur",            "Vietnamese": "lông thú",                "Key Collocation(s)": "covered in fur / soft thick fur",               "Memory Trick": "FUR keeps animals warm — like a built-in coat!"},
        {"Word": "scales",         "Vietnamese": "vảy",                     "Key Collocation(s)": "has scales / covered with scales",              "Memory Trick": "SCALES like a weighing scale → fish scales are like tiny armour plates"},
        {"Word": "feathers",       "Vietnamese": "lông vũ",                 "Key Collocation(s)": "has feathers / soft feathers for flying",       "Memory Trick": "FEATHER = light as a feather → feathers help birds fly!"},
        {"Word": "vertebrate",     "Vietnamese": "động vật có xương sống",  "Key Collocation(s)": "a vertebrate animal / vertebrates have a spine", "Memory Trick": "VERT = turn → vertebra = backbone you turn your back with!"},
        {"Word": "lay eggs",       "Vietnamese": "đẻ trứng",               "Key Collocation(s)": "lay eggs in a nest / birds lay eggs",           "Memory Trick": "LAY = place carefully → a bird LAYS an egg like placing a treasure"},
        # ── TIER 3: Grammar (Present Simple: has/have, lays, lives) ──────────
        {"Word": "classify",       "Vietnamese": "phân loại",               "Key Collocation(s)": "classify animals into groups / classify by type", "Memory Trick": "CLASS = group → classify = sort into classes"},
        {"Word": "belong to",      "Vietnamese": "thuộc về",                "Key Collocation(s)": "belongs to the mammal group / belongs to class reptilia", "Memory Trick": "BE + LONG = long-time member → it BELONGS TO this group forever"},
        {"Word": "species",        "Vietnamese": "loài",                    "Key Collocation(s)": "a species of bird / different species",          "Memory Trick": "SPE-CIES = SPECIAL pieces → each species is a special piece of nature"},
        {"Word": "spine",          "Vietnamese": "cột sống / xương sống",  "Key Collocation(s)": "has a spine / a spine runs down its back",       "Memory Trick": "SPINE = stands in a LINE → a spine is a straight line of bones"},
        {"Word": "group",          "Vietnamese": "nhóm / phân loại",        "Key Collocation(s)": "animal group / sort into groups",               "Memory Trick": "G-R-O-U-P: Great Rabbits Often Use Paws → animals use features to show groups"},
    ],
    39: [
        # ── TIER 1: Oviparous vs Viviparous ───────────────────────────────────
        {"Word": "lay eggs",       "Vietnamese": "đẻ trứng",               "Key Collocation(s)": "lay eggs in a nest / oviparous animals lay eggs", "Memory Trick": "LAY = place carefully → hens LAY eggs like placing treasures"},
        {"Word": "give birth",     "Vietnamese": "sinh con",               "Key Collocation(s)": "give birth to live young / mammals give birth", "Memory Trick": "GIVE + BIRTH = give LIFE → a mother gives life to her baby"},
        {"Word": "hatch",          "Vietnamese": "nở (từ trứng)",          "Key Collocation(s)": "hatch from an egg / chicks hatch",               "Memory Trick": "HATCH = a trapdoor → the baby opens a tiny door in the egg!"},
        {"Word": "protect",        "Vietnamese": "bảo vệ",                 "Key Collocation(s)": "protect the eggs / protect their young",         "Memory Trick": "PRO + TECT = professional guard → like a pro bodyguard!"},
        {"Word": "develop",        "Vietnamese": "phát triển",             "Key Collocation(s)": "develop inside the egg / develop slowly",        "Memory Trick": "DE + VELOP = unwrap → the baby DEVELOPS (unwraps) inside the egg"},
        {"Word": "oviparous",      "Vietnamese": "noãn sinh (đẻ trứng)",  "Key Collocation(s)": "oviparous animals / an oviparous creature",      "Memory Trick": "OVI = egg in Latin → OViparous = egg-bearers. Think OVIE the egg!"},
        {"Word": "viviparous",     "Vietnamese": "thai sinh (đẻ con)",    "Key Collocation(s)": "viviparous mammals / a viviparous animal",        "Memory Trick": "VIVI = alive in Latin → VIViparous = live-birth. VIVI = vivid life!"},
        # ── TIER 2: Cambridge Flyers comparison vocabulary ────────────────────
        {"Word": "embryo",         "Vietnamese": "phôi thai",              "Key Collocation(s)": "an embryo grows inside / tiny embryo",           "Memory Trick": "EM + BRYO = early beginning → an embryo is the EARLIEST beginning of life"},
        {"Word": "shell",          "Vietnamese": "vỏ trứng / mai",        "Key Collocation(s)": "hard egg shell / the shell cracks",              "Memory Trick": "SHELL = protective cover → egg shells protect babies like sea shells protect animals"},
        {"Word": "offspring",      "Vietnamese": "con cái / thế hệ sau",  "Key Collocation(s)": "their offspring / protect their offspring",       "Memory Trick": "OFF + SPRING = spring away → offspring spring away from their parents"},
        {"Word": "nest",           "Vietnamese": "tổ (chim)",              "Key Collocation(s)": "build a nest / eggs in a nest",                  "Memory Trick": "NEST = best rest → a nest is the best resting place to grow"},
        {"Word": "alike",          "Vietnamese": "giống nhau",             "Key Collocation(s)": "alike in many ways / look alike",               "Memory Trick": "A + LIKE = I LIKE it because it's the same → alike = they match!"},
        {"Word": "unlike",         "Vietnamese": "khác với / không giống", "Key Collocation(s)": "unlike reptiles / unlike mammals",              "Memory Trick": "UN + LIKE = NOT like → unlike = NOT the same as"},
        # ── TIER 3: Grammar (Both/Unlike/but comparison) ─────────────────────
        {"Word": "both",           "Vietnamese": "cả hai",                 "Key Collocation(s)": "both reptiles and birds / both lay eggs",        "Memory Trick": "B-O-T-H: Bring One Thing Here → both = bring TWO things together"},
        {"Word": "compare",        "Vietnamese": "so sánh",                "Key Collocation(s)": "compare oviparous and viviparous / compare and contrast", "Memory Trick": "COM + PARE = come in PAIRS → compare = look at two things side by side"},
        {"Word": "similar",        "Vietnamese": "tương tự / giống",       "Key Collocation(s)": "similar to mammals / in a similar way",         "Memory Trick": "SIMIL = same in Latin → similar = almost the SAME"},
        {"Word": "difference",     "Vietnamese": "sự khác biệt",          "Key Collocation(s)": "the main difference / a big difference between",  "Memory Trick": "DIFFER = to be different → a difference = what makes two things DIFFER"},
        {"Word": "incubate",       "Vietnamese": "ấp trứng",               "Key Collocation(s)": "incubate eggs / incubate for 21 days",           "Memory Trick": "IN + CUBE = inside a warm cube → incubate = keep eggs warm inside a cozy space"},
    ],
    40: [
        # ── TIER 1: Habitats vocabulary ───────────────────────────────────────
        {"Word": "habitat",        "Vietnamese": "môi trường sống / sinh cảnh", "Key Collocation(s)": "natural habitat / desert habitat",        "Memory Trick": "HABIT + AT = habit of living at a place → where an animal HABITUALLY lives"},
        {"Word": "desert",         "Vietnamese": "sa mạc",                  "Key Collocation(s)": "hot desert / live in the desert",             "Memory Trick": "DESERT has one S → DeSERT = deserted (empty). Don't confuse with deSSert!"},
        {"Word": "ocean",          "Vietnamese": "đại dương",               "Key Collocation(s)": "deep ocean / live in the ocean",              "Memory Trick": "O-C-E-A-N: Only Cool Enormous Aquatic Nature"},
        {"Word": "hotter",         "Vietnamese": "nóng hơn",                "Key Collocation(s)": "hotter than the forest / much hotter",        "Memory Trick": "HOT → HOTTER: double the T then add ER → the desert got HOTTER!"},
        {"Word": "colder",         "Vietnamese": "lạnh hơn",                "Key Collocation(s)": "colder than the desert / much colder in winter", "Memory Trick": "COLD + ER = just add ER → the Arctic just got COLDER!"},
        {"Word": "forest",         "Vietnamese": "rừng",                    "Key Collocation(s)": "tropical forest / animals in the forest",     "Memory Trick": "F-O-R-E-S-T: Find Our Rabbits Eating Sweet Things → animals eat in forests"},
        {"Word": "rainforest",     "Vietnamese": "rừng nhiệt đới",          "Key Collocation(s)": "tropical rainforest / in the rainforest",     "Memory Trick": "RAIN + FOREST = a forest that RAINS all the time → most biodiverse habitat!"},
        # ── TIER 2: Cambridge Flyers habitat vocabulary ───────────────────────
        {"Word": "Arctic",         "Vietnamese": "Bắc Cực",                 "Key Collocation(s)": "in the Arctic / Arctic animals",              "Memory Trick": "ARC + TIC = a frozen ARC → the Arctic is a giant icy curved region"},
        {"Word": "adapt",          "Vietnamese": "thích nghi",              "Key Collocation(s)": "adapt to the climate / adapt to their habitat", "Memory Trick": "A + DAPT = One solution adopted → to adapt = find ONE way to survive"},
        {"Word": "environment",    "Vietnamese": "môi trường",              "Key Collocation(s)": "the environment / natural environment",        "Memory Trick": "ENVIRON + MENT = to surround → your environment SURROUNDS you everywhere"},
        {"Word": "wetland",        "Vietnamese": "đất ngập nước",          "Key Collocation(s)": "wetland habitat / wetland animals",             "Memory Trick": "WET + LAND = land that is always WET → home for frogs, crabs, and birds"},
        {"Word": "grassland",      "Vietnamese": "đồng cỏ",                "Key Collocation(s)": "open grassland / grassland animals",            "Memory Trick": "GRASS + LAND = land covered in GRASS → lions roam African grasslands"},
        {"Word": "condition",      "Vietnamese": "điều kiện",              "Key Collocation(s)": "living conditions / harsh conditions",           "Memory Trick": "CONDI + TION = the state (trạng thái) → conditions = the state of the environment"},
        # ── TIER 3: Grammar (Comparatives: -er than) ─────────────────────────
        {"Word": "drier",          "Vietnamese": "khô hơn",                "Key Collocation(s)": "drier than the ocean / much drier",             "Memory Trick": "DRY → DRIER: drop Y, add IER → the desert is DRIER than the forest"},
        {"Word": "deeper",         "Vietnamese": "sâu hơn",                "Key Collocation(s)": "deeper than the river / much deeper",           "Memory Trick": "DEEP + ER = just add ER → the ocean gets DEEPER as you swim down"},
        {"Word": "wider",          "Vietnamese": "rộng hơn",               "Key Collocation(s)": "wider than a lake / much wider",               "Memory Trick": "WIDE + R = add R to WIDE → the grassland is WIDER than the forest"},
        {"Word": "compare",        "Vietnamese": "so sánh",                "Key Collocation(s)": "compare habitats / compare temperatures",        "Memory Trick": "COM + PARE = come in PAIRS → compare: A is ___er THAN B"},
        {"Word": "survive",        "Vietnamese": "tồn tại / sống sót",    "Key Collocation(s)": "survive in the desert / survive harsh conditions", "Memory Trick": "SUR + VIVE = super + alive → survive = stay alive in tough places"},
    ],
    41: [
        # ── TIER 1: Life Cycles vocabulary ───────────────────────────────────
        {"Word": "cycle",          "Vietnamese": "chu kỳ / vòng đời",      "Key Collocation(s)": "life cycle / the water cycle",                  "Memory Trick": "CYCLE = circle → a cycle always goes AROUND like a bicycle wheel"},
        {"Word": "larva",          "Vietnamese": "ấu trùng",                "Key Collocation(s)": "a butterfly larva / the larva hatches",         "Memory Trick": "LARVA rhymes with LAVA → the larva is as active as bubbling lava!"},
        {"Word": "pupa",           "Vietnamese": "nhộng",                   "Key Collocation(s)": "forms a pupa / the pupa stage",                 "Memory Trick": "PUPA sounds like POOF-A → poof! The caterpillar disappears into a pupa!"},
        {"Word": "adult",          "Vietnamese": "trưởng thành",            "Key Collocation(s)": "an adult butterfly / the adult stage",           "Memory Trick": "A-D-U-L-T: After Development Usually Life Transforms"},
        {"Word": "stage",          "Vietnamese": "giai đoạn",               "Key Collocation(s)": "the next stage / four stages in a life cycle",  "Memory Trick": "STAGE = theater stage → each STAGE of life is like an act in a play"},
        {"Word": "egg",            "Vietnamese": "trứng",                   "Key Collocation(s)": "lay an egg / hatch from an egg",                "Memory Trick": "E-G-G: Every Good Growth starts from an egg!"},
        {"Word": "caterpillar",    "Vietnamese": "sâu bướm",                "Key Collocation(s)": "a caterpillar eats leaves / green caterpillar",  "Memory Trick": "CATER + PILLAR = EATING (catering) while standing like a PILLAR → caterpillars eat all day!"},
        # ── TIER 2: Cambridge Flyers life science vocabulary ──────────────────
        {"Word": "butterfly",      "Vietnamese": "bươm bướm",              "Key Collocation(s)": "a colorful butterfly / butterfly wings",         "Memory Trick": "BUTTER + FLY = a fly with buttery yellow wings → beautiful!"},
        {"Word": "metamorphosis",  "Vietnamese": "sự biến thái",            "Key Collocation(s)": "complete metamorphosis / undergo metamorphosis",  "Memory Trick": "META + MORPH = beyond + change → metamorphosis = TOTAL transformation!"},
        {"Word": "tadpole",        "Vietnamese": "nòng nọc",               "Key Collocation(s)": "a tadpole grows legs / tiny tadpole",             "Memory Trick": "TAD + POLE = a tad (little bit) of a pole (stick) → a tiny stick with a head!"},
        {"Word": "seedling",       "Vietnamese": "cây mầm",                "Key Collocation(s)": "a seedling sprouts / tiny seedling",              "Memory Trick": "SEED + LING = a little (ling) seed that started growing → baby plant!"},
        {"Word": "transform",      "Vietnamese": "biến đổi hoàn toàn",     "Key Collocation(s)": "transform into a butterfly / transforms completely", "Memory Trick": "TRANS + FORM = cross + form → cross over to a COMPLETELY NEW FORM!"},
        {"Word": "sequence",       "Vietnamese": "trình tự / thứ tự",      "Key Collocation(s)": "the sequence of stages / in correct sequence",   "Memory Trick": "SEQ = follow (Latin) → a sequence = events that FOLLOW each other in order"},
        # ── TIER 3: Grammar (Sequence words + Present Simple) ────────────────
        {"Word": "first",          "Vietnamese": "đầu tiên",               "Key Collocation(s)": "first, the egg hatches / first stage",            "Memory Trick": "F-I-R-S-T: Follow In Right Sequence Then → FIRST = the very beginning"},
        {"Word": "then",           "Vietnamese": "sau đó",                  "Key Collocation(s)": "then it grows / then the larva forms",            "Memory Trick": "THEN = after THAT → first this, THEN that → sequence connector"},
        {"Word": "next",           "Vietnamese": "tiếp theo",               "Key Collocation(s)": "next, it becomes a pupa / the next stage",       "Memory Trick": "NEXT = the NECK connecting before and after → what comes NEXT in the sequence"},
        {"Word": "finally",        "Vietnamese": "cuối cùng",               "Key Collocation(s)": "finally it becomes an adult / finally, it emerges", "Memory Trick": "FINAL + LY = at the FINAL moment → the last step in the sequence"},
        {"Word": "complete",       "Vietnamese": "hoàn thành / hoàn chỉnh", "Key Collocation(s)": "complete metamorphosis / complete the cycle",    "Memory Trick": "COM + PLETE = all + filled → complete = ALL stages filled, nothing missing"},
    ],
    42: [
        # ── TIER 1: Water Cycle vocabulary ───────────────────────────────────
        {"Word": "evaporation",    "Vietnamese": "sự bốc hơi",             "Key Collocation(s)": "water evaporation / evaporation from the ocean",  "Memory Trick": "E-VAPOR-ATION: VAPOR is inside! → evaporation makes water into VAPOR"},
        {"Word": "condensation",   "Vietnamese": "sự ngưng tụ",            "Key Collocation(s)": "water condensation / condensation forms clouds",   "Memory Trick": "CON + DENSE + ATION = get DENSE → vapor condenses = gets denser → water drops"},
        {"Word": "precipitation",  "Vietnamese": "lượng mưa",              "Key Collocation(s)": "precipitation falls / as rain or snow",            "Memory Trick": "PRECIP sounds like DRIP → precipitation = water DRIPPING from the sky!"},
        {"Word": "vapor",          "Vietnamese": "hơi nước",               "Key Collocation(s)": "water vapor / vapor rises into the air",           "Memory Trick": "V-A-P-O-R: Very Airy Particles Of water Rise → vapor floats up!"},
        {"Word": "water cycle",    "Vietnamese": "vòng tuần hoàn nước",   "Key Collocation(s)": "the water cycle / the water cycle repeats",        "Memory Trick": "CYCLE = goes around → water CYCLES (goes around) forever in nature"},
        {"Word": "collection",     "Vietnamese": "sự tích tụ / thu gom",  "Key Collocation(s)": "water collection / collection in rivers and lakes",  "Memory Trick": "COLLECT + ION = collect → water collection = water COLLECTED in rivers and lakes"},
        {"Word": "runoff",         "Vietnamese": "nước chảy tràn",         "Key Collocation(s)": "water runoff / runoff flows into rivers",          "Memory Trick": "RUN + OFF = water RUNS OFF → after rain, water runs off the land into rivers"},
        # ── TIER 2: Cambridge Flyers earth science vocabulary ─────────────────
        {"Word": "groundwater",    "Vietnamese": "nước ngầm",              "Key Collocation(s)": "groundwater / underground water supply",           "Memory Trick": "GROUND + WATER = water UNDER the ground → hidden below your feet!"},
        {"Word": "cloud",          "Vietnamese": "đám mây",                "Key Collocation(s)": "form a cloud / water vapor forms clouds",          "Memory Trick": "C-L-O-U-D: Collected Liquid Orbiting Up Daily → clouds collect tiny water drops"},
        {"Word": "sunlight",       "Vietnamese": "ánh nắng mặt trời",     "Key Collocation(s)": "sunlight heats water / bright sunlight",           "Memory Trick": "SUN + LIGHT = the sun's light → sunlight HEATS water and starts evaporation!"},
        {"Word": "absorb",         "Vietnamese": "hấp thụ",                "Key Collocation(s)": "absorb sunlight / absorb water",                  "Memory Trick": "AB + SORB = suck up like a SPONGE → absorb = drink in energy or water"},
        {"Word": "release",        "Vietnamese": "giải phóng / thả ra",   "Key Collocation(s)": "release water vapor / clouds release rain",        "Memory Trick": "RE + LEASE = give back → release = let go and GIVE BACK to nature"},
        {"Word": "temperature",    "Vietnamese": "nhiệt độ",               "Key Collocation(s)": "high temperature / water temperature",             "Memory Trick": "TEMPER + ATURE = the TEMPER (mood) of the weather → hot or cold"},
        # ── TIER 3: Grammar (Sequence + Present Simple for processes) ─────────
        {"Word": "continuous",     "Vietnamese": "liên tục / không ngừng", "Key Collocation(s)": "a continuous process / continuous cycle",          "Memory Trick": "CONTINUE + OUS = keeps CONTINUING → continuous = always going, never stopping"},
        {"Word": "process",        "Vietnamese": "quá trình",              "Key Collocation(s)": "a natural process / the process of evaporation",   "Memory Trick": "PRO + CESS = move FORWARD → a process = steps that move forward one by one"},
        {"Word": "repeat",         "Vietnamese": "lặp lại",                "Key Collocation(s)": "repeat the cycle / the process repeats endlessly", "Memory Trick": "RE + PEAT = do it AGAIN → repeat = do it again and again and again"},
        {"Word": "stage",          "Vietnamese": "giai đoạn",              "Key Collocation(s)": "each stage of the cycle / four stages",            "Memory Trick": "STAGE = theater stage → each stage of the water cycle is like nature's ACT"},
        {"Word": "flow",           "Vietnamese": "chảy / luân chuyển",    "Key Collocation(s)": "water flows / flow into the ocean",                "Memory Trick": "F-L-O-W: Following Liquid Onwards Warmly → water flows following the cycle"},
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
# PART 2 generator  —  numbered lines per session
# Session 1: words 1-7 (TIER 1)
# Session 2: words 8-13 (TIER 2)
# Session 3: words 14-18 (TIER 3)
# ─────────────────────────────────────────────────────────────────────────────
SESSION_VOCAB_RANGES = {1: (0, 7), 2: (7, 13), 3: (13, 18)}

def build_part2_content(week_num, session_num):
    vocab = VOCAB[week_num]
    start, end = SESSION_VOCAB_RANGES[session_num]
    subset = vocab[start:end]
    lines = []
    for i, v in enumerate(subset, 1):
        word = v['Word']
        viet = v['Vietnamese']
        trick = v['Memory Trick']
        colloc = v['Key Collocation(s)']
        first_colloc = colloc.split(' / ')[0]
        # Pull simple head noun/verb for fill-in
        hw = word.split(' → ')[0].split()[0]
        lines += [
            '%d. %s (Vietnamese: %s)' % (i, word, viet),
            '→ Memory trick: %s' % trick,
            '→ Write 3 times: ___________ ___________ ___________',
            '→ Key Collocation: %s' % first_colloc,
            '→ Collocation practice:',
            'a. Every _____________________________ needs food and water to live.',
            'b. Can you use "%s" in a sentence? ________________________________________' % hw,
            '→ Your turn: ____________________________________________________________',
        ]
    lines.append('[ Sub-total: ___ / %d ]' % len(subset))
    return lines

def build_part2_title(week_num, session_num):
    vocab = VOCAB[week_num]
    start, end = SESSION_VOCAB_RANGES[session_num]
    tier_label = {1: 'TIER 1 — Story & Core Words', 2: 'TIER 2 — Cambridge Science Words', 3: 'TIER 3 — Grammar & Reasoning Words'}
    words_preview = ', '.join(v['Word'] for v in vocab[start:start+4])
    return 'PART 2: VOCABULARY BUILDING — %s: %s...' % (tier_label[session_num], words_preview)

# ─────────────────────────────────────────────────────────────────────────────
# PART 3 data  —  L1-L5 numbered exercises per week per session
# ─────────────────────────────────────────────────────────────────────────────
PART3 = {
    37: {
        1: [
            '[O] L1 — Choose the correct word (10 items)',
            'Word box: [ living / non-living / breathe / grow / move / survive / energy / organism / characteristic / reproduce ]',
            '1. Things that are alive are called _____________ things.',
            '2. A rock cannot breathe or grow. It is a _____________ thing.',
            '3. Every living thing needs air to _____________.',
            '4. Baby animals and young plants need to eat and _____________ bigger.',
            '5. Fish and birds can _____________ from place to place.',
            '6. All living things must _____________ — they need food, water, and air.',
            '7. Animals get _____________ from the food they eat.',
            '8. Being able to breathe is a _____________ of all living things.',
            '9. A tiny ant and a giant tree are both living _____________ s.',
            '10. Animals _____________ by having babies, and plants do it by making seeds.',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — True (T) or False (F)? (6 items)',
            '1. A cat is a living thing because it breathes and grows.  ___',
            '2. A rock can move and breathe on its own.  ___',
            '3. All living things need energy from food.  ___',
            '4. A pencil can reproduce by making baby pencils.  ___',
            '5. A tree is living because it grows from a seed.  ___',
            '6. Non-living things can respond to changes around them.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Fill in the blank with "because" (8 items)',
            '1. A dog is a living thing _____________ it breathes, grows, and moves.',
            '2. A rock is non-living _____________ it does not breathe or grow.',
            '3. Plants are living things _____________ they grow from seeds.',
            '4. A car is non-living _____________ it cannot reproduce.',
            '5. Fish are living organisms _____________ they need food and water to survive.',
            '6. An insect is alive _____________ it responds to light and heat.',
            '7. I know a tree is living _____________ it grows taller every year.',
            '8. Water is non-living _____________ it has no energy of its own.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L4 — Unscramble the sentence (5 items)',
            '1. living / A / dog / thing / is / a   →   ___________________________________',
            '2. non-living / rock / A / because / is / it / not / does / grow   →   ___________________________________',
            '3. things / Living / need / to / water / survive / and / food   →   ___________________________________',
            '4. energy / Animals / food / from / get   →   ___________________________________',
            '5. organism / A / tree / is / living / a / because / it / grows   →   ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence about a LIVING thing, using "because":',
            '   _______________________________________________________________________',
            '2. Write a sentence about a NON-LIVING thing, using "because":',
            '   _______________________________________________________________________',
            '3. Write a sentence about WHY animals need energy:',
            '   _______________________________________________________________________',
            '4. Write one CHARACTERISTIC of living things in a sentence:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        2: [
            '[O] L1 — Match: word → definition (10 items)',
            'Word box: [ organism / reproduce / respond / nutrition / classify / characteristic / investigate / evidence / because / therefore ]',
            '1. a living thing with organs → _____________',
            '2. to make babies or seeds → _____________',
            '3. to react to changes in the world → _____________',
            '4. what food gives your body → _____________',
            '5. to sort into groups → _____________',
            '6. a special feature of something → _____________',
            '7. to find out facts about something → _____________',
            '8. proof that something is true → _____________',
            '9. a word that gives a reason → _____________',
            '10. a word meaning "for that reason" → _____________',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank (8 items)',
            'Word box: [ organism / nutrition / reproduce / characteristic / evidence / classify / respond / investigate ]',
            '1. Scientists _____________ animals into groups: mammals, reptiles, birds...',
            '2. Every living _____________ needs food, water, and air.',
            '3. Animals get _____________ from the food they eat.',
            '4. Being able to breathe is a _____________ of all living things.',
            '5. Living things can _____________ by having babies or making seeds.',
            '6. Flowers _____________ to sunlight by turning their petals toward it.',
            '7. The detective is looking for _____________ that an animal lives here.',
            '8. Let us _____________ whether a tree is really a living thing.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — True (T) or False (F)? (6 items)',
            '1. A living organism needs nutrition to survive.  ___',
            '2. Rocks can reproduce by making baby rocks.  ___',
            '3. Scientists classify living things to understand them better.  ___',
            '4. A characteristic of reptiles is that they have feathers.  ___',
            '5. Evidence helps scientists reach a conclusion.  ___',
            '6. A plant responds to sunlight by growing toward it.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Complete the sentence (5 items)',
            '1. A butterfly is a living organism because ________________________________________.',
            '2. Scientists classify animals because ________________________________________.',
            '3. A rock is not a living thing; therefore, ________________________________________.',
            '4. Investigators look for evidence to ________________________________________.',
            '5. All living things respond to changes because ________________________________________.',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence using "organism":',
            '   _______________________________________________________________________',
            '2. Write a sentence using "because" to explain a conclusion:',
            '   _______________________________________________________________________',
            '3. Write a sentence using "therefore":',
            '   _______________________________________________________________________',
            '4. Write a sentence using "classify":',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        3: [
            '[O] L1 — Read the clue. Write the correct word (10 items)',
            'Word box: [ living / non-living / breathe / grow / reproduce / evidence / investigate / conclusion / because / therefore ]',
            '1. This word means "not alive": _____________',
            '2. This is what you do when you take air in and out: _____________',
            '3. This is what a baby does to become bigger: _____________',
            '4. Scientists do this when they look for facts: _____________',
            '5. This means the same as "proof": _____________',
            '6. This is what you say at the end of an investigation: _____________',
            '7. A dog, a tree, and a fish are all examples of this: _____________',
            '8. This word gives a reason for something: _____________',
            '9. This means "for that reason": _____________',
            '10. This is what animals do when they have babies: _____________',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank — Revision (8 items)',
            '1. A _____________ (living / non-living) thing can breathe, grow, and move.',
            '2. A rock is non-living _____________ it does not breathe.',
            '3. Scientists use _____________ to prove that something is true.',
            '4. After their investigation, they reached a _____________ about the animal.',
            '5. A tree can _____________ by making seeds, so it is a living thing.',
            '6. All living things _____________ to changes in their environment.',
            '7. _____________ , if a thing does not grow, it is non-living.',
            '8. Good scientists always _____________ before writing a conclusion.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — Put the investigation steps in order. Write 1-5. (5 items)',
            '___ a. Write a conclusion.',
            '___ b. Look for evidence.',
            '___ c. Ask: "Is this a living thing?"',
            '___ d. Classify the thing as living or non-living.',
            '___ e. Investigate: observe its characteristics.',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L4 — Correct the mistake (5 items)',
            '1. A fish are a non-living thing. → ___________________________________',
            '2. A rock can breathes and grows. → ___________________________________',
            '3. All living things does not need food. → ___________________________________',
            '4. Because rocks cannot reproduce, its is living. → ___________________________________',
            '5. Scientists investigates living things to find evidences. → ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your science investigation report (4 items)',
            '1. Choose a living thing. Write its name: _____________',
            '2. Write ONE characteristic that shows it is living:',
            '   _______________________________________________________________________',
            '3. Write a sentence using "because" about your chosen thing:',
            '   _______________________________________________________________________',
            '4. Write your conclusion in one sentence:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 32 ]',
        ],
    },
    38: {
        1: [
            '[O] L1 — Choose the correct word (10 items)',
            'Word box: [ mammal / reptile / amphibian / insect / bird / fish / warm-blooded / cold-blooded / lay eggs / fur ]',
            '1. A dog, a cat, and a whale are all examples of a _____________.',
            '2. A lizard, a snake, and a crocodile belong to this group: _____________.',
            '3. A frog and a toad live both in water and on land. They are _____________.',
            '4. An ant, a bee, and a butterfly have six legs. They are _____________ s.',
            '5. A robin, an eagle, and a penguin all have feathers. They are _____________ s.',
            '6. A salmon and a goldfish live in water and have scales. They are _____________ s.',
            '7. Mammals are _____________ — their body temperature stays warm.',
            '8. Reptiles are _____________ — their body temperature changes with the air.',
            '9. Hens and snakes both _____________ to reproduce.',
            '10. Mammals are covered in soft _____________ to stay warm.',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — True (T) or False (F)? (6 items)',
            '1. A dolphin is a mammal because it breathes air and feeds its young with milk.  ___',
            '2. All reptiles are warm-blooded.  ___',
            '3. Amphibians can live in water and on land.  ___',
            '4. Insects always have eight legs.  ___',
            '5. Birds lay eggs to reproduce.  ___',
            '6. Fish breathe air through lungs like humans.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Fill in the blank — Present Simple (has/have, lays, lives) (8 items)',
            '1. A snake _____________ (has / have) scales and is cold-blooded.',
            '2. A hen _____________ (lay / lays) eggs every day.',
            '3. A dolphin _____________ (lives / live) in the ocean but breathes air.',
            '4. Mammals _____________ (has / have) fur or hair on their bodies.',
            '5. A frog _____________ (live / lives) near rivers and ponds.',
            '6. A parrot _____________ (has / have) colourful feathers.',
            '7. An ant _____________ (has / have) six legs and three body sections.',
            '8. A whale _____________ (give / gives) birth to live young.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L4 — Unscramble the sentence (5 items)',
            '1. mammal / is / A / dog / a   →   ___________________________________',
            '2. cold-blooded / Reptiles / are / scales / have / and   →   ___________________________________',
            '3. water / in / Fish / live / and / scales / have   →   ___________________________________',
            '4. both / live / Amphibians / and / water / on / in / land   →   ___________________________________',
            '5. feathers / have / lay / Birds / and / eggs   →   ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence about a mammal using "has":',
            '   _______________________________________________________________________',
            '2. Write a sentence about a reptile using "is cold-blooded":',
            '   _______________________________________________________________________',
            '3. Write a sentence about a bird using "lays":',
            '   _______________________________________________________________________',
            '4. Write a sentence comparing a mammal and a reptile:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        2: [
            '[O] L1 — Match: animal feature → group name (10 items)',
            '1. has fur, warm-blooded, gives birth → _____________',
            '2. has scales, cold-blooded, lays eggs → _____________',
            '3. lives in water AND land → _____________',
            '4. has six legs, three body sections → _____________',
            '5. has feathers, lays eggs, warm-blooded → _____________',
            '6. lives in water, has gills → _____________',
            '7. a vertebrate with a spine and four legs → _____________',
            '8. covered in smooth, moist skin → _____________',
            '9. warm-blooded vertebrate feeding young with milk → _____________',
            '10. cold-blooded vertebrate with scales → _____________',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank (8 items)',
            'Word box: [ vertebrate / scales / feathers / fur / spine / classify / belong to / species ]',
            '1. Scientists _____________ animals into groups to study them.',
            '2. A fish has _____________ on its body instead of fur.',
            '3. A bird has _____________ that help it fly.',
            '4. A lion has thick _____________ to keep it warm.',
            '5. All animals with a backbone are called _____________ s.',
            '6. The backbone is also called the _____________ .',
            '7. A wolf and a dog _____________ the mammal group.',
            '8. There are millions of different animal _____________ on Earth.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — True (T) or False (F)? (6 items)',
            '1. All vertebrates have a spine running down their backs.  ___',
            '2. A snake belongs to the amphibian group.  ___',
            '3. Feathers help birds fly and keep them warm.  ___',
            '4. There is only one species of frog in the world.  ___',
            '5. Scientists classify animals to understand them better.  ___',
            '6. A shark is a fish because it lives in the ocean and has gills.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Complete the sentence (5 items)',
            '1. A whale belongs to the mammal group because ________________________________________.',
            '2. Reptiles are cold-blooded, which means ________________________________________.',
            '3. Scientists classify animals because ________________________________________.',
            '4. A bird has feathers and lays eggs; therefore, ________________________________________.',
            '5. Amphibians are special because they can ________________________________________.',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence using "vertebrate":',
            '   _______________________________________________________________________',
            '2. Write a sentence using "belongs to":',
            '   _______________________________________________________________________',
            '3. Write a sentence about an animal species you know:',
            '   _______________________________________________________________________',
            '4. Write a sentence classifying your favourite animal:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        3: [
            '[O] L1 — Read the clue. Write the group name (10 items)',
            '1. I have fur. I feed my babies milk. I am a _____________ .',
            '2. I have scales. I am cold-blooded. I lay eggs. I am a _____________ .',
            '3. I can live in water AND on land. My skin is smooth. I am an _____________ .',
            '4. I have six legs and three body parts. I am an _____________ .',
            '5. I have feathers and a beak. I lay eggs. I am a _____________ .',
            '6. I have gills. I live in water. I have scales. I am a _____________ .',
            '7. I give birth to live young. My baby drinks my milk. I am a _____________ .',
            '8. I live in a pond as a tadpole first, then grow legs. I am an _____________ .',
            '9. I have a backbone / spine. I belong to the _____________ group.',
            '10. All mammals, birds, fish, reptiles, and amphibians are _____________ s.',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank — Revision (8 items)',
            '1. A _____________ (mammal / reptile) is warm-blooded and has fur.',
            '2. An eagle has _____________ and lays eggs, so it is a bird.',
            '3. A frog belongs to the _____________ group because it lives in both water and land.',
            '4. Scientists _____________ animals into five main vertebrate groups.',
            '5. A whale _____________ to the mammal group, not the fish group.',
            '6. All vertebrates have a _____________ running down their backs.',
            '7. A lizard is a _____________ because it is cold-blooded and has scales.',
            '8. There are thousands of _____________ of beetles in the insect group alone.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — Correct the mistake (5 items)',
            '1. A frog are a reptile. → ___________________________________',
            '2. Birds has scales instead of feathers. → ___________________________________',
            '3. All insects have eight legs. → ___________________________________',
            '4. A whale live in the ocean, so it is a fish. → ___________________________________',
            '5. Reptiles is warm-blooded animals. → ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L4 — Compare two groups. Write one similarity and one difference. (4 items)',
            '1. Birds vs Reptiles:  Similarity: _______________   Difference: _______________',
            '2. Mammals vs Fish:  Similarity: _______________   Difference: _______________',
            '3. Amphibians vs Reptiles:  Similarity: _______________   Difference: _______________',
            '4. Insects vs Birds:  Similarity: _______________   Difference: _______________',
            '[ Sub-total: ___ / 4 ]',
            '',
            '[O] L5 — Write your own sentences (3 items)',
            '1. Write a sentence using "belongs to":',
            '   _______________________________________________________________________',
            '2. Write a sentence using Present Simple (has / lays / lives):',
            '   _______________________________________________________________________',
            '3. Write one sentence classifying an animal you know:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 3 ]',
            '[ PART 3 TOTAL: ___ / 30 ]',
        ],
    },
    39: {
        1: [
            '[O] L1 — Choose the correct word (10 items)',
            'Word box: [ lay eggs / give birth / hatch / protect / develop / oviparous / viviparous / embryo / shell / offspring ]',
            '1. A chicken and a snake are _____________ animals — they produce eggs.',
            '2. A dog and a whale are _____________ animals — their babies grow inside the mother.',
            '3. Birds and reptiles both _____________ to reproduce.',
            '4. Mammals _____________ to live young.',
            '5. Baby birds _____________ from their eggs after being incubated.',
            '6. Parent animals _____________ their young from predators.',
            '7. An _____________ grows inside the egg before it hatches.',
            '8. A bird egg has a hard _____________ to protect the baby inside.',
            '9. A baby animal still growing inside its mother is called an _____________ .',
            '10. The young of any animal are called its _____________ .',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — True (T) or False (F)? (6 items)',
            '1. Oviparous animals lay eggs to reproduce.  ___',
            '2. All viviparous animals are reptiles.  ___',
            '3. A baby chicken hatches from an egg.  ___',
            '4. Only birds protect their offspring.  ___',
            '5. An embryo develops inside either an egg or a mother.  ___',
            '6. Mammals lay eggs just like birds do.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Fill in the blank — Both / Unlike / but (8 items)',
            '1. _____________ birds and reptiles are oviparous — they both lay eggs.',
            '2. _____________ birds, mammals do not lay eggs; they give birth.',
            '3. Crocodiles lay eggs, _____________ crocodiles protect their young.',
            '4. _____________ snakes and frogs reproduce by laying eggs.',
            '5. A hen lays eggs, _____________ a dog gives birth to puppies.',
            '6. _____________ oviparous and viviparous animals protect their offspring.',
            '7. _____________ reptiles, most mammals give birth to live young.',
            '8. A shark gives birth to live young, _____________ most fish lay eggs.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L4 — Unscramble the sentence (5 items)',
            '1. oviparous / A / hen / is / animal / an   →   ___________________________________',
            '2. eggs / lay / Birds / to / reproduce   →   ___________________________________',
            '3. egg / the / hatches / Baby / the / from / bird   →   ___________________________________',
            '4. viviparous / Dogs / because / are / give / they / birth   →   ___________________________________',
            '5. protect / their / Parents / young / offspring   →   ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence about an oviparous animal using "lay eggs":',
            '   _______________________________________________________________________',
            '2. Write a sentence about a viviparous animal using "give birth":',
            '   _______________________________________________________________________',
            '3. Write a sentence using "both":',
            '   _______________________________________________________________________',
            '4. Write a sentence using "unlike":',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        2: [
            '[O] L1 — Match: animal → reproduction method (10 items)',
            'Write "O" (oviparous) or "V" (viviparous) next to each animal:',
            '1. hen  ___        6. whale  ___',
            '2. dog  ___        7. crocodile  ___',
            '3. snake  ___      8. dolphin  ___',
            '4. cat  ___        9. penguin  ___',
            '5. frog  ___       10. shark  ___',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank (8 items)',
            'Word box: [ incubate / nest / shell / offspring / alike / unlike / similar / compare ]',
            '1. Birds build a _____________ to keep their eggs safe and warm.',
            '2. A bird egg has a hard _____________ to protect the embryo.',
            '3. Hens _____________ their eggs by sitting on them to keep them warm.',
            '4. Parent animals protect their _____________ from danger.',
            '5. Birds and reptiles are _____________ in that both are oviparous.',
            '6. _____________ reptiles, mammals give birth to live young.',
            '7. A dog and a cat are _____________ — both are viviparous mammals.',
            '8. When we _____________ a bird and a dog, we see big differences.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — True (T) or False (F)? (6 items)',
            '1. Birds incubate their eggs to keep them warm.  ___',
            '2. Incubating eggs means putting them in cold water.  ___',
            '3. Unlike birds, most mammals give birth to live young.  ___',
            '4. Both oviparous and viviparous parents protect their offspring.  ___',
            '5. A nest is where birds lay and protect their eggs.  ___',
            '6. All snakes are viviparous.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Complete the comparison (5 items)',
            '1. Both birds and reptiles ________________________________________.',
            '2. Unlike mammals, birds ________________________________________.',
            '3. A dog and a cat are similar because both ________________________________________.',
            '4. The difference between oviparous and viviparous animals is ________________________________________.',
            '5. Both oviparous and viviparous parents protect their young because ________________________________________.',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence using "incubate":',
            '   _______________________________________________________________________',
            '2. Write a sentence using "offspring":',
            '   _______________________________________________________________________',
            '3. Write a sentence using "both ... and ...":',
            '   _______________________________________________________________________',
            '4. Write a sentence using "unlike":',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        3: [
            '[O] L1 — Read the clue. Write the word (10 items)',
            'Word box: [ oviparous / viviparous / shell / embryo / hatch / incubate / nest / similar / difference / compare ]',
            '1. An animal that lays eggs is _____________ .',
            '2. An animal that gives birth to live young is _____________ .',
            '3. A baby bird does this when it breaks out of the egg: _____________ .',
            '4. A hen sits on her eggs to _____________ them.',
            '5. The hard outer cover of an egg is the _____________ .',
            '6. The tiny life growing inside an egg or a mother is an _____________ .',
            '7. Birds build this to protect their eggs: _____________ .',
            '8. Two animals that look the same in some ways are _____________ .',
            '9. The way two things are different is the _____________ .',
            '10. When you look at two things side by side, you _____________ them.',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Correct the mistake (6 items)',
            '1. A hen is viviparous because it lay eggs. → ___________________________________',
            '2. Mammals is oviparous because they give birth. → ___________________________________',
            '3. Baby birds hatch from the nest. → ___________________________________',
            '4. Both birds and mammals lays eggs. → ___________________________________',
            '5. Unlike mammals, reptiles gives birth to live young. → ___________________________________',
            '6. A dog and a cat is difference because one is bigger. → ___________________________________',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Write the comparison (Both/Unlike/but) (6 items)',
            '1. Bird ↔ reptile — both lay eggs:',
            '   _____________ birds and reptiles _______________________________________.',
            '2. Mammal ↔ bird — mammals don\'t lay eggs:',
            '   _____________ birds, mammals ___________________________________________.',
            '3. Dog ↔ cat — both are viviparous:',
            '   A dog gives birth to puppies, _____________ a cat also _______________.',
            '4. Hen ↔ whale — hen lays eggs, whale gives birth:',
            '   _____________ .',
            '5. Crocodile ↔ dolphin:',
            '   _____________ .',
            '6. Frog ↔ dog:',
            '   _____________ .',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Put the egg life cycle in order. Write 1-5. (5 items)',
            '___ a. The mother keeps the egg warm (incubates it).',
            '___ b. The egg hatches and a chick comes out.',
            '___ c. The mother lays the egg in a nest.',
            '___ d. The chick grows into an adult bird.',
            '___ e. The embryo develops inside the egg.',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (3 items)',
            '1. Write a sentence comparing oviparous and viviparous animals:',
            '   _______________________________________________________________________',
            '2. Write a sentence using "both ... and ..." about two animals:',
            '   _______________________________________________________________________',
            '3. Write a sentence using "unlike" about two animals:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 3 ]',
            '[ PART 3 TOTAL: ___ / 30 ]',
        ],
    },
    40: {
        1: [
            '[O] L1 — Choose the correct word (10 items)',
            'Word box: [ habitat / desert / ocean / forest / rainforest / Arctic / adapt / environment / hotter / colder ]',
            '1. The place where an animal naturally lives is its _____________ .',
            '2. A camel lives in the hot _____________ where it is very dry.',
            '3. Sharks and whales live in the deep _____________ .',
            '4. Monkeys and parrots live in the tropical _____________ .',
            '5. The Amazon is the largest tropical _____________ in the world.',
            '6. Polar bears live in the _____________ , the coldest place on Earth.',
            '7. Animals _____________ to their habitats — they change over time to survive.',
            '8. Your _____________ is everything around you: the air, water, and land.',
            '9. The desert is much _____________ than the Arctic.',
            '10. The Arctic is much _____________ than the rainforest.',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — True (T) or False (F)? (6 items)',
            '1. A polar bear is adapted to live in the cold Arctic.  ___',
            '2. All animals live in the same type of habitat.  ___',
            '3. The rainforest is hotter and wetter than the desert.  ___',
            '4. Animals change their habitat to match the weather.  ___',
            '5. A camel can survive in the desert because it stores water in its hump.  ___',
            '6. The ocean is one type of aquatic habitat.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Fill in the blank — Comparatives (-er than) (8 items)',
            '1. The Sahara Desert is much _____________ (hot → hotter) than the Amazon Rainforest.',
            '2. The Arctic is _____________ (cold → ?) than the rainforest.',
            '3. The ocean is _____________ (deep → ?) than a river.',
            '4. A desert is _____________ (dry → drier) than a wetland.',
            '5. The rainforest is _____________ (wide → ?) than a grassland.',
            '6. A rainforest is _____________ (wet → wetter) than a desert.',
            '7. Mountains are _____________ (tall → taller) than hills.',
            '8. The Pacific Ocean is _____________ (large → larger) than the Arctic Ocean.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L4 — Unscramble the sentence (5 items)',
            '1. habitat / camel / in / lives / A / the / desert   →   ___________________________________',
            '2. hotter / desert / The / the / is / than / rainforest   →   ___________________________________',
            '3. in / Arctic / lives / the / bear / Polar / A   →   ___________________________________',
            '4. to / Animals / their / adapt / habitat   →   ___________________________________',
            '5. deep / ocean / is / The / the / than / river / deeper   →   ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence about a habitat using "is hotter than":',
            '   _______________________________________________________________________',
            '2. Write a sentence about an animal that adapts to a cold habitat:',
            '   _______________________________________________________________________',
            '3. Write a sentence using "is colder than":',
            '   _______________________________________________________________________',
            '4. Write a sentence about your favourite habitat:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        2: [
            '[O] L1 — Match: animal → habitat (10 items)',
            '1. camel  →  _____________      6. clownfish  →  _____________',
            '2. polar bear  →  _____________  7. monkey  →  _____________',
            '3. lion  →  _____________       8. frog  →  _____________',
            '4. whale  →  _____________      9. cactus  →  _____________',
            '5. eagle  →  _____________      10. penguin  →  _____________',
            'Habitats: [ desert / Arctic / ocean / rainforest / grassland / wetland / mountains ]',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank (8 items)',
            'Word box: [ adapt / environment / wetland / grassland / condition / drier / deeper / wider ]',
            '1. A wetland is a _____________ (wet / dry) habitat where frogs and crabs live.',
            '2. Lions hunt on the open _____________ of Africa.',
            '3. Animals _____________ to their environment over many years.',
            '4. Your _____________ includes the air, water, and animals around you.',
            '5. Harsh weather _____________ s make survival very difficult.',
            '6. The desert is _____________ than the wetland.',
            '7. The Mariana Trench is the _____________ place in the ocean.',
            '8. The Pacific Ocean is _____________ than the Atlantic Ocean.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — True (T) or False (F)? (6 items)',
            '1. Wetlands are very dry habitats with no water.  ___',
            '2. Animals that adapt survive better in their habitat.  ___',
            '3. A grassland is wider and more open than a forest.  ___',
            '4. All environments have the same conditions.  ___',
            '5. A deeper ocean has less light and is colder.  ___',
            '6. Camels are adapted to survive in cold, wet forests.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Complete the comparison sentence (5 items)',
            '1. The desert is much __________ than the rainforest. (hot)',
            '2. The Arctic is __________ than the grassland. (cold)',
            '3. The ocean is __________ than a river. (deep)',
            '4. A desert is __________ than a wetland. (dry)',
            '5. The Amazon Rainforest is __________ than a city park. (wide)',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence using "adapts to":',
            '   _______________________________________________________________________',
            '2. Write a sentence using "is drier than":',
            '   _______________________________________________________________________',
            '3. Write a sentence about the grassland habitat:',
            '   _______________________________________________________________________',
            '4. Write a sentence about an animal and its environment:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        3: [
            '[O] L1 — Read the clue. Write the word (10 items)',
            'Word box: [ habitat / adapt / environment / grassland / wetland / condition / hotter / colder / drier / survive ]',
            '1. The natural home of an animal: _____________ .',
            '2. To change so you can live better in a place: _____________ .',
            '3. Everything around you — air, water, land: _____________ .',
            '4. An open area covered in grass where lions live: _____________ .',
            '5. A wet habitat where frogs and crabs live: _____________ .',
            '6. The state of the weather or a place: _____________ .',
            '7. The desert is this compared to the rainforest: _____________ .',
            '8. The Arctic is this compared to the desert: _____________ .',
            '9. The desert is this compared to the ocean: _____________ .',
            '10. To stay alive in a difficult place: _____________ .',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Correct the mistake (6 items)',
            '1. A camel live in the ocean. → ___________________________________',
            '2. The Arctic are hotter than the desert. → ___________________________________',
            '3. Animals adapts to their habitats over years. → ___________________________________',
            '4. The ocean is more deeper than the river. → ___________________________________',
            '5. A grassland are a wet habitat. → ___________________________________',
            '6. Polar bears survives in the hot desert. → ___________________________________',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Write comparisons using -er than (6 items)',
            '1. desert → rainforest (hot):  The desert is __________ than the rainforest.',
            '2. Arctic → desert (cold):  The Arctic is __________ than the desert.',
            '3. ocean → river (deep):  The ocean is __________ than the river.',
            '4. desert → forest (dry):  The desert is __________ than the forest.',
            '5. ocean → lake (wide):  The ocean is __________ than the lake.',
            '6. mountain → hill (tall):  The mountain is __________ than the hill.',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Write the correct comparative form (5 items)',
            '1. hot → _____________ than',
            '2. cold → _____________ than',
            '3. deep → _____________ than',
            '4. dry → _____________ than',
            '5. wide → _____________ than',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (3 items)',
            '1. Write a sentence about an animal adapting to its habitat:',
            '   _______________________________________________________________________',
            '2. Write a comparison using "-er than" about two habitats:',
            '   _______________________________________________________________________',
            '3. Write a sentence about why an animal survives in its habitat:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 3 ]',
            '[ PART 3 TOTAL: ___ / 30 ]',
        ],
    },
    41: {
        1: [
            '[O] L1 — Choose the correct word (10 items)',
            'Word box: [ cycle / larva / pupa / adult / stage / egg / caterpillar / butterfly / metamorphosis / tadpole ]',
            '1. The word for a baby butterfly before it forms wings: _____________ .',
            '2. The stage when the caterpillar wraps itself in a cocoon: _____________ .',
            '3. The full-grown butterfly is the _____________ stage.',
            '4. The complete journey from birth to adult is the life _____________ .',
            '5. The first step in a butterfly\'s life is the _____________ stage.',
            '6. The total change from egg to butterfly is called _____________ .',
            '7. A baby frog before it grows legs is a _____________ .',
            '8. The caterpillar is the _____________ of a butterfly.',
            '9. A butterfly life cycle has four _____________ s: egg, larva, pupa, adult.',
            '10. A beautiful _____________ comes out of the pupa.',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — True (T) or False (F)? (6 items)',
            '1. A caterpillar is the larva stage of a butterfly.  ___',
            '2. The pupa stage comes before the egg stage.  ___',
            '3. Metamorphosis means a total change in body form.  ___',
            '4. A tadpole will grow into a butterfly.  ___',
            '5. Every life cycle eventually returns to the beginning.  ___',
            '6. The adult butterfly can lay eggs to start the cycle again.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Fill in the blank — Sequence words (First / Then / Next / Finally) (8 items)',
            '1. _____________ , the butterfly lays a tiny egg on a leaf.',
            '2. _____________ , the egg hatches and a caterpillar comes out.',
            '3. _____________ , the caterpillar eats leaves and grows bigger.',
            '4. _____________ , the caterpillar wraps itself into a pupa.',
            '5. _____________ , the pupa changes slowly inside the cocoon.',
            '6. _____________ , the adult butterfly breaks out of the pupa.',
            '7. The egg is the _____________ stage, and the adult is the _____________ stage.',
            '8. _____________ , the adult butterfly lays eggs and the cycle begins again.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L4 — Put the butterfly life cycle in order. Write 1-4. (4 items)',
            '___ a. A caterpillar eats leaves and grows.',
            '___ b. A butterfly lays eggs on a leaf.',
            '___ c. An adult butterfly emerges from the pupa.',
            '___ d. The caterpillar wraps itself into a pupa.',
            '[ Sub-total: ___ / 4 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence using "first" about a butterfly\'s life:',
            '   _______________________________________________________________________',
            '2. Write a sentence using "then" about the larva stage:',
            '   _______________________________________________________________________',
            '3. Write a sentence using "next" about the pupa stage:',
            '   _______________________________________________________________________',
            '4. Write a sentence using "finally" about the adult stage:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 32 ]',
        ],
        2: [
            '[O] L1 — Match: life cycle word → meaning (10 items)',
            '1. metamorphosis → _____________',
            '2. transform → _____________',
            '3. sequence → _____________',
            '4. complete → _____________',
            '5. seedling → _____________',
            '6. tadpole → _____________',
            '7. pupa → _____________',
            '8. cycle → _____________',
            '9. stage → _____________',
            '10. larva → _____________',
            'Meanings: [ a total change in form / to change completely / the correct order / all stages finished / a baby plant / a baby frog / the cocoon stage / goes around and around / one part of the journey / the caterpillar stage ]',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank (8 items)',
            'Word box: [ metamorphosis / tadpole / seedling / transform / sequence / complete / cycle / stage ]',
            '1. A frog starts as a tiny _____________ in the water.',
            '2. A caterpillar goes through _____________ to become a butterfly.',
            '3. The butterfly life cycle is a _____________ — it keeps going around.',
            '4. In the pupa stage, the caterpillar begins to _____________ .',
            '5. A tiny _____________ grows out of a seed in the soil.',
            '6. The _____________ of stages is: egg → larva → pupa → adult.',
            '7. When the butterfly emerges, it has _____________ metamorphosis.',
            '8. Each _____________ of the life cycle is important.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — True (T) or False (F)? (6 items)',
            '1. A tadpole grows into a frog through metamorphosis.  ___',
            '2. A seedling is a fully-grown tree.  ___',
            '3. The sequence of a butterfly\'s life is: egg → larva → pupa → adult.  ___',
            '4. A life cycle is complete when the adult dies.  ___',
            '5. A caterpillar transforms into a butterfly inside the pupa.  ___',
            '6. All plants start their life cycle as a seedling.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Complete the sentence (5 items)',
            '1. A tadpole transforms into a frog through ________________________________________.',
            '2. The sequence of a butterfly\'s life cycle is: ________________________________________.',
            '3. A seedling grows from a seed and eventually ________________________________________.',
            '4. When the caterpillar is inside the pupa, it begins to ________________________________________.',
            '5. The life cycle is complete when the adult ________________________________________.',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (3 items)',
            '1. Write a sentence using "metamorphosis":',
            '   _______________________________________________________________________',
            '2. Write a sentence using "transforms into":',
            '   _______________________________________________________________________',
            '3. Write a sentence about a life cycle you know (frog, butterfly, or plant):',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 3 ]',
            '[ PART 3 TOTAL: ___ / 32 ]',
        ],
        3: [
            '[O] L1 — Read the clue. Write the word (10 items)',
            'Word box: [ cycle / stage / first / then / next / finally / complete / transform / sequence / adult ]',
            '1. A journey that keeps going around and around: _____________ .',
            '2. One step in the journey: _____________ .',
            '3. The very beginning of the sequence: _____________ .',
            '4. What happens after "first": _____________ .',
            '5. The step that comes after "then": _____________ .',
            '6. The very last step: _____________ .',
            '7. A life cycle with all four stages is called _____________ .',
            '8. When the caterpillar changes completely, it does this: _____________ .',
            '9. The correct order of steps: _____________ .',
            '10. The last stage of growth in a butterfly or frog: _____________ .',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Put the frog life cycle in order. Write 1-5. (5 items)',
            '___ a. The adult frog lays eggs in water.',
            '___ b. The tadpole grows legs.',
            '___ c. A tiny tadpole hatches from the egg.',
            '___ d. The froglet climbs out of the water.',
            '___ e. The tadpole becomes a young frog (froglet).',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L3 — Write the life cycle using sequence words (6 items)',
            'Write a sentence for each step of the butterfly life cycle:',
            '1. First, _________________________________________________________________ .',
            '2. Then, __________________________________________________________________ .',
            '3. Next, __________________________________________________________________ .',
            '4. After that, _____________________________________________________________ .',
            '5. Next, __________________________________________________________________ .',
            '6. Finally, ________________________________________________________________ .',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Correct the mistake (5 items)',
            '1. First, the caterpillar lays an egg. → ___________________________________',
            '2. A pupa becomes a caterpillar finally. → ___________________________________',
            '3. Then, the egg transforms into an adult butterfly immediately. → ___________________________________',
            '4. The sequence of a frog\'s life are: egg, tadpole, adult frog. → ___________________________________',
            '5. A life cycle are complete when the adult make eggs again. → ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write the complete butterfly life cycle in one sentence:',
            '   _______________________________________________________________________',
            '2. Write a sentence using "first ... then ... finally":',
            '   _______________________________________________________________________',
            '3. Write a sentence using "transforms into":',
            '   _______________________________________________________________________',
            '4. Write a sentence about why life cycles are continuous:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 30 ]',
        ],
    },
    42: {
        1: [
            '[O] L1 — Choose the correct word (10 items)',
            'Word box: [ evaporation / condensation / precipitation / vapor / water cycle / collection / runoff / groundwater / cloud / sunlight ]',
            '1. Water turning into gas and rising into the air is _____________ .',
            '2. Water vapor cooling and turning into tiny drops in the air is _____________ .',
            '3. Rain, snow, and hail falling from the sky is _____________ .',
            '4. Water in the form of an invisible gas is called _____________ .',
            '5. The continuous journey of water from sea to sky and back is the _____________ .',
            '6. Rain water gathering in rivers and lakes is called _____________ .',
            '7. When rain flows over the land into rivers, it is called _____________ .',
            '8. Water that soaks into the soil and collects underground is _____________ .',
            '9. Tiny water drops in the air that we can see form a _____________ .',
            '10. The energy from the sun that heats water is _____________ .',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — True (T) or False (F)? (6 items)',
            '1. Evaporation happens when sunlight heats water and turns it into vapor.  ___',
            '2. Condensation turns water vapor back into liquid water.  ___',
            '3. Precipitation only happens as rain, never as snow or hail.  ___',
            '4. The water cycle is a process that never stops.  ___',
            '5. Groundwater is found above the ground in rivers.  ___',
            '6. Sunlight gives the energy that starts the water cycle.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L3 — Put the water cycle steps in order. Write 1-5. (5 items)',
            '___ a. Water vapor rises and cools to form clouds (condensation).',
            '___ b. Rain or snow falls from the clouds (precipitation).',
            '___ c. Sunlight heats water in the ocean (evaporation begins).',
            '___ d. Water collects in rivers, lakes, and oceans (collection).',
            '___ e. Water turns into vapor and rises into the air (evaporation).',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L4 — Fill in the blank — Present Simple for processes (8 items)',
            '1. Sunlight _____________ (heat / heats) the water in the ocean.',
            '2. Water _____________ (evaporate / evaporates) and rises as vapor.',
            '3. The vapor _____________ (cool / cools) and forms tiny water drops.',
            '4. The drops _____________ (form / forms) clouds in the sky.',
            '5. Clouds _____________ (release / releases) rain or snow as precipitation.',
            '6. Water _____________ (flow / flows) down into rivers and lakes.',
            '7. Some water _____________ (soak / soaks) into the ground as groundwater.',
            '8. The water cycle _____________ (repeat / repeats) continuously.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence about evaporation using "sunlight":',
            '   _______________________________________________________________________',
            '2. Write a sentence about condensation using "forms clouds":',
            '   _______________________________________________________________________',
            '3. Write a sentence about precipitation using Present Simple:',
            '   _______________________________________________________________________',
            '4. Write a sentence about why the water cycle is continuous:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        2: [
            '[O] L1 — Match: water cycle word → definition (10 items)',
            '1. absorb → _____________',
            '2. release → _____________',
            '3. temperature → _____________',
            '4. sunlight → _____________',
            '5. cloud → _____________',
            '6. runoff → _____________',
            '7. groundwater → _____________',
            '8. continuous → _____________',
            '9. process → _____________',
            '10. collection → _____________',
            'Definitions: [ to soak up / to let go / how hot or cold something is / energy from the sun / tiny water drops in the sky / water flowing over land / water underground / never stopping / steps that happen one by one / water gathering in rivers ]',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Fill in the blank (8 items)',
            'Word box: [ absorb / release / temperature / sunlight / cloud / runoff / continuous / process ]',
            '1. Water _____________ s sunlight and gets hotter.',
            '2. When water gets hot, it _____________ s vapor into the air.',
            '3. The _____________ of the water determines how fast it evaporates.',
            '4. _____________ gives the energy needed to start evaporation.',
            '5. Condensation forms tiny drops that make up a _____________ .',
            '6. After rain, water flows over the land as _____________ .',
            '7. The water cycle is a _____________ process — it never stops.',
            '8. The water cycle is a natural _____________ with four main stages.',
            '[ Sub-total: ___ / 8 ]',
            '',
            '[O] L3 — True (T) or False (F)? (6 items)',
            '1. Water absorbs sunlight to start the process of evaporation.  ___',
            '2. Clouds release water as precipitation when they get too heavy.  ___',
            '3. Higher temperatures make evaporation happen more slowly.  ___',
            '4. The water cycle is continuous — it never stops.  ___',
            '5. Runoff happens when water soaks completely into the ground.  ___',
            '6. Groundwater can become a source of drinking water.  ___',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Complete the process description (5 items)',
            '1. Water absorbs sunlight; therefore, ________________________________________.',
            '2. When the temperature is high, ________________________________________.',
            '3. Clouds release precipitation because ________________________________________.',
            '4. The water cycle is continuous, which means ________________________________________.',
            '5. Runoff flows into rivers because ________________________________________.',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (4 items)',
            '1. Write a sentence using "absorbs":',
            '   _______________________________________________________________________',
            '2. Write a sentence using "releases":',
            '   _______________________________________________________________________',
            '3. Write a sentence about temperature and evaporation:',
            '   _______________________________________________________________________',
            '4. Write a sentence about the water cycle using "continuous":',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '[ PART 3 TOTAL: ___ / 33 ]',
        ],
        3: [
            '[O] L1 — Read the clue. Write the word (10 items)',
            'Word box: [ evaporation / condensation / precipitation / vapor / collection / repeat / stage / flow / process / continuous ]',
            '1. Water turns into gas and rises: _____________ .',
            '2. Gas cools and becomes tiny water drops: _____________ .',
            '3. Rain, snow, or hail falling from clouds: _____________ .',
            '4. Water in the form of an invisible gas: _____________ .',
            '5. Water gathering in rivers and lakes after rain: _____________ .',
            '6. The water cycle does this — it goes around and around: _____________ .',
            '7. One step in the water cycle: _____________ .',
            '8. Water does this when it moves from mountains to the sea: _____________ .',
            '9. Steps that happen one after another: _____________ .',
            '10. Always happening, never stopping: _____________ .',
            '[ Sub-total: ___ / 10 ]',
            '',
            '[O] L2 — Write the four stages of the water cycle in order (4 items)',
            '1. Stage 1: _______________________________________________',
            '2. Stage 2: _______________________________________________',
            '3. Stage 3: _______________________________________________',
            '4. Stage 4: _______________________________________________',
            '[ Sub-total: ___ / 4 ]',
            '',
            '[O] L3 — Write the water cycle story using sequence words (6 items)',
            '1. First, ________________________________________________________________ .',
            '2. Then, _________________________________________________________________ .',
            '3. Next, _________________________________________________________________ .',
            '4. After that, ____________________________________________________________ .',
            '5. Then, _________________________________________________________________ .',
            '6. Finally, ______________________________________________________________ .',
            '[ Sub-total: ___ / 6 ]',
            '',
            '[O] L4 — Correct the mistake (5 items)',
            '1. Water evaporates because it get colder. → ___________________________________',
            '2. Condensation happens when vapor get hotter. → ___________________________________',
            '3. Precipitation are rain or snow that falling from clouds. → ___________________________________',
            '4. The water cycle repeats continuous. → ___________________________________',
            '5. Water flows into the ocean because it is lightest than air. → ___________________________________',
            '[ Sub-total: ___ / 5 ]',
            '',
            '[O] L5 — Write your own sentences (5 items)',
            '1. Write a sentence about evaporation using Present Simple:',
            '   _______________________________________________________________________',
            '2. Write a sentence about condensation using Present Simple:',
            '   _______________________________________________________________________',
            '3. Write a sentence about precipitation using "falls":',
            '   _______________________________________________________________________',
            '4. Write a sentence using "the water cycle repeats":',
            '   _______________________________________________________________________',
            '5. Write a sentence about why the water cycle is important:',
            '   _______________________________________________________________________',
            '[ Sub-total: ___ / 5 ]',
            '[ PART 3 TOTAL: ___ / 30 ]',
        ],
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _find_part(parts, part_key):
    """Return (index, part_dict) for the part whose title starts with part_key."""
    for i, p in enumerate(parts):
        if p['title'].startswith(part_key):
            return i, p
    return -1, None

def _update_part_in_sessions(sessions_list, sess_num, part_key, new_content, new_title=None):
    """Update content (and optionally title) of a PART in a sessions list."""
    for sess in sessions_list:
        if sess.get('session') == sess_num:
            idx, part = _find_part(sess['parts'], part_key)
            if part is not None:
                part['content'] = new_content
                if new_title:
                    part['title'] = new_title
            break

def _update_part_all_views(data, sess_num, part_key, new_content, new_title=None):
    """Update PART in sessions, sessions_5, sessions_2."""
    for key in ('sessions', 'sessions_5', 'sessions_2'):
        if key in data and isinstance(data[key], list):
            _update_part_in_sessions(data[key], sess_num, part_key, new_content, new_title)

def load_week(week_num):
    path = LESSONS_DIRS[0] / ('W%d.json' % week_num)
    return json.loads(path.read_text(encoding='utf-8'))

def save_week(week_num, data):
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    for d in LESSONS_DIRS:
        path = d / ('W%d.json' % week_num)
        if path.exists():
            path.write_text(payload, encoding='utf-8')
    print('  saved W%d.json (%d chars)' % (week_num, len(payload)))

# ─────────────────────────────────────────────────────────────────────────────
# Main enrichment
# ─────────────────────────────────────────────────────────────────────────────
def enrich_week(week_num):
    print('── W%d ──────────────────────────────────────' % week_num)
    data = load_week(week_num)

    # 1. Vocab expansion
    old_count = len(data.get('vocab_tiers', []))
    data['vocab_tiers'] = VOCAB[week_num]
    print('  vocab: %d → %d words' % (old_count, len(data['vocab_tiers'])))

    # 2. PART 2 — numbered, split by tier per session
    for sess_num in [1, 2, 3]:
        new_content = build_part2_content(week_num, sess_num)
        new_title   = build_part2_title(week_num, sess_num)
        _update_part_all_views(data, sess_num, 'PART 2', new_content, new_title)
    print('  PART 2: rewritten (numbered, 7/6/5 words per session, sub-totals)')

    # 3. PART 3 — numbered L1-L5
    week_p3 = PART3.get(week_num, {})
    for sess_num in [1, 2, 3]:
        sess_p3 = week_p3.get(sess_num)
        if sess_p3:
            _update_part_all_views(data, sess_num, 'PART 3', sess_p3)
    print('  PART 3: rewritten (numbered L1-L5 per session)')

    # 4. Save
    save_week(week_num, data)
    print()

def main():
    weeks = list(range(37, 43))
    if len(sys.argv) > 1:
        arg = sys.argv[1]
        if '-' in arg:
            a, b = arg.split('-')
            weeks = list(range(int(a), int(b) + 1))
        else:
            weeks = [int(arg)]

    print('Enriching W%d-W%d directly...\n' % (weeks[0], weeks[-1]))
    for w in weeks:
        enrich_week(w)
    print('Done. Run validate_lesson_plan.py --all to check.')

if __name__ == '__main__':
    main()
