/**
 * Dynamic Roleplay System - Weekly Scenarios
 * 
 * Week 5 is the TEMPLATE. Other weeks will be dynamically generated by AI
 * based on their theme and vocabulary.
 */

export const ROLEPLAY_TEMPLATES = {
  5: [ // WEEK 5: HOUSE & ROOMS (Template for other weeks)
    {
      id: 'interior_designer',
      label_en: 'Room Designer',
      label_vi: 'Thiết kế phòng',
      emoji: '🎨',
      character: 'Interior Designer',
      character_vi: 'Nhà thiết kế nội thất',
      setting: 'Empty Room',
      setting_vi: 'Phòng trống',
      vocab_focus: ['bedroom', 'lamp', 'sofa', 'table', 'chair', 'beautiful', 'color'],
      opening_line: "Hello! I'm an interior designer. What room do you want to make beautiful?",
      opening_line_vi: "Xin chào! Tôi là nhà thiết kế nội thất. Bạn muốn làm đẹp phòng nào?",
      scenario_description: `You are a friendly interior designer helping a child design their dream room. Ask what furniture they need, what colors they like, and where to place items. Use vocabulary: ${['bedroom', 'lamp', 'sofa', 'table', 'chair'].join(', ')}.`
    },
    {
      id: 'house_tour_guide',
      label_en: 'House Tour',
      label_vi: 'Dẫn khách',
      emoji: '🚪',
      character: 'Tour Guide',
      character_vi: 'Hướng dẫn viên',
      setting: 'Beautiful House',
      setting_vi: 'Ngôi nhà đẹp',
      vocab_focus: ['bedroom', 'kitchen', 'bathroom', 'living room', 'door', 'window'],
      opening_line: "Welcome! Let me show you this beautiful house. Which room do you want to see first?",
      opening_line_vi: "Chào mừng! Để tôi cho bạn xem ngôi nhà đẹp này. Bạn muốn xem phòng nào trước?",
      scenario_description: `You are giving a tour of a beautiful house. Show different rooms, describe what's in each room, and answer questions. Use vocabulary: ${['bedroom', 'kitchen', 'bathroom', 'living room', 'door', 'window'].join(', ')}.`
    },
    {
      id: 'furniture_shop',
      label_en: 'Furniture Shop',
      label_vi: 'Cửa hàng đồ',
      emoji: '🛋️',
      character: 'Shop Owner',
      character_vi: 'Chủ cửa hàng',
      setting: 'Furniture Store',
      setting_vi: 'Cửa hàng nội thất',
      vocab_focus: ['sofa', 'table', 'chair', 'lamp', 'bed', 'buy', 'need', 'color'],
      opening_line: "Welcome to my furniture shop! What do you need for your house?",
      opening_line_vi: "Chào mừng đến cửa hàng nội thất! Bạn cần gì cho nhà?",
      scenario_description: `You own a furniture shop. Help customers choose furniture, describe items, ask what they need, and suggest good options. Use vocabulary: ${['sofa', 'table', 'chair', 'lamp', 'bed'].join(', ')}.`
    }
  ]
};

/**
 * Get roleplay scenarios for a specific week
 * If week not defined, AI will generate dynamically based on weekData
 */
export function getRoleplaysForWeek(weekId, weekData) {
  // If Week 5 template exists, use it
  if (ROLEPLAY_TEMPLATES[weekId]) {
    return ROLEPLAY_TEMPLATES[weekId];
  }
  
  // Otherwise, generate dynamic roleplays based on theme
  // AI will create appropriate scenarios using weekData
  const theme = weekData?.theme || 'General';
  const vocab = weekData?.target_vocab?.map(v => v.word) || [];
  
  // Return generic structure - AI will fill in details during conversation
  return [
    {
      id: `${theme.toLowerCase()}_scenario_1`,
      label_en: `${theme} Activity 1`,
      label_vi: `Hoạt động 1`,
      emoji: '🎭',
      character: 'Character',
      setting: theme,
      vocab_focus: vocab.slice(0, 7),
      opening_line: `Hello! Let's talk about ${theme}. What do you think?`,
      scenario_description: `Create an engaging roleplay scenario related to ${theme}. Use vocabulary: ${vocab.slice(0, 10).join(', ')}.`
    },
    {
      id: `${theme.toLowerCase()}_scenario_2`,
      label_en: `${theme} Activity 2`,
      label_vi: `Hoạt động 2`,
      emoji: '🎪',
      character: 'Helper',
      setting: theme,
      vocab_focus: vocab.slice(5, 12),
      opening_line: `Hi! I can help you with ${theme}. What would you like to do?`,
      scenario_description: `Create a fun roleplay about ${theme}. Use vocabulary: ${vocab.slice(5, 15).join(', ')}.`
    },
    {
      id: `${theme.toLowerCase()}_scenario_3`,
      label_en: `${theme} Activity 3`,
      label_vi: `Hoạt động 3`,
      emoji: '🎯',
      character: 'Guide',
      setting: theme,
      vocab_focus: vocab.slice(7, 14),
      opening_line: `Welcome! Let's explore ${theme} together!`,
      scenario_description: `Create an interactive roleplay about ${theme}. Use vocabulary: ${vocab.slice(7, 17).join(', ')}.`
    }
  ];
}

/**
 * CRITICAL: This data structure serves as a TEMPLATE for AI
 * When creating new weeks, AI should:
 * 1. Look at Week 5 structure
 * 2. Replace theme (House → School/Family/Toys/etc)
 * 3. Replace vocab_focus with new week's target_vocab
 * 4. Create contextually appropriate character/setting
 * 5. Maintain same JSON structure
 */
