/**
 * Game Adaptation System - Weekly Content
 * 
 * Week 5 is the TEMPLATE. Other weeks will be dynamically generated by AI
 * based on their vocabulary and theme.
 */

export const GAME_TEMPLATES = {
  5: { // WEEK 5: HOUSE & ROOMS (Template for other weeks)
    theme: 'House & Rooms',
    theme_vi: 'Ngôi nhà và các phòng',
    vocab: ['bedroom', 'kitchen', 'bathroom', 'living room', 'door', 'window', 'lamp', 'sofa', 'table', 'chair'],
    
    games: {
      // 🔗 WORD CHAIN
      word_chain: {
        name_en: 'Word Chain',
        name_vi: 'Nối từ',
        emoji: '🔗',
        starter_words: ['bedroom', 'kitchen', 'lamp', 'sofa'],
        instructions: `Let's play Word Chain with house words! I'll say a word, then you say a word that starts with the last letter of my word. Use words about houses and rooms!`,
        instructions_vi: 'Chơi Nối từ với từ vựng về nhà! Tôi nói từ, bạn nói từ bắt đầu bằng chữ cái cuối.',
        example: 'Nova: "BEDROOM" → Student: "MIRROR" → Nova: "ROOF"'
      },
      
      // ❓ 20 QUESTIONS
      twenty_questions: {
        name_en: '20 Questions',
        name_vi: 'Đoán vật',
        emoji: '❓',
        objects: ['bed', 'sofa', 'lamp', 'table', 'chair', 'mirror', 'rug', 'door', 'window', 'shelf'],
        instructions: `I'm thinking of something in a house. Ask me yes/no questions to guess what it is! It's one of these: bed, sofa, lamp, table, chair, mirror, rug, door, window, or shelf.`,
        instructions_vi: 'Tôi nghĩ đến một vật trong nhà. Hỏi câu hỏi yes/no để đoán!',
        hints: ['Is it in the bedroom?', 'Is it furniture?', 'Do you sit on it?', 'Does it give light?']
      },
      
      // 🧩 SENTENCE BUILDER
      sentence_builder: {
        name_en: 'Sentence Builder',
        name_vi: 'Xây câu',
        emoji: '🧩',
        patterns: [
          'There is a ... in the ...',
          'I ... in my ...',
          'The ... is in the ...'
        ],
        instructions: `Let's build sentences together! I'll start with one word, you add the next word. We'll make sentences about houses using patterns like "There is a lamp in my bedroom."`,
        instructions_vi: 'Xây câu cùng nhau! Tôi nói 1 từ, bạn thêm từ tiếp theo.',
        examples: [
          'There is a lamp in my bedroom.',
          'I sleep in my bedroom.',
          'The sofa is in the living room.'
        ]
      }
    }
  }
};

/**
 * Get game content for a specific week
 * If week not defined, AI will generate dynamically based on weekData
 */
export function getGameContentForWeek(weekId, weekData) {
  // If Week 5 template exists, use it
  if (GAME_TEMPLATES[weekId]) {
    return GAME_TEMPLATES[weekId];
  }
  
  // Otherwise, generate dynamic content from weekData
  // AI will use weekData.target_vocab and weekData.theme
  return {
    theme: weekData?.theme || 'English Practice',
    theme_vi: weekData?.theme_vi || 'Luyện tiếng Anh',
    vocab: weekData?.target_vocab?.map(v => v.word) || [],
    games: {
      word_chain: {
        name_en: 'Word Chain',
        name_vi: 'Nối từ',
        emoji: '🔗',
        // AI will pick starter words from vocab
        starter_words: weekData?.target_vocab?.slice(0, 4).map(v => v.word) || [],
        instructions: `Let's play Word Chain with words about ${weekData?.theme || 'this topic'}!`,
        instructions_vi: `Chơi Nối từ với từ vựng về ${weekData?.theme_vi || 'chủ đề này'}!`
      },
      twenty_questions: {
        name_en: '20 Questions',
        name_vi: 'Đoán vật',
        emoji: '❓',
        // AI will use vocabulary items as objects to guess
        objects: weekData?.target_vocab?.map(v => v.word) || [],
        instructions: `I'm thinking of something related to ${weekData?.theme || 'this topic'}. Ask yes/no questions!`,
        instructions_vi: `Tôi nghĩ đến thứ gì đó về ${weekData?.theme_vi || 'chủ đề này'}. Hỏi câu hỏi yes/no!`
      },
      sentence_builder: {
        name_en: 'Sentence Builder',
        name_vi: 'Xây câu',
        emoji: '🧩',
        // AI will extract patterns from weekData.target_grammar or generate based on vocab
        patterns: weekData?.target_grammar || ['I ... a ...', 'This is my ...', 'I like ...'],
        instructions: `Let's build sentences about ${weekData?.theme || 'this topic'}!`,
        instructions_vi: `Xây câu về ${weekData?.theme_vi || 'chủ đề này'}!`
      }
    }
  };
}

/**
 * Get list of available games (3 games)
 */
export const GAME_OPTIONS = [
  {
    id: 'word_chain',
    label_en: 'Word Chain',
    label_vi: 'Nối từ',
    emoji: '🔗',
    description: 'Chain words by last letter'
  },
  {
    id: 'twenty_questions',
    label_en: '20 Questions',
    label_vi: 'Đoán vật',
    emoji: '❓',
    description: 'Guess with yes/no questions'
  },
  {
    id: 'sentence_builder',
    label_en: 'Sentence Builder',
    label_vi: 'Xây câu',
    emoji: '🧩',
    description: 'Build sentences together'
  }
];
