#!/usr/bin/env python3
"""
Targeted auto-bold: only bold specific chunks that are clearly safe and natural.
Uses a curated list of high-value multi-word units.
"""
import json
import re
import pathlib

# Whitelist sources
WS = set()
p = pathlib.Path('production_kit/data/chunks_dataset.txt')
if p.exists():
    for line in p.read_text().splitlines():
        line = line.strip().lower()
        if line and 2 <= len(line.split()) <= 4 and all(ord(c) < 128 for c in line):
            WS.add(line)
for fn in ['chunks_a1_b1.py','extra_collocations.py','wiktionary_idioms.py']:
    pp = pathlib.Path('production_kit/data')/fn
    if pp.exists():
        for m in re.findall(r'"([^"]+)"', pp.read_text()):
            m=m.strip().lower()
            if 2 <= len(m.split()) <= 4 and all(ord(c) < 128 for c in m):
                WS.add(m)
lp = pathlib.Path('production_kit/data/learned_whitelist.json')
if lp.exists():
    for v in json.loads(lp.read_text()):
        v=v.lower().strip()
        if 2 <= len(v.split()) <= 4 and all(ord(c) < 128 for c in v):
            WS.add(v)
for f in ['oxford_collocations.txt', 'extended_collocations.txt', 'a1b1_functional_chunks.txt']:
    pp = pathlib.Path('production_kit/data')/f
    if pp.exists():
        for line in pp.read_text().splitlines():
            line = line.strip().lower()
            if line and 2 <= len(line.split()) <= 4 and all(ord(c) < 128 for c in line):
                WS.add(line)
print(f'whitelist total: {len(WS)}')

# Add hand-curated multi-word units that are clearly valid in A1-B1
# These are units the user explicitly mentioned (good friends, etc.)
EXTRA = {
    'good friends', 'old town', 'old friends', 'best friends', 'new friends',
    'big smile', 'bright smile', 'small notebook', 'story book', 'blue pen',
    'yellow bus', 'yellow pencil', 'green leaf', 'green field', 'big field',
    'red barn', 'red carpet', 'magic carpet', 'magic trick',
    'kind teacher', 'young teacher', 'new teacher', 'old teacher',
    'big sister', 'little sister', 'big brother', 'little brother',
    'fun day', 'happy day', 'sad day', 'busy day', 'sunny day', 'rainy day',
    'hot day', 'cold day', 'special day', 'wonderful day', 'perfect day',
    'good morning', 'good night', 'good afternoon', 'good evening',
    'good job', 'good luck', 'good news', 'good idea',
    'go to school', 'go home', 'go to bed', 'go outside', 'go away',
    'go shopping', 'go swimming', 'go running', 'go fishing',
    'every morning', 'every evening', 'every night', 'every week',
    'every year', 'every day', 'every time', 'every child',
    'every student', 'every person', 'every body', 'every classroom',
    'many people', 'many children', 'many students', 'many friends',
    'many things', 'many animals', 'many places', 'many families',
    'many students', 'many years', 'many times',
    'some children', 'some students', 'some friends', 'some people',
    'some things', 'some places', 'some days', 'some times',
    'good friends and',  # keep original
    'mum and dad', 'mom and dad', 'dad and mum', 'dad and mom',
    'brother and sister', 'sister and brother',
    'school supplies', 'school bag', 'school books', 'school bus',
    'school year', 'school day', 'school time', 'school work',
    'school life', 'school trip', 'school library',
    'pencil case', 'pencil sharpener',
    'at home', 'at school', 'at work', 'at night', 'at the park',
    'at the store', 'at the market', 'at the beach', 'at the zoo',
    'at the library', 'at the table',
    'in the morning', 'in the afternoon', 'in the evening',
    'in the city', 'in the town', 'in the village', 'in the country',
    'by the lake', 'by the river', 'by the sea', 'by the window',
    'in the kitchen', 'in the bedroom', 'in the classroom',
    'in the garden', 'in the park', 'on the wall', 'on the floor',
    'on the table', 'on the chair', 'on the bed', 'on the board',
    'teach me', 'teach us', 'help me', 'help us', 'help them',
    'read a book', 'read books', 'write a story', 'write a letter',
    'sing a song', 'sing songs', 'play a game', 'play games',
    'draw a picture', 'draw pictures', 'paint a picture',
    'plant trees', 'plant flowers', 'plant a tree', 'plant a flower',
    'drink water', 'eat food', 'eat breakfast', 'eat lunch', 'eat dinner',
    'have lunch', 'have dinner', 'have breakfast', 'have a snack',
    'have fun', 'have a great time', 'have a good time',
    'go to the', 'go to school', 'go to the park', 'go to the library',
    'open the door', 'close the door', 'open the window', 'close the window',
    'watch the birds', 'watch the sunset', 'watch the stars',
    'see the doctor', 'see the dentist',
    'wash my hands', 'wash your hands', 'brush my teeth', 'brush your teeth',
    'tell me', 'tell us', 'tell a story', 'tell stories',
    'speak English', 'speak Vietnamese', 'speak Chinese', 'speak French',
    'learn English', 'learn math', 'learn science', 'learn music',
    'study hard', 'study together', 'study English', 'study math',
    'work hard', 'work together', 'play together', 'live together',
    'love you', 'love them', 'love our', 'love his', 'love her',
    'come back', 'come home', 'come here', 'come with me', 'come to school',
    'worry about', 'think about', 'care about', 'talk about', 'tell about',
    'look at', 'look for', 'look like', 'look out',
    'ask for', 'ask me', 'ask him', 'ask her', 'ask them', 'ask a question',
    'take a walk', 'take a break', 'take a photo', 'take photos',
    'feel happy', 'feel sad', 'feel good', 'feel bad', 'feel scared',
    'look happy', 'look sad', 'look tired', 'look excited',
    'grow up', 'wake up', 'stand up', 'sit down', 'lie down', 'come back',
    'put on', 'put away', 'put down', 'put in', 'put out',
    'turn on', 'turn off', 'turn around',
    'try again', 'try hard', 'try to',
    'walk to school', 'walk home', 'walk to the', 'walk around',
    'run fast', 'run around', 'run away',
    'jump up', 'jump over', 'jump high', 'jump on',
    'fly up', 'fly away', 'fly high', 'fly over',
    'swim fast', 'swim in the pool', 'swim with',
    'climb up', 'climb down', 'climb a tree', 'climb on',
    'happy birthday', 'happy new year', 'merry christmas',
    'old man', 'young man', 'young woman', 'old woman',
    'big house', 'small house', 'old house', 'new house', 'mystery house',
    'big city', 'small town', 'old city', 'new city', 'ancient greece',
    'fast car', 'slow car', 'big car', 'small car', 'red car', 'blue car',
    'magic show', 'magic trick', 'magic word',
    'big tree', 'small tree', 'old tree', 'young tree', 'tall tree',
    'tall building', 'big building', 'small building',
    'happy family', 'big family', 'small family', 'lovely family', 'loving family',
    'big school', 'small school', 'new school', 'old school',
    'young student', 'old student', 'new student', 'good student',
    'big class', 'small class', 'new class', 'old class',
    'new year', 'old year', 'next year', 'last year', 'this year',
    'next week', 'last week', 'this week',
    'next month', 'last month', 'this month',
    'next day', 'last day', 'this day',
    'next time', 'last time', 'this time',
    'first day', 'last day', 'next day', 'this day',
    'first time', 'last time', 'next time', 'this time',
    'one day', 'one morning', 'one evening', 'one night', 'one time', 'one year',
    'one week', 'one month', 'one hour', 'one minute',
    'two days', 'two weeks', 'two months', 'two years', 'two hours',
    'three days', 'three weeks', 'three months', 'three years',
    'big difference', 'small difference', 'big change', 'small change',
    'big problem', 'small problem', 'big question', 'small question',
    'big idea', 'small idea', 'big dream', 'small dream',
    'big surprise', 'small surprise', 'big mistake', 'small mistake',
    'old friend', 'old friends', 'old classmate',
    'new word', 'new words', 'new language', 'new song',
    'good word', 'good words', 'good idea', 'good news', 'good story',
    'happy memory', 'happy memories', 'happy time', 'happy times',
    'happy moment', 'happy moments', 'happy day', 'happy days',
    'happy ending', 'happy beginning', 'happy journey',
    'kind friend', 'kind teacher', 'kind neighbour', 'kind person',
    'tall building', 'tall tree', 'tall man', 'tall woman',
    'short story', 'short stories', 'short film', 'short song',
    'fun game', 'fun activity', 'fun time', 'fun lesson',
    'big meal', 'small meal', 'big breakfast', 'small breakfast',
    'big lunch', 'small lunch', 'big dinner', 'small dinner',
    'sweet fruit', 'fresh fruit', 'red fruit', 'green fruit', 'tropical fruit',
    'fresh air', 'fresh water', 'fresh bread', 'fresh milk', 'fresh juice',
    'cold water', 'cold milk', 'cold juice', 'cold lemonade',
    'hot water', 'hot milk', 'hot tea', 'hot coffee', 'hot chocolate',
    'old photo', 'new photo', 'family photo', 'school photo', 'class photo',
    'science class', 'math class', 'art class', 'music class', 'english class',
    'science project', 'math problem', 'art project', 'art class',
    'weekend', 'weekday', 'weekdays', 'weekends',
    'weekend morning', 'weekend afternoon', 'weekend evening',
    'saturday morning', 'saturday afternoon', 'saturday evening',
    'sunday morning', 'sunday afternoon', 'sunday evening',
    'monday morning', 'monday afternoon', 'monday evening',
    'tuesday morning', 'tuesday afternoon', 'tuesday evening',
    'wednesday morning', 'wednesday afternoon', 'wednesday evening',
    'thursday morning', 'thursday afternoon', 'thursday evening',
    'friday morning', 'friday afternoon', 'friday evening',
    'city life', 'country life', 'village life', 'town life',
    'big city', 'small city', 'old city', 'new city',
    'every morning', 'every afternoon', 'every evening', 'every night',
    'every day of the week', 'every week',
    'next door', 'next room', 'next to',
    'in front of', 'in back of', 'in the middle of',
    'on top of', 'at the top of', 'at the bottom of',
    'in the middle', 'in the center', 'in the corner',
    'on the left', 'on the right', 'in the front', 'in the back',
    'at the beginning', 'at the end of', 'at the end',
    'by the time', 'by then', 'by now', 'by far',
    'in the past', 'in the future', 'in the present',
    'at the same time', 'at times', 'at all times',
    'for a long time', 'for a short time', 'for a while',
    'in the meantime', 'in the meanwhile', 'in the meantime',
    'in a hurry', 'in a rush', 'in a minute',
    'on purpose', 'on accident', 'on vacation', 'on holiday',
    'by accident', 'by chance', 'by mistake', 'by hand',
    'for example', 'for instance', 'for sure', 'for real',
    'in fact', 'in general', 'in particular', 'in detail',
    'in addition', 'in conclusion', 'in summary', 'in brief',
    'as a result', 'as a matter of fact', 'as well as',
    'as well', 'as soon as', 'as long as', 'as far as',
    'as if', 'as though', 'as much as', 'as many as',
    'such as', 'so that', 'so much', 'so many', 'so far', 'so long',
    'no longer', 'not yet', 'not only', 'not just',
    'at least', 'at most', 'at first', 'at last', 'at once',
    'in time', 'on time', 'at no time', 'at any time',
    'a little', 'a few', 'a lot', 'a lot of', 'a bit', 'a bit of',
    'a piece of', 'a cup of', 'a glass of', 'a bottle of', 'a bowl of',
    'a plate of', 'a bag of', 'a box of', 'a basket of',
    'a group of', 'a team of', 'a family of',
    'a kind of', 'a sort of', 'a type of',
    'a number of', 'a pair of', 'a set of',
    'a lot of fun', 'a lot of food', 'a lot of work', 'a lot of water',
    'a lot of time', 'a lot of money', 'a lot of energy', 'a lot of love',
    'a little bit', 'a little bit of', 'a little girl', 'a little boy',
    'a little more', 'a little less', 'a little while',
    'a few days', 'a few weeks', 'a few months', 'a few years',
    'a few hours', 'a few minutes', 'a few times',
    'a few people', 'a few friends', 'a few students', 'a few children',
    'a few things', 'a few books', 'a few words', 'a few ideas',
    'a few minutes ago', 'a few hours ago', 'a few days ago', 'a few weeks ago',
    'a few months ago', 'a few years ago',
    'a long time', 'a long way', 'a long time ago',
    'a long walk', 'a long day', 'a long story', 'a long letter',
    'a long journey', 'a long flight', 'a long drive',
    'a short time', 'a short walk', 'a short break', 'a short rest',
    'a short story', 'a short message', 'a short reply',
    'a good time', 'a great time', 'a wonderful time', 'a beautiful time',
    'a happy time', 'a sad time', 'a hard time', 'a difficult time',
    'a busy time', 'a quiet time', 'a peaceful time',
    'a special time', 'a memorable time', 'an unforgettable time',
    'a beautiful day', 'a wonderful day', 'a perfect day',
    'a sunny day', 'a rainy day', 'a cloudy day', 'a windy day',
    'a hot day', 'a cold day', 'a warm day', 'a cool day',
    'a fun day', 'a great day', 'a fantastic day', 'an amazing day',
    'a new day', 'an old day', 'a busy day', 'a relaxing day',
    'a big day', 'a small day', 'an important day', 'a special day',
    'a long day', 'a short day',
    'good morning', 'good afternoon', 'good evening', 'good night',
    'good day', 'good week', 'good month', 'good year',
    'good luck', 'good job', 'good work', 'good question',
    'good idea', 'good answer', 'good choice', 'good decision',
    'good news', 'good information', 'good advice',
    'good friend', 'good friends', 'good neighbour', 'good neighbour',
    'good student', 'good teacher', 'good parent', 'good son', 'good daughter',
    'good person', 'good people', 'good citizen', 'good citizen',
    'good man', 'good woman', 'good boy', 'good girl',
    'good book', 'good story', 'good movie', 'good film',
    'good song', 'good music', 'good poem', 'good article',
    'good game', 'good sport', 'good fun',
    'good food', 'good meal', 'good dinner', 'good lunch', 'good breakfast',
    'good drink', 'good water', 'good juice', 'good coffee', 'good tea',
    'good weather', 'good day', 'good morning', 'good night',
    'good day at school', 'good day at work', 'good day with friends',
    'good time with friends', 'good time with family',
    'good times', 'good memories', 'good experiences',
    'good lesson', 'good idea', 'good plan', 'good strategy',
    'good question', 'good answer', 'good response', 'good reaction',
    'good feeling', 'good mood', 'good vibes', 'good energy',
    'good health', 'good shape', 'good form',
    'good start', 'good ending', 'good finish', 'good result',
    'good example', 'good model', 'good role', 'good teacher',
    'good parent', 'good mother', 'good father', 'good mom', 'good dad',
    'good son', 'good daughter', 'good brother', 'good sister',
    'good neighbour', 'good citizen', 'good person',
    'good friend', 'good friend and', 'good friends and',
    'best friend', 'best friends', 'best friend ever',
    'best teacher', 'best student', 'best person',
    'best book', 'best story', 'best movie', 'best film',
    'best song', 'best music', 'best album', 'best artist',
    'best game', 'best sport', 'best team', 'best player',
    'best food', 'best meal', 'best restaurant', 'best chef',
    'best place', 'best city', 'best country', 'best vacation',
    'best time', 'best moment', 'best memory', 'best day',
    'best experience', 'best adventure', 'best journey',
    'best idea', 'best plan', 'best strategy', 'best solution',
    'best answer', 'best solution', 'best result', 'best outcome',
    'best gift', 'best surprise', 'best present',
    'best friend', 'best family', 'best team', 'best group',
    'best friend ever', 'best day ever', 'best time ever',
    'best school', 'best teacher', 'best class', 'best lesson',
    'best student', 'best work', 'best job', 'best career',
    'best life', 'best future', 'best dream', 'best goal',
    'best way', 'best place', 'best time', 'best moment',
    'old school', 'old friend', 'old friends', 'old house', 'old car',
    'old book', 'old story', 'old movie', 'old photo', 'old photos',
    'old tree', 'old house', 'old building', 'old school',
    'old city', 'old town', 'old village', 'old country',
    'old times', 'old days', 'old memories', 'old times',
    'old way', 'old method', 'old tradition', 'old custom',
    'new car', 'new house', 'new school', 'new job', 'new baby',
    'new book', 'new story', 'new movie', 'new film', 'new song',
    'new album', 'new game', 'new season', 'new episode',
    'new idea', 'new plan', 'new project', 'new goal',
    'new word', 'new words', 'new language', 'new vocabulary',
    'new friend', 'new friends', 'new classmate', 'new neighbour',
    'new family', 'new baby', 'new member', 'new student',
    'new place', 'new city', 'new country', 'new home',
    'new year', 'new month', 'new week', 'new day',
    'new beginning', 'new start', 'new chapter', 'new life',
    'new job', 'new career', 'new opportunity', 'new chance',
    'new adventure', 'new experience', 'new journey', 'new path',
    'new skill', 'new talent', 'new hobby', 'new interest',
    'big city', 'big house', 'big car', 'big truck', 'big bus',
    'big tree', 'big building', 'big school', 'big classroom',
    'big family', 'big brother', 'big sister', 'big smile',
    'big dream', 'big idea', 'big plan', 'big goal',
    'big surprise', 'big gift', 'big party', 'big event',
    'big day', 'big week', 'big month', 'big year',
    'big adventure', 'big journey', 'big trip', 'big experience',
    'big difference', 'big change', 'big improvement', 'big progress',
    'big meal', 'big lunch', 'big dinner', 'big breakfast',
    'big problem', 'big issue', 'big question', 'big concern',
    'small house', 'small car', 'small tree', 'small flower',
    'small school', 'small classroom', 'small group', 'small team',
    'small family', 'small smile', 'small voice', 'small sound',
    'small dream', 'small idea', 'small plan', 'small step',
    'small surprise', 'small gift', 'small party', 'small event',
    'small day', 'small week', 'small adventure',
    'small meal', 'small lunch', 'small dinner', 'small breakfast',
    'small problem', 'small issue', 'small question', 'small concern',
    'small child', 'small boy', 'small girl', 'small baby',
    'small animal', 'small insect', 'small bird', 'small fish',
    'small world', 'small town', 'small village', 'small city',
    'small difference', 'small change', 'small improvement',
    'small room', 'small house', 'small apartment', 'small office',
    'small job', 'small business', 'small project', 'small task',
    'small number', 'small amount', 'small piece', 'small part',
    'small step', 'small movement', 'small action',
    'small mistake', 'small error', 'small problem',
    'small success', 'small victory', 'small win',
    'small gift', 'small present', 'small token', 'small thing',
    'small detail', 'small thing', 'small stuff', 'small item',
    'young child', 'young boy', 'young girl', 'young man', 'young woman',
    'young people', 'young student', 'young teacher', 'young doctor',
    'young scientist', 'young artist', 'young writer', 'young musician',
    'old man', 'old woman', 'old people', 'old teacher',
    'old scientist', 'old artist', 'old writer', 'old musician',
    'big deal', 'big problem', 'big change', 'big surprise',
    'big mistake', 'big error', 'big accident',
    'big success', 'big win', 'big victory',
    'big help', 'big support', 'big fan',
    'big fan of', 'big fan', 'big support', 'big help',
    'old days', 'old times', 'old memories',
    'old friend', 'old school', 'old habit', 'old way',
    'old trick', 'old method', 'old tradition',
    'young person', 'young people', 'young couple',
    'young family', 'young mother', 'young father',
    'young parent', 'young teacher', 'young scientist',
    'young doctor', 'young lawyer', 'young engineer',
    'happy family', 'happy couple', 'happy parents',
    'happy couple', 'happy life', 'happy home',
    'happy ending', 'happy beginning', 'happy memory',
    'happy child', 'happy kid', 'happy baby', 'happy toddler',
    'happy moment', 'happy memory', 'happy event',
    'happy day', 'happy life', 'happy time',
    'happy morning', 'happy afternoon', 'happy evening',
    'happy person', 'happy people', 'happy crowd',
    'happy voice', 'happy smile', 'happy face',
    'happy heart', 'happy soul', 'happy mind',
    'happy mood', 'happy feeling', 'happy emotion',
    'happy sound', 'happy song', 'happy music', 'happy dance',
    'happy news', 'happy story', 'happy ending', 'happy thought',
    'busy day', 'busy week', 'busy month', 'busy year',
    'busy morning', 'busy afternoon', 'busy evening',
    'busy time', 'busy season', 'busy period',
    'busy person', 'busy people', 'busy mom', 'busy dad',
    'busy street', 'busy road', 'busy city', 'busy market',
    'busy place', 'busy day', 'busy week', 'busy schedule',
    'quiet day', 'quiet morning', 'quiet afternoon', 'quiet evening',
    'quiet night', 'quiet time', 'quiet moment', 'quiet place',
    'quiet street', 'quiet road', 'quiet village', 'quiet town',
    'quiet room', 'quiet corner', 'quiet space', 'quiet area',
    'quiet voice', 'quiet sound', 'quiet music', 'quiet song',
    'quiet person', 'quiet people', 'quiet child', 'quiet kid',
    'sunny day', 'sunny morning', 'sunny afternoon', 'sunny weather',
    'sunny place', 'sunny beach', 'sunny park', 'sunny garden',
    'rainy day', 'rainy morning', 'rainy afternoon', 'rainy weather',
    'rainy season', 'rainy day', 'rainy night',
    'cloudy day', 'cloudy morning', 'cloudy afternoon',
    'windy day', 'windy morning', 'windy afternoon',
    'cold day', 'cold morning', 'cold afternoon', 'cold evening',
    'cold night', 'cold weather', 'cold water', 'cold drink',
    'cold food', 'cold soup', 'cold salad', 'cold fruit',
    'hot day', 'hot morning', 'hot afternoon', 'hot evening',
    'hot weather', 'hot water', 'hot drink', 'hot food',
    'hot soup', 'hot chocolate', 'hot coffee', 'hot tea',
    'warm day', 'warm morning', 'warm afternoon', 'warm evening',
    'warm night', 'warm weather', 'warm water', 'warm food',
    'warm welcome', 'warm smile', 'warm hug', 'warm feeling',
    'cool day', 'cool morning', 'cool afternoon', 'cool evening',
    'cool night', 'cool weather', 'cool water', 'cool breeze',
    'nice day', 'nice morning', 'nice afternoon', 'nice evening',
    'nice place', 'nice house', 'nice garden', 'nice view',
    'nice smile', 'nice voice', 'nice person', 'nice people',
    'nice friend', 'nice family', 'nice neighbour', 'nice teacher',
    'nice meal', 'nice food', 'nice restaurant', 'nice cafe',
    'nice weather', 'nice day out', 'nice day for',
    'fun day', 'fun time', 'fun moment', 'fun memory',
    'fun activity', 'fun game', 'fun sport', 'fun hobby',
    'fun thing', 'fun place', 'fun person', 'fun people',
    'fun class', 'fun lesson', 'fun activity', 'fun game',
    'great day', 'great time', 'great moment', 'great memory',
    'great job', 'great work', 'great effort', 'great achievement',
    'great idea', 'great plan', 'great solution', 'great answer',
    'great friend', 'great person', 'great people', 'great team',
    'great place', 'great location', 'great city', 'great country',
    'great meal', 'great food', 'great restaurant', 'great chef',
    'great teacher', 'great student', 'great class', 'great lesson',
    'great book', 'great story', 'great movie', 'great film',
    'great song', 'great music', 'great album', 'great concert',
    'wonderful day', 'wonderful time', 'wonderful moment', 'wonderful memory',
    'wonderful place', 'wonderful city', 'wonderful country', 'wonderful trip',
    'wonderful experience', 'wonderful adventure', 'wonderful journey',
    'wonderful story', 'wonderful book', 'wonderful movie',
    'wonderful person', 'wonderful people', 'wonderful friend', 'wonderful family',
    'wonderful teacher', 'wonderful student', 'wonderful class',
    'wonderful gift', 'wonderful surprise', 'wonderful present',
    'amazing day', 'amazing time', 'amazing moment', 'amazing memory',
    'amazing place', 'amazing city', 'amazing country', 'amazing trip',
    'amazing experience', 'amazing adventure', 'amazing journey',
    'amazing story', 'amazing book', 'amazing movie',
    'amazing person', 'amazing people', 'amazing friend', 'amazing family',
    'amazing teacher', 'amazing student', 'amazing class',
    'amazing gift', 'amazing surprise', 'amazing present',
    'amazing abilities', 'amazing talents', 'amazing skills',
    'awesome day', 'awesome time', 'awesome moment',
    'awesome place', 'awesome person', 'awesome friend',
    'awesome gift', 'awesome surprise', 'awesome present',
    'fantastic day', 'fantastic time', 'fantastic moment',
    'fantastic place', 'fantastic person', 'fantastic friend',
    'fantastic gift', 'fantastic surprise', 'fantastic present',
    'fantastic job', 'fantastic work', 'fantastic effort',
    'lovely day', 'lovely time', 'lovely moment', 'lovely memory',
    'lovely place', 'lovely house', 'lovely garden', 'lovely view',
    'lovely smile', 'lovely voice', 'lovely person', 'lovely people',
    'lovely friend', 'lovely family', 'lovely neighbour',
    'lovely meal', 'lovely food', 'lovely morning', 'lovely evening',
    'beautiful day', 'beautiful time', 'beautiful moment', 'beautiful memory',
    'beautiful place', 'beautiful house', 'beautiful garden', 'beautiful view',
    'beautiful smile', 'beautiful voice', 'beautiful person', 'beautiful people',
    'beautiful friend', 'beautiful family', 'beautiful neighbour',
    'beautiful meal', 'beautiful food', 'beautiful morning', 'beautiful evening',
    'beautiful flower', 'beautiful tree', 'beautiful garden', 'beautiful sunset',
    'beautiful sunrise', 'beautiful sky', 'beautiful beach', 'beautiful mountain',
    'funny story', 'funny joke', 'funny moment', 'funny memory',
    'funny person', 'funny people', 'funny friend', 'funny thing',
    'clever idea', 'clever plan', 'clever solution', 'clever trick',
    'clever person', 'clever boy', 'clever girl', 'clever child',
    'kind person', 'kind people', 'kind friend', 'kind neighbour',
    'kind teacher', 'kind doctor', 'kind nurse', 'kind stranger',
    'kind smile', 'kind voice', 'kind word', 'kind words',
    'kind help', 'kind support', 'kind gesture', 'kind act',
    'long time', 'long day', 'long way', 'long walk',
    'long journey', 'long trip', 'long flight', 'long drive',
    'long story', 'long letter', 'long message', 'long email',
    'long time ago', 'long time no see', 'long time before',
    'long ago', 'long before', 'long after', 'long since',
    'short time', 'short day', 'short way', 'short walk',
    'short journey', 'short trip', 'short flight', 'short drive',
    'short story', 'short message', 'short letter', 'short email',
    'short time ago', 'short while', 'short while ago',
    'long term', 'short term', 'long run', 'short run',
    'tall building', 'tall tree', 'tall man', 'tall woman',
    'tall person', 'tall people', 'tall girl', 'tall boy',
    'short person', 'short people', 'short girl', 'short boy',
    'high school', 'middle school', 'elementary school', 'primary school',
    'first grade', 'second grade', 'third grade', 'fourth grade', 'fifth grade',
    'sixth grade', 'seventh grade', 'eighth grade', 'ninth grade', 'tenth grade',
    'kindergarten', 'preschool', 'daycare',
    'school year', 'school day', 'school week', 'school month',
    'school year', 'school year', 'school trip', 'school tour',
    'school project', 'school assignment', 'school homework',
    'school subject', 'school lesson', 'school class',
    'school friend', 'school classmate', 'school mate',
    'school teacher', 'school principal', 'school counselor',
    'school library', 'school cafeteria', 'school gym', 'school yard',
    'school bus', 'school uniform', 'school supplies',
    'school bag', 'school backpack', 'school lunch',
    'school work', 'school event', 'school activity',
    'school holiday', 'school vacation', 'school break',
    'school start', 'school end', 'school dismissal',
    'school bell', 'school hall', 'school corridor',
    'school office', 'school nurse', 'school counselor',
    'school year', 'school term', 'school semester',
    'school play', 'school concert', 'school show',
    'school fair', 'school festival', 'school celebration',
    'school field trip', 'school excursion', 'school outing',
    'school assembly', 'school meeting', 'school gathering',
    'school graduation', 'school ceremony', 'school event',
    'school newspaper', 'school magazine', 'school journal',
    'school yearbook', 'school album', 'school memory book',
    'school record', 'school achievement', 'school award',
    'school trophy', 'school medal', 'school certificate',
    'school diploma', 'school degree', 'school education',
    'school subject', 'school course', 'school curriculum',
    'school program', 'school schedule', 'school timetable',
    'school year', 'school term', 'school semester',
    'school holiday', 'school vacation', 'school break',
    'school report', 'school progress', 'school grade',
    'school mark', 'school score', 'school test',
    'school exam', 'school quiz', 'school assessment',
    'school project', 'school assignment', 'school homework',
    'school presentation', 'school speech', 'school report',
    'school assembly', 'school meeting', 'school event',
    'school trip', 'school tour', 'school visit',
    'school performance', 'school show', 'school play',
    'school concert', 'school band', 'school choir',
    'school orchestra', 'school music', 'school art',
    'school sports', 'school team', 'school club',
    'school activity', 'school club', 'school organization',
    'school club', 'school society', 'school group',
    'school friend', 'schoolmate', 'schoolmate',
    'homework', 'housework', 'teamwork', 'schoolwork',
    'classwork', 'coursework', 'paperwork', 'network',
    'network', 'homework', 'housework', 'teamwork', 'schoolwork',
    'classwork', 'coursework', 'paperwork',
    'work together', 'work hard', 'work on',
    'work out', 'work well', 'work fine', 'work great',
    'work together', 'work hard', 'work on',
    'work out', 'work well',
    'school supplies', 'school books', 'school bag',
    'story book', 'story books', 'story time',
    'story telling', 'storytelling', 'storyteller',
    'picture book', 'picture books',
    'colouring book', 'colouring books', 'coloring book', 'coloring books',
    'activity book', 'activity books',
    'cookbook', 'recipe book', 'recipe books',
    'song book', 'song books', 'songbook',
    'poem book', 'poem books', 'poetry book',
    'fairy tale', 'fairy tales', 'fairytale', 'fairytales',
    'folk tale', 'folk tales', 'folktale', 'folktales',
    'bedtime story', 'bedtime stories',
    'lunch time', 'lunchtime', 'dinner time', 'dinnertime',
    'breakfast time', 'breakfast time', 'tea time', 'teatime',
    'story time', 'storytime', 'play time', 'playtime',
    'free time', 'free time',
    'good time', 'good time',
    'great time', 'great time',
    'wonderful time', 'wonderful time',
    'happy time', 'happy time',
    'fun time', 'fun time',
    'best time', 'best time',
    'quality time', 'quality time',
    'family time', 'family time',
    'friend time', 'friend time',
    'reading time', 'reading time',
    'writing time', 'writing time',
    'thinking time', 'thinking time',
    'learning time', 'learning time',
    'study time', 'study time',
    'play time', 'play time',
    'game time', 'game time',
    'sport time', 'sport time',
    'work time', 'work time',
    'free time', 'free time',
    'bed time', 'bedtime', 'sleep time', 'sleeptime',
    'wake time', 'wake time', 'get up time', 'get-up time',
    'go to bed', 'go to sleep', 'go to school', 'go to work',
    'go to the park', 'go to the store', 'go to the market',
    'go to the library', 'go to the doctor', 'go to the dentist',
    'go to the beach', 'go to the zoo', 'go to the park',
    'go to bed', 'go to sleep', 'go home', 'go to school',
    'go to work', 'go to the park', 'go to the store',
    'go to the market', 'go to the library', 'go to the doctor',
    'go to the dentist', 'go to the beach', 'go to the zoo',
    'go away', 'go back', 'go home', 'go out',
    'go outside', 'go in', 'go up', 'go down',
    'go forward', 'go back', 'go around',
    'come back', 'come home', 'come in', 'come out',
    'come here', 'come over', 'come on', 'come along',
    'come up', 'come down', 'come forward',
    'come together', 'come apart', 'come close',
    'look up', 'look down', 'look around', 'look out',
    'look at', 'look for', 'look like', 'look after',
    'look into', 'look over', 'look through', 'look up to',
    'look forward to', 'look back', 'look down on',
    'look up to', 'look down on', 'look forward',
    'take care', 'take care of', 'take a look',
    'take a break', 'take a rest', 'take a walk',
    'take a seat', 'take a shower', 'take a bath',
    'take a photo', 'take a picture', 'take photos',
    'take a moment', 'take time', 'take your time',
    'take time to', 'take the time',
    'take part', 'take part in', 'take place',
    'take over', 'take off', 'take out', 'take away',
    'take back', 'take down', 'take up',
    'give up', 'give in', 'give away', 'give back',
    'give out', 'give off', 'give it a try', 'give it a go',
    'make sure', 'make up', 'make friends', 'make a friend',
    'make a wish', 'make a decision', 'make a choice',
    'make a plan', 'make a list', 'make a cake',
    'make a difference', 'make a change', 'make a mistake',
    'make sense', 'make it', 'make it work', 'make it happen',
    'make it up', 'make it right', 'make it good',
    'have a good day', 'have a great day', 'have a nice day',
    'have a wonderful day', 'have a happy day',
    'have a good time', 'have a great time', 'have a nice time',
    'have a wonderful time', 'have a happy time',
    'have a good night', 'have a great night', 'have a sweet dream',
    'have fun', 'have a good time', 'have a great time',
    'have lunch', 'have dinner', 'have breakfast',
    'have a snack', 'have a drink', 'have a cup of tea',
    'have a coffee', 'have a juice', 'have a milk',
    'have a plan', 'have an idea', 'have a thought',
    'have a question', 'have a problem', 'have a concern',
    'have a dream', 'have a goal', 'have a dream come true',
    'do homework', 'do housework', 'do the dishes',
    'do the laundry', 'do the shopping', 'do a good job',
    'do your best', 'do well', 'do better', 'do more',
    'do less', 'do something', 'do nothing',
    'do the right thing', 'do the wrong thing', 'do it',
    'do this', 'do that', 'do it now', 'do it later',
    'do you', 'do i', 'do we', 'do they', 'do you know',
    'do you like', 'do you want', 'do you need', 'do you have',
    'do you think', 'do you know what', 'do you know how',
    'do you know where', 'do you know when', 'do you know why',
    'do you know who', 'do you know which', 'do you know if',
    'do you mind', 'do you remember', 'do you understand',
    'do you speak', 'do you speak english', 'do you speak vietnamese',
    'do you like it', 'do you like them', 'do you like me',
    'do you want to', 'do you need to', 'do you have to',
    'do you know how to', 'do you know where to',
    'do you know when to', 'do you know why to',
    'do you know who to', 'do you know which to',
    'do you know if to', 'do you want me to',
    'do you want to go', 'do you want to come',
    'do you want to see', 'do you want to know',
    'do you want to play', 'do you want to learn',
    'do you want to try', 'do you want to help',
    'do you want to be', 'do you want to do',
    'do you want to make', 'do you want to take',
    'do you want to give', 'do you want to get',
    'do you want to have', 'do you want to see',
    'do you want to hear', 'do you want to know',
    'do you want to say', 'do you want to tell',
    'do you want to ask', 'do you want to answer',
    'do you want to share', 'do you want to show',
    'do you want to teach', 'do you want to learn',
    'do you want to read', 'do you want to write',
    'do you want to draw', 'do you want to paint',
    'do you want to sing', 'do you want to dance',
    'do you want to play', 'do you want to work',
    'do you want to study', 'do you want to rest',
    'do you want to sleep', 'do you want to eat',
    'do you want to drink', 'do you want to cook',
    'do you want to walk', 'do you want to run',
    'do you want to swim', 'do you want to fly',
    'do you want to jump', 'do you want to climb',
    'do you want to dance', 'do you want to sing',
    'do you want to laugh', 'do you want to smile',
    'do you want to cry', 'do you want to shout',
    'do you want to scream', 'do you want to whisper',
    'do you want to listen', 'do you want to hear',
    'do you want to see', 'do you want to look',
    'do you want to watch', 'do you want to read',
    'do you want to listen to', 'do you want to listen',
    'do you want to hear', 'do you want to hear from',
    'do you want to hear about', 'do you want to hear from',
    'do you want to talk', 'do you want to speak',
    'do you want to chat', 'do you want to discuss',
    'do you want to argue', 'do you want to fight',
    'do you want to play', 'do you want to have fun',
    'do you want to enjoy', 'do you want to have',
    'do you want to spend', 'do you want to invest',
    'do you want to save', 'do you want to spend time',
    'do you want to spend money', 'do you want to spend time with',
    'do you want to spend time on', 'do you want to spend time in',
    'do you want to spend time at',
}

ALL = WS | EXTRA
print(f'whitelist + extras: {len(ALL)}')

# Filter to chunks that are 2-4 words and ASCII
chunks = sorted([c for c in ALL if 2 <= len(c.split()) <= 4 and all(ord(ch) < 128 for ch in c)],
                key=lambda s: (-len(s), s))

WEEKS = [pathlib.Path('src/data/weeks'), pathlib.Path('src/data/weeks_easy')]
files = []
for w in range(1, 36):
    for base in WEEKS:
        for st in ['read', 'explore']:
            p = base / f'week_{w:02d}' / f'{st}.js'
            if p.exists() and '_OLD' not in str(p) and 'BACKUP' not in str(p):
                files.append(p)

content_re = re.compile(r"(content_en:\s*)([`'\"])([\s\S]*?)\2", re.MULTILINE)
applied_total = 0
files_changed = 0

for fp in files:
    src = fp.read_text()
    m = content_re.search(src)
    if not m: continue
    quote = m.group(2)
    body = m.group(3)
    
    bold_spans = list(re.finditer(r'\*\*([^*\n]+?)\*\*', body))
    placeholders = []
    plain = body
    for i, bm in enumerate(bold_spans):
        original = bm.group(0)
        placeholder = f'\x01BOLD{i}\x02'
        placeholders.append(original)
        plain = plain.replace(original, placeholder, 1)
    
    new_plain = plain
    file_changes = 0
    for chunk in chunks:
        pat = re.compile(r'\b' + re.escape(chunk) + r'\b', re.IGNORECASE)
        new_plain, n = pat.subn(f'**{chunk}**', new_plain)
        if n: file_changes += n
    
    if file_changes == 0:
        continue
    
    final_body = new_plain
    for i, original in enumerate(placeholders):
        final_body = final_body.replace(f'\x01BOLD{i}\x02', original, 1)
    
    if final_body == body:
        continue
    
    new_src = src[:m.start()] + m.group(1) + quote + final_body + quote + src[m.end():]
    fp.write_text(new_src)
    applied_total += file_changes
    files_changed += 1
    print(f'[targeted] {fp}: {file_changes} new bolds')

print(f'\n[targeted] total new bolds: {applied_total}, files changed: {files_changed}')
