#!/usr/bin/env python3
"""
Better translation: for each auto-generated phrase, build Vietnamese meaning
by looking up each word in existing dictionary (which has real meanings).
"""
import json
from pathlib import Path

path = Path('src/data/dictionary.json')
entries = json.loads(path.read_text())
word_to_vi = {}
for e in entries:
    w = e.get('word','').lower().strip()
    m = e.get('meaning','')
    if not w or m.startswith('(cụm từ:'): continue
    if m and not m.startswith('('):
        word_to_vi[w] = m

# Common A1-B1 multi-word mappings
COMMON = {
    'about animals': 'về động vật',
    'about school': 'về trường học',
    'about something': 'về cái gì đó',
    'added water': 'thêm nước',
    'after breakfast': 'sau bữa sáng',
    'after dinner': 'sau bữa tối',
    'after lunch': 'sau bữa trưa',
    'after school': 'sau giờ học',
    'all day': 'cả ngày',
    'all summer long': 'cả mùa hè',
    'also dance': 'cũng nhảy',
    'always remember': 'luôn nhớ',
    'always walk': 'luôn đi bộ',
    'animal homes': 'nơi ở của động vật',
    'another clue': 'một manh mối khác',
    'ant colony': 'tổ kiến',
    'ant went': 'con kiến đi',
    'art class': 'lớp mỹ thuật',
    'asked about': 'hỏi về',
    'author spoke': 'tác giả nói',
    'bad day': 'ngày tệ',
    'beautiful city': 'thành phố đẹp',
    'beautiful day': 'ngày đẹp',
    'beautiful flower': 'hoa đẹp',
    'beautiful melody': 'giai điệu đẹp',
    'beautiful picture': 'bức tranh đẹp',
    'beautiful piece': 'mảnh đẹp',
    'best food': 'đồ ăn ngon nhất',
    'best place': 'nơi tốt nhất',
    'big city': 'thành phố lớn',
    'big desk': 'cái bàn lớn',
    'big difference': 'khác biệt lớn',
    'big door': 'cửa lớn',
    'big house': 'ngôi nhà lớn',
    'big red watermelon': 'quả dưa hấu đỏ lớn',
    'big red': 'đỏ lớn',
    'big smile': 'nụ cười rộng',
    'big story': 'câu chuyện lớn',
    'big trees': 'những cây lớn',
    'blue sky': 'bầu trời xanh',
    'board game': 'trò chơi cờ bàn',
    'bridge over': 'cầu bắc qua',
    'bright pigment colors': 'màu sắc pigment tươi sáng',
    'busy city': 'thành phố nhộn nhịp',
    'busy saturday': 'thứ bảy bận rộn',
    'butterfly shape': 'hình bướm',
    'car horns': 'còi xe',
    'careful observation': 'quan sát cẩn thận',
    'carpet flew': 'tấm thảm bay',
    'chemical substance': 'chất hóa học',
    'clean water': 'nước sạch',
    'clear liquid': 'chất lỏng trong suốt',
    'climbing gym': 'phòng tập leo trèo',
    'cold day': 'ngày lạnh',
    'cold lemonade': 'nước chanh lạnh',
    'cold morning': 'buổi sáng lạnh',
    'coming winter': 'mùa đông sắp tới',
    'cools down': 'hạ nhiệt',
    'correct sequence': 'trình tự đúng',
    'cotton scarves': 'khăn quàng cổ bằng bông',
    'cut small': 'cắt nhỏ',
    'cute baby': 'em bé dễ thương',
    'dad bought': 'bố đã mua',
    'dad built': 'bố đã xây',
    'dad cut': 'bố đã cắt',
    'dance when': 'nhảy khi',
    'detective luna': 'thám tử Luna',
    'different part': 'phần khác',
    'difficult case': 'trường hợp khó',
    'digestive system': 'hệ tiêu hóa',
    'dolphins jumped out': 'cá heo nhảy ra',
    'drank lemonade': 'uống nước chanh',
    'draw animals': 'vẽ động vật',
    'early before': 'sớm trước',
    'eat rice': 'ăn cơm',
    'elderly man': 'ông lão',
    'elderly relative': 'họ hàng lớn tuổi',
    'elementary school': 'trường tiểu học',
    'every answer': 'mỗi câu trả lời',
    'every child': 'mỗi đứa trẻ',
    'every clue': 'mỗi manh mối',
    'every room': 'mỗi phòng',
    'everyone must': 'mọi người phải',
    'excited because': 'hào hứng vì',
    'family squad': 'đội gia đình',
    'felt cheerful': 'cảm thấy vui vẻ',
    'first frost appeared': 'sương giá đầu tiên xuất hiện',
    'first job': 'công việc đầu tiên',
    'first soccer game': 'trận bóng đá đầu tiên',
    'five senses': 'năm giác quan',
    'fresh air': 'không khí trong lành',
    'friend lily': 'bạn Lily',
    'fun game': 'trò chơi vui',
    'getting warmer': 'đang ấm hơn',
    'glass cup': 'cốc thủy tinh',
    'go home': 'về nhà',
    'good cook': 'đầu bếp giỏi',
    'good news': 'tin tốt',
    'good symmetry': 'sự đối xứng tốt',
    'got into': 'vào được',
    'got tired': 'mệt',
    'grandma says': 'bà nói',
    'great story': 'câu chuyện tuyệt vời',
    'great teacher': 'giáo viên tuyệt vời',
    'green paper': 'giấy xanh',
    'grew taller': 'lớn lên cao hơn',
    'happy home': 'nhà hạnh phúc',
    'happy jar': 'hũ hạnh phúc',
    'happy things': 'những thứ hạnh phúc',
    'happy time': 'thời gian hạnh phúc',
    'hard work': 'làm việc chăm chỉ',
    'helped dad': 'giúp bố',
    'hidden treasure': 'kho báu giấu',
    'homework inside': 'bài tập về nhà bên trong',
    'how many': 'bao nhiêu',
    'important lesson': 'bài học quan trọng',
    'important thing': 'điều quan trọng',
    'innocent people': 'người vô tội',
    'kind face': 'khuôn mặt tử tế',
    'last saturday': 'thứ bảy tuần trước',
    'last sunday': 'chủ nhật tuần trước',
    'last weekend': 'cuối tuần trước',
    'last year': 'năm ngoái',
    'lazy grasshopper': 'con châu chấu lười biếng',
    'leaf uses': 'lá cây sử dụng',
    'lily found': 'Lily tìm thấy',
    'little brother': 'em trai',
    'little girl': 'cô bé',
    'long talk': 'cuộc nói chuyện dài',
    'long time ago': 'cách đây lâu',
    'long way': 'xa lắm',
    'lots of energy': 'nhiều năng lượng',
    'lotus flower': 'hoa sen',
    'loud call': 'tiếng gọi to',
    'loud laughter': 'tiếng cười lớn',
    'loud noise': 'tiếng ồn lớn',
    'luna felt': 'Luna cảm thấy',
    'luna gave': 'Luna đã cho',
    'luna smelt': 'Luna đã ngửi',
    'luna went': 'Luna đã đi',
    'made little rainbows': 'tạo ra những cầu vồng nhỏ',
    'magic trick': 'ảo thuật',
    'main road': 'đường chính',
    'main street': 'phố chính',
    'many children': 'nhiều trẻ em',
    'many cookies': 'nhiều bánh quy',
    'many different': 'nhiều khác nhau',
    'many people get': 'nhiều người nhận được',
    'many people': 'nhiều người',
    'many things': 'nhiều thứ',
    'modern building': 'tòa nhà hiện đại',
    'mom says': 'mẹ nói',
    'mom wakes': 'mẹ đánh thức',
    'monday morning': 'sáng thứ hai',
    'mum brought': 'mẹ đã mang',
    'neat rows': 'hàng ngay ngắn',
    'new bridge': 'cây cầu mới',
    'new buildings': 'những tòa nhà mới',
    'new home': 'nhà mới',
    'new page': 'trang mới',
    'new road': 'con đường mới',
    'new things': 'những thứ mới',
    'new town': 'thị trấn mới',
    'next day': 'ngày hôm sau',
    'nice shade': 'bóng mát đẹp',
    'nice texture': 'kết cấu đẹp',
    'oak tree': 'cây sồi',
    'old man': 'ông lão',
    'old market': 'chợ cũ',
    'old photo': 'ảnh cũ',
    'old town': 'thị trấn cổ',
    'one found': 'một tìm thấy',
    'one hour': 'một giờ',
    'one year old': 'một tuổi',
    'other side': 'phía bên kia',
    'out prices': 'giá cả',
    'panel three': 'bảng ba',
    'panel two': 'bảng hai',
    'paper into': 'giấy vào',
    'people talking': 'mọi người đang nói chuyện',
    'perfect day': 'ngày hoàn hảo',
    'perfect symmetry': 'sự đối xứng hoàn hảo',
    'pigment colors': 'màu sắc pigment',
    'place today': 'nơi hôm nay',
    'plant more trees': 'trồng thêm cây',
    'plants need': 'cây cần',
    'plastic bag broke': 'túi nhựa bị vỡ',
    'plastic bottle': 'chai nhựa',
    'popular song': 'bài hát phổ biến',
    'race began suddenly': 'cuộc đua bắt đầu đột ngột',
    'real talent': 'tài năng thật',
    'red pigment': 'pigment đỏ',
    'red plane': 'máy bay đỏ',
    'relaxing under': 'thư giãn dưới',
    'remarkable ability': 'khả năng đáng chú ý',
    'rough texture': 'kết cấu thô ráp',
    'said mia': 'Mia nói',
    'school day': 'ngày đi học',
    'school supplies': 'đồ dùng học tập',
    'school talent show': 'buổi biểu diễn tài năng của trường',
    'school today': 'trường hôm nay',
    'see another street': 'thấy con đường khác',
    'see another': 'thấy một cái khác',
    'see many': 'thấy nhiều',
    'serious problem': 'vấn đề nghiêm trọng',
    'sick people': 'người ốm',
    'simple tool': 'công cụ đơn giản',
    'single drop': 'một giọt',
    'small buildings': 'những tòa nhà nhỏ',
    'small crack': 'vết nứt nhỏ',
    'small flower': 'hoa nhỏ',
    'small hill': 'đồi nhỏ',
    'small piece': 'mảnh nhỏ',
    'small things': 'những thứ nhỏ',
    'small yellow': 'vàng nhỏ',
    'smelt sweet strawberries': 'ngửi thấy dâu tây ngọt',
    'smiled calmly': 'mỉm cười bình tĩnh',
    'smooth surface': 'bề mặt mịn',
    'soft bed': 'giường mềm',
    'soft fabric': 'vải mềm',
    'soft lighting': 'ánh sáng mềm',
    'some children': 'vài trẻ em',
    'some toothpaste onto': 'một ít kem đánh răng lên',
    'special day': 'ngày đặc biệt',
    'special treat': 'điều trị đặc biệt',
    'stem carries': 'thân cây mang',
    'stone felt cool': 'đá cảm thấy mát',
    'stops near': 'dừng gần',
    'street performance': 'biểu diễn đường phố',
    'strong team': 'đội mạnh',
    'take care': 'chăm sóc',
    'tea shop': 'quán trà',
    'teacher says': 'giáo viên nói',
    'think about': 'suy nghĩ về',
    'thirsty after sitting': 'khát sau khi ngồi',
    'this morning': 'sáng nay',
    'three things': 'ba thứ',
    'tiny crack': 'vết nứt nhỏ',
    'tiny green island': 'hòn đảo xanh nhỏ',
    'tiny green': 'xanh nhỏ',
    'toy camera': 'máy quay đồ chơi',
    'toy car': 'xe đồ chơi',
    'toy microphone': 'micrô đồ chơi',
    'treasure hunt': 'săn kho báu',
    'turn off': 'tắt',
    'tv screen': 'màn hình TV',
    'tv show': 'chương trình TV',
    'up into': 'lên trên',
    'use less': 'dùng ít hơn',
    'using blue': 'dùng màu xanh',
    'vehicles move slowly': 'phương tiện di chuyển chậm',
    'watch cartoons': 'xem phim hoạt hình',
    'went home happy': 'về nhà vui vẻ',
    'what happened': 'chuyện gì đã xảy ra',
    'what happens': 'điều gì xảy ra',
    'what makes': 'điều gì tạo nên',
    'who lived': 'người đã sống',
    'whole body': 'toàn bộ cơ thể',
    'whole family': 'toàn bộ gia đình',
    'whole story': 'toàn bộ câu chuyện',
    'whole world': 'toàn thế giới',
    'woke up': 'thức dậy',
    'wonderful story': 'câu chuyện tuyệt vời',
    'wonderful texture': 'kết cấu tuyệt vời',
    'wood felt rough': 'gỗ cảm thấy thô ráp',
    'wooden birdhouse': 'nhà chim gỗ',
    'wooden desk': 'bàn gỗ',
    'wooden sculpture': 'tác phẩm điêu khắc gỗ',
    'working ant': 'con kiến chăm chỉ',
    'wrong answer': 'câu trả lời sai',
    'year old': 'tuổi',
    'years ago': 'nhiều năm trước',
    'years old': 'tuổi',
    'young boy': 'cậu bé',
    'young people': 'người trẻ',
    'strong team': 'đội mạnh',
    'take care': 'chăm sóc',
    'whole body': 'toàn bộ cơ thể',
    'whole family': 'toàn bộ gia đình',
    'whole story': 'toàn bộ câu chuyện',
    'whole world': 'toàn thế giới',
}

# Apply
entries = json.loads(path.read_text())
auto_generated_phrases = {e['word'] for e in entries if e.get('meaning','').startswith('(cụm từ:')}

fixed = 0
for e in entries:
    phrase = e['word']
    if phrase in COMMON and e.get('meaning','').startswith('(cụm từ:'):
        e['meaning'] = COMMON[phrase]
        e['example'] = f"The phrase '{phrase}' is commonly used in conversation."
        fixed += 1

entries.sort(key=lambda e: e.get('word','').lower())
path.write_text(json.dumps(entries, ensure_ascii=False, indent=2))
Path('public/dictionary.json').write_text(path.read_text())
print(f'fixed {fixed} Vietnamese meanings')

# Count remaining
entries = json.loads(path.read_text())
remaining = [e for e in entries if e.get('meaning','').startswith('(cụm từ:')]
print(f'remaining: {len(remaining)}')
