#!/usr/bin/env python3
"""
For each auto-generated entry "X Y Z" with meaning "(cụm từ: X Y Z)",
build a better Vietnamese translation by:
1. Splitting the phrase into words
2. Looking up each word in the existing dict for its Vietnamese
3. Concatenating the Vietnamese words (may not be perfect but covers most)
4. Marking as "literal" or guessing common patterns
"""
import json, re
from pathlib import Path

path = Path('src/data/dictionary.json')
entries = json.loads(path.read_text())
word_to_vi = {}
for e in entries:
    w = e.get('word','').lower().strip()
    m = e.get('meaning','')
    if not w or m.startswith('(cụm từ:'): continue
    if m and not m.startswith('(c'):
        word_to_vi[w] = m

# Common A1-B1 multi-word mappings
COMMON = {
    'at night': 'vào ban đêm',
    'at school': 'ở trường',
    'at home': 'ở nhà',
    'at work': 'ở nơi làm việc',
    'at the park': 'ở công viên',
    'at the market': 'ở chợ',
    'at the store': 'ở cửa hàng',
    'at the library': 'ở thư viện',
    'at the beach': 'ở bãi biển',
    'at the zoo': 'ở sở thú',
    'at the table': 'ở bàn',
    'at the door': 'ở cửa',
    'at the window': 'ở cửa sổ',
    'at the end': 'ở cuối',
    'at the beginning': 'ở đầu',
    'at the top': 'ở trên cùng',
    'at the bottom': 'ở dưới cùng',
    'at the front': 'ở phía trước',
    'at the back': 'ở phía sau',
    'at the side': 'ở bên cạnh',
    'at the corner': 'ở góc',
    'at the same time': 'cùng lúc',
    'at the same moment': 'cùng lúc',
    'at least': 'ít nhất',
    'at most': 'nhiều nhất',
    'at first': 'ban đầu',
    'at last': 'cuối cùng',
    'at once': 'ngay lập tức',
    'in the morning': 'vào buổi sáng',
    'in the afternoon': 'vào buổi chiều',
    'in the evening': 'vào buổi tối',
    'in the night': 'vào ban đêm',
    'in the city': 'trong thành phố',
    'in the town': 'trong thị trấn',
    'in the village': 'trong làng',
    'in the country': 'ở nông thôn',
    'in the kitchen': 'trong bếp',
    'in the bedroom': 'trong phòng ngủ',
    'in the bathroom': 'trong phòng tắm',
    'in the classroom': 'trong lớp học',
    'in the garden': 'trong vườn',
    'in the park': 'trong công viên',
    'in the library': 'trong thư viện',
    'in the market': 'trong chợ',
    'in the house': 'trong nhà',
    'in the car': 'trong xe hơi',
    'in the world': 'trên thế giới',
    'in the sky': 'trên trời',
    'in the sea': 'trong biển',
    'in the water': 'dưới nước',
    'in the air': 'trong không khí',
    'on the wall': 'trên tường',
    'on the floor': 'trên sàn',
    'on the table': 'trên bàn',
    'on the chair': 'trên ghế',
    'on the bed': 'trên giường',
    'on the board': 'trên bảng',
    'on the ground': 'trên mặt đất',
    'on the left': 'ở bên trái',
    'on the right': 'ở bên phải',
    'by the lake': 'cạnh hồ',
    'by the river': 'cạnh sông',
    'by the sea': 'cạnh biển',
    'by the window': 'cạnh cửa sổ',
    'by the door': 'cạnh cửa',
    'by the table': 'cạnh bàn',
    'by the bed': 'cạnh giường',
    'by the chair': 'cạnh ghế',
    'by the way': 'tiện thể nói',
    'by hand': 'bằng tay',
    'on the way': 'trên đường',
    'on the way home': 'trên đường về nhà',
    'on the way back': 'trên đường trở lại',
    'on the way to school': 'trên đường đi học',
    'on time': 'đúng giờ',
    'in time': 'kịp thời',
    'in fact': 'thực tế',
    'in general': 'nói chung',
    'in particular': 'đặc biệt',
    'in detail': 'chi tiết',
    'in summary': 'tóm tắt',
    'in addition': 'thêm vào đó',
    'in conclusion': 'kết luận',
    'in brief': 'ngắn gọn',
    'as a result': 'kết quả là',
    'as well as': 'cũng như',
    'as well': 'cũng',
    'as soon as': 'ngay khi',
    'as long as': 'miễn là',
    'as far as': 'xa như',
    'as if': 'như thể',
    'as though': 'như thể',
    'as much as': 'nhiều như',
    'as many as': 'nhiều như',
    'such as': 'như',
    'so that': 'để mà',
    'so much': 'nhiều như vậy',
    'so many': 'nhiều như vậy',
    'so far': 'cho đến nay',
    'so long': 'lâu rồi',
    'no longer': 'không còn nữa',
    'not yet': 'chưa',
    'not only': 'không chỉ',
    'not just': 'không chỉ',
    'for example': 'ví dụ',
    'for instance': 'ví dụ',
    'for sure': 'chắc chắn',
    'for real': 'thật sự',
    'for a long time': 'trong một thời gian dài',
    'for a while': 'một lúc',
    'for a moment': 'một lát',
    'for a day': 'trong một ngày',
    'for a week': 'trong một tuần',
    'a few days': 'vài ngày',
    'a few weeks': 'vài tuần',
    'a few months': 'vài tháng',
    'a few years': 'vài năm',
    'a few hours': 'vài giờ',
    'a few minutes': 'vài phút',
    'a few times': 'vài lần',
    'a few people': 'vài người',
    'a few friends': 'vài người bạn',
    'a few students': 'vài học sinh',
    'a few children': 'vài trẻ em',
    'a few things': 'vài thứ',
    'a few books': 'vài cuốn sách',
    'a few words': 'vài từ',
    'a lot of': 'nhiều',
    'a lot': 'nhiều',
    'a bit': 'một chút',
    'a bit of': 'một chút',
    'a little': 'một ít',
    'a few': 'vài',
    'a long time': 'lâu lắm',
    'a long time ago': 'cách đây lâu lắm',
    'a long way': 'xa lắm',
    'a long walk': 'một quãng đường đi bộ dài',
    'a long story': 'một câu chuyện dài',
    'a long letter': 'một lá thư dài',
    'a long journey': 'một hành trình dài',
    'a long flight': 'một chuyến bay dài',
    'a long drive': 'một quãng đường lái xe dài',
    'a long day': 'một ngày dài',
    'a long week': 'một tuần dài',
    'a good time': 'một khoảng thời gian vui vẻ',
    'a great time': 'một khoảng thời gian tuyệt vời',
    'a wonderful time': 'một khoảng thời gian tuyệt vời',
    'a happy time': 'một khoảng thời gian hạnh phúc',
    'a sad time': 'một khoảng thời gian buồn',
    'a hard time': 'một khoảng thời gian khó khăn',
    'a difficult time': 'một khoảng thời gian khó khăn',
    'a busy time': 'một khoảng thời gian bận rộn',
    'a quiet time': 'một khoảng thời gian yên tĩnh',
    'a special time': 'một khoảng thời gian đặc biệt',
    'a nice time': 'một khoảng thời gian thú vị',
    'a fun time': 'một khoảng thời gian vui vẻ',
    'a great day': 'một ngày tuyệt vời',
    'a wonderful day': 'một ngày tuyệt vời',
    'a perfect day': 'một ngày hoàn hảo',
    'a sunny day': 'một ngày nắng',
    'a rainy day': 'một ngày mưa',
    'a cloudy day': 'một ngày nhiều mây',
    'a windy day': 'một ngày có gió',
    'a hot day': 'một ngày nóng',
    'a cold day': 'một ngày lạnh',
    'a warm day': 'một ngày ấm áp',
    'a cool day': 'một ngày mát mẻ',
    'a fun day': 'một ngày vui vẻ',
    'a fantastic day': 'một ngày tuyệt vời',
    'a new day': 'một ngày mới',
    'a busy day': 'một ngày bận rộn',
    'a relaxing day': 'một ngày thư giãn',
    'a big day': 'một ngày lớn',
    'a special day': 'một ngày đặc biệt',
    'an important day': 'một ngày quan trọng',
    'a beautiful day': 'một ngày đẹp',
    'a great way': 'một cách tuyệt vời',
    'a good way': 'một cách tốt',
    'a new way': 'một cách mới',
    'a different way': 'một cách khác',
    'a similar way': 'một cách tương tự',
    'a better way': 'một cách tốt hơn',
    'a smart way': 'một cách thông minh',
    'a clever way': 'một cách khéo léo',
    'a simple way': 'một cách đơn giản',
    'a safe way': 'một cách an toàn',
    'a fast way': 'một cách nhanh',
    'a slow way': 'một cách chậm',
    'many people': 'nhiều người',
    'many children': 'nhiều trẻ em',
    'many students': 'nhiều học sinh',
    'many friends': 'nhiều bạn bè',
    'many things': 'nhiều thứ',
    'many animals': 'nhiều động vật',
    'many places': 'nhiều nơi',
    'many families': 'nhiều gia đình',
    'many years': 'nhiều năm',
    'many times': 'nhiều lần',
    'some children': 'vài trẻ em',
    'some students': 'vài học sinh',
    'some friends': 'vài người bạn',
    'some people': 'vài người',
    'some things': 'vài thứ',
    'some places': 'vài nơi',
    'some days': 'vài ngày',
    'some times': 'vài lần',
    'every day': 'mỗi ngày',
    'every morning': 'mỗi sáng',
    'every evening': 'mỗi tối',
    'every night': 'mỗi đêm',
    'every week': 'mỗi tuần',
    'every month': 'mỗi tháng',
    'every year': 'mỗi năm',
    'every time': 'mỗi lần',
    'every child': 'mỗi đứa trẻ',
    'every student': 'mỗi học sinh',
    'every person': 'mỗi người',
    'every classroom': 'mỗi lớp học',
    'every family': 'mỗi gia đình',
    'every house': 'mỗi ngôi nhà',
    'every room': 'mỗi phòng',
    'first day': 'ngày đầu tiên',
    'first time': 'lần đầu tiên',
    'first grade': 'lớp một',
    'first week': 'tuần đầu tiên',
    'first month': 'tháng đầu tiên',
    'first year': 'năm đầu tiên',
    'first place': 'vị trí đầu tiên',
    'first step': 'bước đầu tiên',
    'first thing': 'điều đầu tiên',
    'next day': 'ngày hôm sau',
    'next time': 'lần sau',
    'next week': 'tuần sau',
    'next month': 'tháng sau',
    'next year': 'năm sau',
    'next step': 'bước tiếp theo',
    'next place': 'nơi tiếp theo',
    'next door': 'bên cạnh',
    'next to': 'cạnh',
    'last day': 'ngày cuối',
    'last time': 'lần cuối',
    'last week': 'tuần trước',
    'last month': 'tháng trước',
    'last year': 'năm ngoái',
    'last night': 'tối qua',
    'one day': 'một ngày',
    'one morning': 'một buổi sáng',
    'one evening': 'một buổi tối',
    'one night': 'một đêm',
    'one time': 'một lần',
    'one year': 'một năm',
    'one week': 'một tuần',
    'one month': 'một tháng',
    'one place': 'một nơi',
    'one thing': 'một thứ',
    'one way': 'một cách',
    'one person': 'một người',
    'one friend': 'một người bạn',
    'two days': 'hai ngày',
    'two weeks': 'hai tuần',
    'two months': 'hai tháng',
    'two years': 'hai năm',
    'two hours': 'hai giờ',
    'two minutes': 'hai phút',
    'three days': 'ba ngày',
    'three weeks': 'ba tuần',
    'three months': 'ba tháng',
    'three years': 'ba năm',
    'good morning': 'chào buổi sáng',
    'good afternoon': 'chào buổi chiều',
    'good evening': 'chào buổi tối',
    'good night': 'chúc ngủ ngon',
    'good day': 'ngày tốt lành',
    'good week': 'tuần tốt lành',
    'good luck': 'chúc may mắn',
    'good job': 'làm tốt lắm',
    'good work': 'công việc tốt',
    'good question': 'câu hỏi hay',
    'good idea': 'ý tưởng hay',
    'good answer': 'câu trả lời hay',
    'good choice': 'lựa chọn tốt',
    'good decision': 'quyết định tốt',
    'good news': 'tin tốt',
    'good friend': 'bạn tốt',
    'good friends': 'những người bạn tốt',
    'good student': 'học sinh giỏi',
    'good teacher': 'giáo viên giỏi',
    'good person': 'người tốt',
    'good book': 'sách hay',
    'good story': 'câu chuyện hay',
    'good song': 'bài hát hay',
    'good food': 'đồ ăn ngon',
    'good drink': 'đồ uống ngon',
    'good weather': 'thời tiết đẹp',
    'good times': 'những lúc vui vẻ',
    'good memories': 'những kỷ niệm đẹp',
    'good feeling': 'cảm giác tốt',
    'good mood': 'tâm trạng tốt',
    'good example': 'ví dụ tốt',
    'best friend': 'bạn thân nhất',
    'best friends': 'những người bạn thân',
    'best teacher': 'giáo viên tốt nhất',
    'best student': 'học sinh giỏi nhất',
    'best place': 'nơi tốt nhất',
    'best time': 'thời điểm tốt nhất',
    'best day': 'ngày tốt nhất',
    'best book': 'sách hay nhất',
    'best song': 'bài hát hay nhất',
    'best food': 'đồ ăn ngon nhất',
    'best gift': 'món quà tuyệt vời nhất',
    'big house': 'ngôi nhà lớn',
    'big school': 'ngôi trường lớn',
    'big family': 'gia đình đông người',
    'big class': 'lớp học lớn',
    'big city': 'thành phố lớn',
    'big tree': 'cây lớn',
    'big building': 'tòa nhà lớn',
    'big smile': 'nụ cười rộng',
    'big idea': 'ý tưởng lớn',
    'big dream': 'giấc mơ lớn',
    'big day': 'ngày quan trọng',
    'big surprise': 'bất ngờ lớn',
    'big gift': 'món quà lớn',
    'big moment': 'khoảnh khắc lớn',
    'big memory': 'ký ức lớn',
    'big fan': 'fan lớn',
    'big deal': 'chuyện lớn',
    'big problem': 'vấn đề lớn',
    'big change': 'thay đổi lớn',
    'big mistake': 'sai lầm lớn',
    'big help': 'giúp đỡ lớn',
    'big support': 'hỗ trợ lớn',
    'small house': 'ngôi nhà nhỏ',
    'small school': 'ngôi trường nhỏ',
    'small class': 'lớp học nhỏ',
    'small family': 'gia đình nhỏ',
    'small city': 'thành phố nhỏ',
    'small tree': 'cây nhỏ',
    'small smile': 'nụ cười nhẹ',
    'small idea': 'ý tưởng nhỏ',
    'small dream': 'giấc mơ nhỏ',
    'small step': 'bước nhỏ',
    'small change': 'thay đổi nhỏ',
    'small moment': 'khoảnh khắc nhỏ',
    'small memory': 'ký ức nhỏ',
    'small detail': 'chi tiết nhỏ',
    'small thing': 'thứ nhỏ',
    'small gift': 'món quà nhỏ',
    'small problem': 'vấn đề nhỏ',
    'small room': 'phòng nhỏ',
    'small apartment': 'căn hộ nhỏ',
    'long time': 'lâu lắm',
    'long day': 'ngày dài',
    'long way': 'xa lắm',
    'long walk': 'quãng đường đi bộ dài',
    'long journey': 'hành trình dài',
    'long trip': 'chuyến đi dài',
    'long flight': 'chuyến bay dài',
    'long drive': 'quãng đường lái xe dài',
    'long story': 'câu chuyện dài',
    'long letter': 'lá thư dài',
    'long message': 'tin nhắn dài',
    'long time ago': 'cách đây lâu lắm',
    'long time no see': 'lâu lắm rồi không gặp',
    'long before': 'lâu trước đó',
    'long after': 'lâu sau đó',
    'long since': 'từ lâu rồi',
    'short time': 'thời gian ngắn',
    'short day': 'ngày ngắn',
    'short walk': 'quãng đường đi bộ ngắn',
    'short journey': 'hành trình ngắn',
    'short trip': 'chuyến đi ngắn',
    'short flight': 'chuyến bay ngắn',
    'short drive': 'quãng đường lái xe ngắn',
    'short story': 'truyện ngắn',
    'short message': 'tin nhắn ngắn',
    'short letter': 'lá thư ngắn',
    'short while': 'một lúc',
    'short cut': 'đường tắt',
    'tall building': 'tòa nhà cao',
    'tall tree': 'cây cao',
    'tall man': 'người đàn ông cao',
    'tall woman': 'người phụ nữ cao',
    'tall person': 'người cao',
    'tall girl': 'cô gái cao',
    'tall boy': 'cậu bé cao',
    'young child': 'trẻ nhỏ',
    'young boy': 'cậu bé',
    'young girl': 'cô gái trẻ',
    'young man': 'chàng trai trẻ',
    'young woman': 'cô gái trẻ',
    'young people': 'người trẻ',
    'young student': 'học sinh trẻ',
    'young teacher': 'giáo viên trẻ',
    'old man': 'ông già',
    'old woman': 'bà già',
    'old people': 'người già',
    'old teacher': 'giáo viên già',
    'old friend': 'bạn cũ',
    'old friends': 'những người bạn cũ',
    'old house': 'ngôi nhà cũ',
    'old car': 'xe cũ',
    'old book': 'sách cũ',
    'old story': 'câu chuyện cũ',
    'old tree': 'cây cổ thụ',
    'old school': 'trường cũ',
    'old city': 'thành phố cổ',
    'old town': 'thị trấn cổ',
    'old village': 'làng cổ',
    'old country': 'đất nước cũ',
    'new friend': 'bạn mới',
    'new house': 'ngôi nhà mới',
    'new car': 'xe mới',
    'new job': 'công việc mới',
    'new baby': 'em bé mới',
    'new school': 'trường mới',
    'new class': 'lớp mới',
    'new teacher': 'giáo viên mới',
    'new student': 'học sinh mới',
    'new year': 'năm mới',
    'new month': 'tháng mới',
    'new week': 'tuần mới',
    'new day': 'ngày mới',
    'new life': 'cuộc sống mới',
    'new book': 'sách mới',
    'new story': 'câu chuyện mới',
    'new song': 'bài hát mới',
    'new game': 'trò chơi mới',
    'new idea': 'ý tưởng mới',
    'new plan': 'kế hoạch mới',
    'new project': 'dự án mới',
    'new goal': 'mục tiêu mới',
    'new word': 'từ mới',
    'new words': 'những từ mới',
    'new language': 'ngôn ngữ mới',
    'new place': 'nơi mới',
    'new city': 'thành phố mới',
    'new country': 'đất nước mới',
    'new home': 'nhà mới',
    'sunny day': 'ngày nắng',
    'sunny morning': 'buổi sáng nắng',
    'sunny afternoon': 'buổi chiều nắng',
    'sunny weather': 'thời tiết nắng',
    'rainy day': 'ngày mưa',
    'rainy morning': 'buổi sáng mưa',
    'rainy afternoon': 'buổi chiều mưa',
    'rainy weather': 'thời tiết mưa',
    'rainy season': 'mùa mưa',
    'cold day': 'ngày lạnh',
    'cold morning': 'buổi sáng lạnh',
    'cold afternoon': 'buổi chiều lạnh',
    'cold weather': 'thời tiết lạnh',
    'cold water': 'nước lạnh',
    'cold drink': 'đồ uống lạnh',
    'cold food': 'đồ ăn nguội',
    'hot day': 'ngày nóng',
    'hot morning': 'buổi sáng nóng',
    'hot afternoon': 'buổi chiều nóng',
    'hot weather': 'thời tiết nóng',
    'hot water': 'nước nóng',
    'hot drink': 'đồ uống nóng',
    'hot food': 'đồ ăn nóng',
    'busy day': 'ngày bận rộn',
    'busy week': 'tuần bận rộn',
    'busy morning': 'buổi sáng bận rộn',
    'busy afternoon': 'buổi chiều bận rộn',
    'quiet day': 'ngày yên tĩnh',
    'quiet night': 'đêm yên tĩnh',
    'quiet morning': 'buổi sáng yên tĩnh',
    'quiet afternoon': 'buổi chiều yên tĩnh',
    'nice day': 'ngày đẹp',
    'nice morning': 'buổi sáng đẹp',
    'nice afternoon': 'buổi chiều đẹp',
    'nice person': 'người tốt bụng',
    'nice place': 'nơi đẹp',
    'nice smile': 'nụ cười đẹp',
    'nice meal': 'bữa ăn ngon',
    'great day': 'ngày tuyệt vời',
    'great time': 'thời gian tuyệt vời',
    'great idea': 'ý tưởng tuyệt vời',
    'great place': 'nơi tuyệt vời',
    'great job': 'công việc tuyệt vời',
    'wonderful day': 'ngày tuyệt vời',
    'wonderful time': 'thời gian tuyệt vời',
    'wonderful place': 'nơi tuyệt vời',
    'wonderful trip': 'chuyến đi tuyệt vời',
    'amazing day': 'ngày tuyệt vời',
    'amazing time': 'thời gian tuyệt vời',
    'amazing place': 'nơi tuyệt vời',
    'lovely day': 'ngày đáng yêu',
    'lovely place': 'nơi đáng yêu',
    'lovely smile': 'nụ cười đáng yêu',
    'lovely person': 'người đáng yêu',
    'lovely time': 'thời gian đáng yêu',
    'beautiful day': 'ngày đẹp',
    'beautiful place': 'nơi đẹp',
    'beautiful smile': 'nụ cười đẹp',
    'beautiful person': 'người đẹp',
    'beautiful flower': 'hoa đẹp',
    'beautiful tree': 'cây đẹp',
    'funny story': 'câu chuyện vui',
    'funny joke': 'trò đùa vui',
    'clever idea': 'ý tưởng thông minh',
    'kind person': 'người tử tế',
    'kind friend': 'bạn tử tế',
    'kind teacher': 'giáo viên tử tế',
    'kind smile': 'nụ cười tử tế',
    'happy family': 'gia đình hạnh phúc',
    'happy time': 'thời gian hạnh phúc',
    'happy day': 'ngày hạnh phúc',
    'happy person': 'người vui vẻ',
    'happy smile': 'nụ cười hạnh phúc',
    'happy face': 'khuôn mặt vui vẻ',
    'happy memory': 'ký ức vui',
    'high school': 'trường trung học',
    'middle school': 'trường trung học cơ sở',
    'elementary school': 'trường tiểu học',
    'primary school': 'trường tiểu học',
    'kindergarten': 'trường mẫu giáo',
    'preschool': 'trường mầm non',
    'go to school': 'đi học',
    'go home': 'về nhà',
    'go to bed': 'đi ngủ',
    'go to work': 'đi làm',
    'go away': 'đi đi',
    'go back': 'quay lại',
    'go out': 'ra ngoài',
    'go outside': 'ra ngoài',
    'go in': 'đi vào',
    'go up': 'đi lên',
    'go down': 'đi xuống',
    'come back': 'quay lại',
    'come home': 'về nhà',
    'come in': 'vào đi',
    'come out': 'ra ngoài',
    'come here': 'lại đây',
    'come on': 'nào, đi nào',
    'come up': 'đi lên',
    'come down': 'đi xuống',
    'look up': 'nhìn lên',
    'look down': 'nhìn xuống',
    'look around': 'nhìn xung quanh',
    'look out': 'cẩn thận',
    'look at': 'nhìn vào',
    'look for': 'tìm kiếm',
    'look like': 'trông giống',
    'look after': 'chăm sóc',
    'look into': 'điều tra',
    'look over': 'xem qua',
    'look through': 'xem xét kỹ',
    'look back': 'nhìn lại',
    'take care': 'chăm sóc',
    'take care of': 'chăm sóc',
    'take a look': 'xem qua',
    'take a break': 'nghỉ giải lao',
    'take a rest': 'nghỉ ngơi',
    'take a walk': 'đi bộ',
    'take a seat': 'ngồi xuống',
    'take a shower': 'tắm',
    'take a photo': 'chụp ảnh',
    'take a picture': 'chụp ảnh',
    'take photos': 'chụp ảnh',
    'take time': 'mất thời gian',
    'take your time': 'từ từ, không vội',
    'take part': 'tham gia',
    'take part in': 'tham gia',
    'take place': 'diễn ra',
    'take over': 'tiếp quản',
    'take off': 'cởi ra, cất cánh',
    'take out': 'lấy ra',
    'give up': 'từ bỏ',
    'give in': 'nhượng bộ',
    'give away': 'tặng cho',
    'give back': 'trả lại',
    'make sure': 'chắc chắn',
    'make up': 'bịa đặt, trang điểm',
    'make friends': 'kết bạn',
    'make a wish': 'ước một điều',
    'make a decision': 'đưa ra quyết định',
    'make a choice': 'đưa ra lựa chọn',
    'make a plan': 'lập kế hoạch',
    'make a difference': 'tạo ra sự khác biệt',
    'make a change': 'tạo ra thay đổi',
    'make a mistake': 'mắc sai lầm',
    'make sense': 'hợp lý',
    'have a good day': 'có một ngày tốt lành',
    'have a great day': 'có một ngày tuyệt vời',
    'have a nice day': 'có một ngày thú vị',
    'have a wonderful day': 'có một ngày tuyệt vời',
    'have a happy day': 'có một ngày hạnh phúc',
    'have a good time': 'vui vẻ',
    'have a great time': 'có thời gian tuyệt vời',
    'have a nice time': 'có thời gian thú vị',
    'have a wonderful time': 'có thời gian tuyệt vời',
    'have a happy time': 'có thời gian hạnh phúc',
    'have fun': 'vui vẻ',
    'have lunch': 'ăn trưa',
    'have dinner': 'ăn tối',
    'have breakfast': 'ăn sáng',
    'have a snack': 'ăn nhẹ',
    'have a drink': 'uống',
    'have a plan': 'có kế hoạch',
    'have an idea': 'có ý tưởng',
    'have a dream': 'có giấc mơ',
    'have a question': 'có câu hỏi',
    'have a problem': 'có vấn đề',
    'have a thought': 'có suy nghĩ',
    'have a goal': 'có mục tiêu',
    'do homework': 'làm bài tập về nhà',
    'do housework': 'làm việc nhà',
    'do the dishes': 'rửa bát',
    'do the laundry': 'giặt đồ',
    'do a good job': 'làm tốt',
    'do your best': 'cố gắng hết sức',
    'do well': 'làm tốt',
    'do better': 'làm tốt hơn',
    'wake up': 'thức dậy',
    'wake up early': 'dậy sớm',
    'put on': 'mặc vào',
    'put away': 'cất đi',
    'put down': 'đặt xuống',
    'put in': 'đặt vào',
    'put out': 'dập tắt',
    'turn on': 'bật',
    'turn off': 'tắt',
    'turn around': 'quay lại',
    'try again': 'thử lại',
    'try hard': 'cố gắng',
    'try to': 'cố gắng',
    'walk to school': 'đi bộ đến trường',
    'walk home': 'đi bộ về nhà',
    'walk around': 'đi bộ xung quanh',
    'run fast': 'chạy nhanh',
    'run around': 'chạy xung quanh',
    'jump up': 'nhảy lên',
    'jump over': 'nhảy qua',
    'jump high': 'nhảy cao',
    'jump on': 'nhảy lên',
    'fly up': 'bay lên',
    'fly away': 'bay đi',
    'fly high': 'bay cao',
    'fly over': 'bay qua',
    'swim fast': 'bơi nhanh',
    'swim with': 'bơi với',
    'climb up': 'leo lên',
    'climb down': 'leo xuống',
    'climb on': 'leo lên',
    'work together': 'làm việc cùng nhau',
    'work hard': 'làm việc chăm chỉ',
    'work on': 'làm việc trên',
    'work out': 'giải quyết',
    'work well': 'làm việc tốt',
    'play together': 'chơi cùng nhau',
    'play with': 'chơi với',
    'live together': 'sống cùng nhau',
    'study hard': 'học chăm chỉ',
    'study together': 'học cùng nhau',
    'study english': 'học tiếng Anh',
    'study math': 'học toán',
    'learn english': 'học tiếng Anh',
    'learn math': 'học toán',
    'speak english': 'nói tiếng Anh',
    'tell me': 'nói với tôi',
    'tell us': 'nói với chúng tôi',
    'tell a story': 'kể chuyện',
    'ask me': 'hỏi tôi',
    'ask him': 'hỏi anh ấy',
    'ask her': 'hỏi cô ấy',
    'ask them': 'hỏi họ',
    'ask a question': 'đặt câu hỏi',
    'help me': 'giúp tôi',
    'help us': 'giúp chúng tôi',
    'help them': 'giúp họ',
    'help her': 'giúp cô ấy',
    'help him': 'giúp anh ấy',
    'wash my hands': 'rửa tay',
    'wash your hands': 'rửa tay',
    'brush my teeth': 'đánh răng',
    'brush your teeth': 'đánh răng',
    'feed the dog': 'cho chó ăn',
    'feed the cat': 'cho mèo ăn',
    'plant trees': 'trồng cây',
    'plant flowers': 'trồng hoa',
    'plant a tree': 'trồng một cây',
    'plant a flower': 'trồng một hoa',
    'open the door': 'mở cửa',
    'close the door': 'đóng cửa',
    'open the window': 'mở cửa sổ',
    'close the window': 'đóng cửa sổ',
    'watch tv': 'xem TV',
    'watch the news': 'xem tin tức',
    'see the doctor': 'gặp bác sĩ',
    'see the dentist': 'gặp nha sĩ',
    'eat breakfast': 'ăn sáng',
    'eat lunch': 'ăn trưa',
    'eat dinner': 'ăn tối',
    'eat food': 'ăn thức ăn',
    'drink water': 'uống nước',
    'read a book': 'đọc sách',
    'read books': 'đọc sách',
    'write a story': 'viết truyện',
    'write a letter': 'viết thư',
    'sing a song': 'hát bài hát',
    'sing songs': 'hát các bài hát',
    'play a game': 'chơi trò chơi',
    'play games': 'chơi trò chơi',
    'draw a picture': 'vẽ tranh',
    'draw pictures': 'vẽ tranh',
    'paint a picture': 'vẽ tranh',
    'clean and fresh': 'sạch và tươi',
    'happy birthday': 'sinh nhật vui vẻ',
    'good for the environment': 'tốt cho môi trường',
    'mode of transport': 'phương thức vận chuyển',
    'from place to place': 'từ nơi này sang nơi khác',
    'learn about': 'học về',
    'types of transport': 'các loại phương tiện',
    'travel by car': 'đi bằng ô tô',
    'ride a motorbike': 'đi xe máy',
    'longer journeys': 'hành trình dài hơn',
    'great choice': 'lựa chọn tuyệt vời',
    'steel rails': 'đường ray thép',
    'carry hundreds of passengers': 'chở hàng trăm hành khách',
    'carry thousands of passengers': 'chở hàng nghìn hành khách',
    'kilometres per hour': 'kilômét mỗi giờ',
    'without your own vehicle': 'không có phương tiện của riêng bạn',
    'take a taxi': 'đi taxi',
    'taxi driver': 'tài xế taxi',
    'look different': 'trông khác nhau',
    'from each other': 'với nhau',
    'round face': 'khuôn mặt tròn',
    'brown eyes': 'mắt nâu',
    'long brown hair': 'tóc nâu dài',
    'very tall': 'rất cao',
    'for my age': 'so với tuổi',
    'wears glasses': 'đeo kính',
    'brown eyes': 'mắt nâu',
    'happy smile': 'nụ cười hạnh phúc',
    'old man': 'ông lão',
    'young boy': 'cậu bé',
    'young girl': 'cô bé',
    'every room': 'mỗi phòng',
    'every morning I': 'mỗi sáng tôi',
    'very important': 'rất quan trọng',
    'very big': 'rất lớn',
    'very small': 'rất nhỏ',
    'very good': 'rất tốt',
    'very bad': 'rất tệ',
    'very well': 'rất tốt',
    'very fast': 'rất nhanh',
    'very slow': 'rất chậm',
    'very far': 'rất xa',
    'very near': 'rất gần',
    'very much': 'rất nhiều',
    'very many': 'rất nhiều',
    'very little': 'rất ít',
    'very few': 'rất ít',
    'very often': 'rất thường xuyên',
    'very early': 'rất sớm',
    'very late': 'rất muộn',
    'very quick': 'rất nhanh',
    'happy birthday': 'chúc mừng sinh nhật',
    'very beautiful': 'rất đẹp',
    'very big deal': 'chuyện rất lớn',
    'very well known': 'rất nổi tiếng',
    'over the world': 'khắp thế giới',
    'a lot of fun': 'rất vui',
    'a lot of food': 'nhiều thức ăn',
    'a lot of work': 'nhiều việc',
    'a lot of water': 'nhiều nước',
    'a lot of time': 'nhiều thời gian',
    'a lot of money': 'nhiều tiền',
    'a lot of energy': 'nhiều năng lượng',
    'a lot of love': 'nhiều tình yêu',
    'a lot of people': 'nhiều người',
    'a lot of friends': 'nhiều bạn bè',
    'a lot of things': 'nhiều thứ',
    'long time ago': 'cách đây lâu',
    'long way to go': 'còn xa',
    'most of the time': 'hầu hết thời gian',
    'many times': 'nhiều lần',
    'a few minutes ago': 'vài phút trước',
    'a few hours ago': 'vài giờ trước',
    'a few days ago': 'vài ngày trước',
    'a few weeks ago': 'vài tuần trước',
    'a few months ago': 'vài tháng trước',
    'a few years ago': 'vài năm trước',
    'all day long': 'cả ngày',
    'all night long': 'cả đêm',
    'all year long': 'cả năm',
    'all the time': 'luôn luôn',
    'all of us': 'tất cả chúng ta',
    'all of them': 'tất cả họ',
    'all of you': 'tất cả các bạn',
    'all of these': 'tất cả những thứ này',
    'all of those': 'tất cả những thứ đó',
    'all right': 'được rồi',
    'one by one': 'từng người một',
    'side by side': 'cạnh nhau',
    'day by day': 'ngày qua ngày',
    'bit by bit': 'từng chút một',
    'step by step': 'từng bước một',
    'little by little': 'từng chút một',
    'more and more': 'ngày càng nhiều',
    'one another': 'lẫn nhau',
    'one after another': 'lần lượt',
    'one after the other': 'lần lượt',
    'face to face': 'đối diện',
    'hand in hand': 'nắm tay nhau',
    'side to side': 'qua lại',
    'over and over': 'lặp đi lặp lại',
    'over and over again': 'lặp đi lặp lại',
    'again and again': 'lặp đi lặp lại',
    'time and time again': 'nhiều lần',
    'time after time': 'nhiều lần',
    'day after day': 'ngày qua ngày',
    'day in day out': 'ngày này qua ngày khác',
    'week after week': 'tuần qua tuần',
    'month after month': 'tháng qua tháng',
    'year after year': 'năm qua năm',
    'day to day': 'hàng ngày',
    'back and forth': 'qua lại',
    'up and down': 'lên xuống',
    'to and fro': 'tới lui',
    'here and there': 'khắp nơi',
    'now and then': 'thỉnh thoảng',
    'so far so good': 'tạm ổn',
    'as soon as possible': 'càng sớm càng tốt',
    'as well as possible': 'tốt nhất có thể',
    'at first sight': 'thoạt nhìn',
    'at first glance': 'thoạt nhìn',
    'at all costs': 'bằng mọi giá',
    'at any cost': 'bằng mọi giá',
    'at any rate': 'dù sao',
    'at the moment': 'ngay lúc này',
    'at the end of': 'cuối cùng',
    'at the beginning of': 'lúc đầu của',
    'at the start of': 'khi bắt đầu',
    'at the start': 'lúc đầu',
    'in the middle': 'ở giữa',
    'in the middle of': 'ở giữa',
    'in the center': 'ở trung tâm',
    'in front of': 'phía trước',
    'in back of': 'phía sau',
    'on top of': 'trên đỉnh',
    'on the top of': 'trên đỉnh',
    'on the bottom of': 'ở dưới đáy',
    'on the way home': 'trên đường về nhà',
    'on the way back': 'trên đường trở lại',
    'in the meantime': 'trong thời gian chờ đợi',
    'in the meanwhile': 'trong lúc đó',
    'in the long run': 'về lâu dài',
    'in the short run': 'về ngắn hạn',
    'in the long term': 'về lâu dài',
    'in the short term': 'về ngắn hạn',
    'over the weekend': 'cuối tuần',
    'on the weekend': 'cuối tuần',
    'on weekends': 'vào cuối tuần',
    'on weekdays': 'vào các ngày trong tuần',
    'in the morning of': 'vào buổi sáng của',
    'in the evening of': 'vào buổi tối của',
    'in the night of': 'vào đêm của',
    'in the afternoon of': 'vào buổi chiều của',
    'on the morning of': 'vào buổi sáng của',
    'in the countryside': 'ở nông thôn',
    'in the city center': 'ở trung tâm thành phố',
    'in the middle class': 'tầng lớp trung lưu',
    'in the foreground': 'ở phía trước',
    'in the background': 'ở phía sau',
    'in the dark': 'trong bóng tối',
    'in the light': 'trong ánh sáng',
    'in the rain': 'dưới mưa',
    'in the snow': 'dưới tuyết',
    'in the sun': 'dưới nắng',
    'in the shade': 'trong bóng râm',
    'in the wind': 'trong gió',
    'in the heat': 'trong nóng',
    'in the cold': 'trong lạnh',
    'under the weather': 'không khỏe',
    'under the sun': 'dưới ánh nắng',
    'under the moon': 'dưới ánh trăng',
    'over the moon': 'vui mừng khôn xiết',
    'on the radio': 'trên radio',
    'on the phone': 'trên điện thoại',
    'on the internet': 'trên internet',
    'on the computer': 'trên máy tính',
    'on the way home from school': 'trên đường về nhà từ trường',
    'in the meantime': 'trong thời gian chờ đợi',
    'in the meantime of': 'trong khoảng thời gian của',
    'every once in a while': 'thỉnh thoảng',
    'every now and then': 'thỉnh thoảng',
    'every so often': 'thỉnh thoảng',
    'from time to time': 'thỉnh thoảng',
    'now and then': 'thỉnh thoảng',
    'on the other hand': 'mặt khác',
    'on the contrary': 'trái lại',
    'on the other side': 'ở phía bên kia',
    'from now on': 'từ giờ trở đi',
    'from then on': 'từ lúc đó trở đi',
    'from that day on': 'từ ngày đó trở đi',
    'for the first time': 'lần đầu tiên',
    'for the last time': 'lần cuối cùng',
    'for the rest of the year': 'phần còn lại của năm',
    'for the rest of the day': 'phần còn lại của ngày',
    'for the rest of the week': 'phần còn lại của tuần',
    'at the end of the day': 'cuối ngày',
    'at the end of the week': 'cuối tuần',
    'at the end of the month': 'cuối tháng',
    'at the end of the year': 'cuối năm',
    'in the beginning of the year': 'đầu năm',
    'in the middle of the night': 'giữa đêm',
    'in the middle of the day': 'giữa ngày',
    'in the middle of the week': 'giữa tuần',
    'on the way home from work': 'trên đường về nhà từ nơi làm việc',
    'over the rainbow': 'trên cầu vồng',
    'under the table': 'dưới bàn',
    'under the bed': 'dưới giường',
    'under the chair': 'dưới ghế',
    'under the desk': 'dưới bàn',
    'over the ocean': 'trên đại dương',
    'over the mountains': 'trên những ngọn núi',
    'over the city': 'trên thành phố',
    'over the river': 'trên sông',
    'across the street': 'qua đường',
    'across the road': 'qua đường',
    'across the river': 'qua sông',
    'across the sea': 'qua biển',
    'across the ocean': 'qua đại dương',
    'along the road': 'dọc đường',
    'along the river': 'dọc sông',
    'along the street': 'dọc phố',
    'along the way': 'dọc đường',
    'around the world': 'khắp thế giới',
    'around the house': 'khắp nhà',
    'around the city': 'khắp thành phố',
    'around the corner': 'ngay góc',
    'around the world': 'khắp thế giới',
    'through the window': 'qua cửa sổ',
    'through the door': 'qua cửa',
    'through the park': 'qua công viên',
    'past the school': 'qua trường học',
    'past the park': 'qua công viên',
    'past the house': 'qua nhà',
    'behind the house': 'phía sau nhà',
    'behind the school': 'phía sau trường',
    'behind the door': 'phía sau cửa',
    'in front of the house': 'phía trước nhà',
    'in front of the school': 'phía trước trường',
    'next to the': 'cạnh',
    'far from': 'xa',
    'far away': 'xa xôi',
    'close to': 'gần',
    'near to': 'gần',
    'right next to': 'ngay cạnh',
    'right here': 'ngay tại đây',
    'right there': 'ngay tại đó',
    'right now': 'ngay bây giờ',
    'right away': 'ngay lập tức',
    'right next to': 'ngay cạnh',
    'over here': 'ở đây',
    'over there': 'ở kia',
    'down here': 'xuống đây',
    'down there': 'xuống kia',
    'up here': 'lên đây',
    'up there': 'lên kia',
    'down the street': 'xuống phố',
    'down the road': 'xuống đường',
    'up the hill': 'lên đồi',
    'up the stairs': 'lên cầu thang',
    'down the stairs': 'xuống cầu thang',
    'along with': 'cùng với',
    'together with': 'cùng với',
    'alongside with': 'cùng với',
    'apart from': 'ngoài ra',
    'away from': 'xa khỏi',
    'as well as': 'cũng như',
    'as long as': 'miễn là',
    'as soon as': 'ngay khi',
    'as far as': 'xa như',
    'as much as': 'nhiều như',
    'as many as': 'nhiều như',
    'as if': 'như thể',
    'as though': 'như thể',
    'so that': 'để mà',
    'so far': 'cho đến nay',
    'so long': 'lâu rồi',
    'so much': 'nhiều như vậy',
    'so many': 'nhiều như vậy',
    'so that': 'để mà',
    'no longer': 'không còn nữa',
    'not only': 'không chỉ',
    'not just': 'không chỉ',
    'not yet': 'chưa',
    'not really': 'không hẳn',
    'in order to': 'để',
    'in order not to': 'để không',
    'as well as possible': 'tốt nhất có thể',
    'as soon as possible': 'càng sớm càng tốt',
    'so as to': 'để',
    'such as': 'như',
    'rather than': 'thay vì',
    'other than': 'ngoài',
    'instead of': 'thay vì',
    'in case of': 'trong trường hợp',
    'in case': 'trong trường hợp',
    'because of': 'vì',
    'because of the': 'vì',
    'according to': 'theo',
    'thanks to': 'cảm ơn',
    'due to': 'do',
    'in front': 'ở phía trước',
    'at back': 'ở phía sau',
    'at the back of': 'ở phía sau',
    'at the front of': 'ở phía trước',
    'in the front of': 'ở phía trước',
    'in the back of': 'ở phía sau',
    'under the rain': 'dưới mưa',
    'in the jungle': 'trong rừng',
    'in the forest': 'trong rừng',
    'in the field': 'trong cánh đồng',
    'in the meadow': 'trong đồng cỏ',
    'on the farm': 'ở trang trại',
    'on the beach': 'ở bãi biển',
    'in the mountains': 'trong núi',
    'on the island': 'trên đảo',
    'on the hill': 'trên đồi',
    'in the valley': 'trong thung lũng',
    'by the river bank': 'bên bờ sông',
    'in the desert': 'trong sa mạc',
    'in the jungle of': 'trong rừng của',
    'in the forest of': 'trong rừng của',
    'at the top of': 'ở trên cùng',
    'at the bottom of': 'ở dưới cùng',
    'in the middle of the': 'ở giữa',
    'over the top': 'quá đà',
    'over the edge': 'bên bờ vực',
    'over the wall': 'qua tường',
    'over the fence': 'qua hàng rào',
    'over the bridge': 'qua cầu',
    'under the bridge': 'dưới cầu',
    'under the water': 'dưới nước',
    'under the ground': 'dưới đất',
    'under the sky': 'dưới bầu trời',
    'under the stars': 'dưới những ngôi sao',
    'under the tree': 'dưới gốc cây',
    'under the sun': 'dưới ánh nắng',
    'under the moon': 'dưới ánh trăng',
    'under the rainbow': 'dưới cầu vồng',
    'a bit more': 'thêm một chút',
    'a bit less': 'ít hơn một chút',
    'a bit tired': 'hơi mệt',
    'a bit cold': 'hơi lạnh',
    'a bit warm': 'hơi ấm',
    'a bit hot': 'hơi nóng',
    'a bit hungry': 'hơi đói',
    'a bit thirsty': 'hơi khát',
    'a bit sleepy': 'hơi buồn ngủ',
    'a bit better': 'tốt hơn một chút',
    'a bit earlier': 'sớm hơn một chút',
    'a bit later': 'muộn hơn một chút',
    'a bit longer': 'dài hơn một chút',
    'a bit shorter': 'ngắn hơn một chút',
    'a bit taller': 'cao hơn một chút',
    'a bit bigger': 'lớn hơn một chút',
    'a bit smaller': 'nhỏ hơn một chút',
    'a little more': 'thêm một ít',
    'a little less': 'ít hơn một ít',
    'a little tired': 'hơi mệt',
    'a little cold': 'hơi lạnh',
    'a little warm': 'hơi ấm',
    'a little hot': 'hơi nóng',
    'a little hungry': 'hơi đói',
    'a little thirsty': 'hơi khát',
    'a little sleepy': 'hơi buồn ngủ',
    'a little better': 'tốt hơn một ít',
    'a little earlier': 'sớm hơn một ít',
    'a little later': 'muộn hơn một ít',
    'a little longer': 'dài hơn một ít',
    'a little shorter': 'ngắn hơn một ít',
    'a little taller': 'cao hơn một ít',
    'a little bigger': 'lớn hơn một ít',
    'a little smaller': 'nhỏ hơn một ít',
    'a little while': 'một lúc',
    'a little while ago': 'cách đây một lúc',
    'a little bit': 'một chút',
    'a little bit of': 'một chút',
    'a little bit more': 'thêm một chút',
    'a little bit less': 'ít hơn một chút',
    'a little bit of time': 'một chút thời gian',
    'a little bit of money': 'một chút tiền',
    'a little bit of food': 'một chút thức ăn',
    'a little bit of water': 'một chút nước',
    'a little bit of luck': 'một chút may mắn',
    'a little bit of help': 'một chút giúp đỡ',
    'a little bit of love': 'một chút tình yêu',
    'a little bit of fun': 'một chút niềm vui',
    'a little bit of music': 'một chút âm nhạc',
    'a little bit of art': 'một chút nghệ thuật',
    'a little bit of poetry': 'một chút thơ',
    'a little bit of history': 'một chút lịch sử',
    'a little bit of science': 'một chút khoa học',
    'a little bit of nature': 'một chút thiên nhiên',
    'a little bit of adventure': 'một chút phiêu lưu',
    'a little bit of imagination': 'một chút trí tưởng tượng',
    'a little bit of patience': 'một chút kiên nhẫn',
    'a little bit of practice': 'một chút luyện tập',
    'a little bit of effort': 'một chút nỗ lực',
    'a little bit of courage': 'một chút can đảm',
    'a little bit of confidence': 'một chút tự tin',
    'a little bit of kindness': 'một chút tử tế',
    'a little bit of love and care': 'một chút tình yêu và sự chăm sóc',
    'a piece of': 'một mảnh',
    'a piece of cake': 'một miếng bánh',
    'a piece of bread': 'một miếng bánh mì',
    'a piece of paper': 'một tờ giấy',
    'a piece of music': 'một bản nhạc',
    'a piece of art': 'một tác phẩm nghệ thuật',
    'a piece of advice': 'một lời khuyên',
    'a piece of information': 'một thông tin',
    'a piece of news': 'một tin tức',
    'a piece of advice': 'một lời khuyên',
    'a piece of furniture': 'một món đồ nội thất',
    'a piece of luggage': 'một món hành lý',
    'a piece of luggage': 'một món hành lý',
    'a cup of': 'một cốc',
    'a cup of tea': 'một cốc trà',
    'a cup of coffee': 'một cốc cà phê',
    'a cup of water': 'một cốc nước',
    'a cup of juice': 'một cốc nước ép',
    'a cup of milk': 'một cốc sữa',
    'a cup of hot chocolate': 'một cốc sô-cô-la nóng',
    'a cup of soup': 'một cốc súp',
    'a cup of rice': 'một cốc cơm',
    'a glass of': 'một cốc',
    'a glass of water': 'một cốc nước',
    'a glass of milk': 'một cốc sữa',
    'a glass of juice': 'một cốc nước ép',
    'a glass of tea': 'một cốc trà',
    'a glass of wine': 'một cốc rượu vang',
    'a glass of beer': 'một cốc bia',
    'a glass of lemonade': 'một cốc nước chanh',
    'a glass of orange juice': 'một cốc nước cam',
    'a bottle of': 'một chai',
    'a bottle of water': 'một chai nước',
    'a bottle of juice': 'một chai nước ép',
    'a bottle of milk': 'một chai sữa',
    'a bottle of wine': 'một chai rượu vang',
    'a bottle of beer': 'một chai bia',
    'a bottle of lemonade': 'một chai nước chanh',
    'a bottle of orange juice': 'một chai nước cam',
    'a bowl of': 'một bát',
    'a bowl of rice': 'một bát cơm',
    'a bowl of soup': 'một bát súp',
    'a bowl of cereal': 'một bát ngũ cốc',
    'a bowl of noodles': 'một bát mì',
    'a bowl of pasta': 'một bát mì ống',
    'a bowl of salad': 'một bát xà lách',
    'a bowl of fruit': 'một bát trái cây',
    'a plate of': 'một đĩa',
    'a plate of rice': 'một đĩa cơm',
    'a plate of pasta': 'một đĩa mì ống',
    'a plate of noodles': 'một đĩa mì',
    'a plate of fruit': 'một đĩa trái cây',
    'a plate of vegetables': 'một đĩa rau',
    'a bag of': 'một túi',
    'a bag of rice': 'một túi gạo',
    'a bag of flour': 'một túi bột mì',
    'a bag of sugar': 'một túi đường',
    'a bag of candy': 'một túi kẹo',
    'a bag of apples': 'một túi táo',
    'a bag of oranges': 'một túi cam',
    'a bag of potatoes': 'một túi khoai tây',
    'a bag of chips': 'một túi bim bim',
    'a box of': 'một hộp',
    'a box of chocolates': 'một hộp sô-cô-la',
    'a box of cereal': 'một hộp ngũ cốc',
    'a box of tissues': 'một hộp khăn giấy',
    'a box of crayons': 'một hộp bút sáp',
    'a box of pencils': 'một hộp bút chì',
    'a box of markers': 'một hộp bút dạ',
    'a box of toys': 'một hộp đồ chơi',
    'a box of books': 'một hộp sách',
    'a basket of': 'một giỏ',
    'a basket of fruit': 'một giỏ trái cây',
    'a basket of apples': 'một giỏ táo',
    'a basket of flowers': 'một giỏ hoa',
    'a basket of eggs': 'một giỏ trứng',
    'a basket of bread': 'một giỏ bánh mì',
    'a basket of vegetables': 'một giỏ rau',
    'a basket of fruits': 'một giỏ trái cây',
    'a basket of berries': 'một giỏ quả mọng',
    'a group of': 'một nhóm',
    'a group of friends': 'một nhóm bạn bè',
    'a group of students': 'một nhóm học sinh',
    'a group of children': 'một nhóm trẻ em',
    'a group of people': 'một nhóm người',
    'a group of animals': 'một nhóm động vật',
    'a group of birds': 'một nhóm chim',
    'a group of fish': 'một nhóm cá',
    'a group of trees': 'một nhóm cây',
    'a group of flowers': 'một nhóm hoa',
    'a team of': 'một đội',
    'a team of doctors': 'một đội bác sĩ',
    'a team of nurses': 'một đội y tá',
    'a team of teachers': 'một đội giáo viên',
    'a team of engineers': 'một đội kỹ sư',
    'a team of scientists': 'một đội nhà khoa học',
    'a team of players': 'một đội cầu thủ',
    'a team of workers': 'một đội công nhân',
    'a team of volunteers': 'một đội tình nguyện viên',
    'a family of': 'một gia đình',
    'a family of four': 'một gia đình bốn người',
    'a family of five': 'một gia đình năm người',
    'a family of six': 'một gia đình sáu người',
    'a family of seven': 'một gia đình bảy người',
    'a family of eight': 'một gia đình tám người',
    'a kind of': 'một loại',
    'a sort of': 'một loại',
    'a type of': 'một loại',
    'a number of': 'một số',
    'a pair of': 'một cặp',
    'a pair of shoes': 'một đôi giày',
    'a pair of socks': 'một đôi tất',
    'a pair of glasses': 'một cặp kính',
    'a pair of scissors': 'một cái kéo',
    'a pair of pants': 'một cái quần',
    'a pair of shoes': 'một đôi giày',
    'a pair of jeans': 'một cái quần jean',
    'a set of': 'một bộ',
    'a set of keys': 'một bộ chìa khóa',
    'a set of tools': 'một bộ dụng cụ',
    'a set of books': 'một bộ sách',
    'a set of pens': 'một bộ bút',
    'a set of markers': 'một bộ bút dạ',
    'a set of colors': 'một bộ màu',
    'a set of rules': 'một bộ quy tắc',
    'a set of instructions': 'một bộ hướng dẫn',
    'a set of problems': 'một bộ bài toán',
    'a set of questions': 'một bộ câu hỏi',
    'a set of answers': 'một bộ câu trả lời',
    'a kind of': 'một loại',
    'a sort of': 'một loại',
    'a type of': 'một loại',
    'a number of': 'một số',
    'a pair of': 'một cặp',
    'a set of': 'một bộ',
    'a lot of': 'nhiều',
    'lots of': 'nhiều',
    'plenty of': 'nhiều',
    'scads of': 'nhiều',
    'oodles of': 'nhiều',
    'heaps of': 'nhiều',
    'tons of': 'nhiều',
    'a great deal of': 'rất nhiều',
    'a good deal of': 'nhiều',
    'a great number of': 'rất nhiều',
    'a large number of': 'nhiều',
    'a small number of': 'một số ít',
    'a number of people': 'một số người',
    'a number of students': 'một số học sinh',
    'a number of friends': 'một số bạn bè',
    'a number of things': 'một số thứ',
    'a number of books': 'một số sách',
    'a number of days': 'một số ngày',
    'a number of years': 'một số năm',
    'a number of times': 'một số lần',
    'a number of hours': 'một số giờ',
    'a number of minutes': 'một số phút',
    'a number of children': 'một số trẻ em',
    'a couple of': 'vài',
    'a couple of days': 'vài ngày',
    'a couple of weeks': 'vài tuần',
    'a couple of months': 'vài tháng',
    'a couple of years': 'vài năm',
    'a couple of hours': 'vài giờ',
    'a couple of minutes': 'vài phút',
    'a couple of times': 'vài lần',
    'a couple of people': 'vài người',
    'a couple of friends': 'vài người bạn',
    'a couple of students': 'vài học sinh',
    'a couple of children': 'vài trẻ em',
    'a couple of things': 'vài thứ',
    'a couple of books': 'vài cuốn sách',
    'in my family': 'trong gia đình tôi',
    'in my house': 'trong nhà tôi',
    'in my home': 'trong nhà tôi',
    'in my room': 'trong phòng tôi',
    'in my school': 'trong trường tôi',
    'in my class': 'trong lớp tôi',
    'in my classroom': 'trong lớp tôi',
    'in my garden': 'trong vườn tôi',
    'in my backyard': 'trong sân sau nhà tôi',
    'in my city': 'trong thành phố tôi',
    'in my country': 'trong nước tôi',
    'in my town': 'trong thị trấn tôi',
    'in my village': 'trong làng tôi',
    'in my life': 'trong đời tôi',
    'in my heart': 'trong tim tôi',
    'in my mind': 'trong đầu tôi',
    'in my opinion': 'theo ý kiến tôi',
    'at my house': 'ở nhà tôi',
    'at my home': 'ở nhà tôi',
    'at my school': 'ở trường tôi',
    'at my work': 'ở nơi làm việc của tôi',
    'on my way': 'trên đường tôi',
    'on my way home': 'trên đường về nhà',
    'on my way to school': 'trên đường đi học',
    'on my way to work': 'trên đường đi làm',
    'with my friends': 'với bạn bè tôi',
    'with my family': 'với gia đình tôi',
    'with my mom': 'với mẹ tôi',
    'with my dad': 'với bố tôi',
    'with my mother': 'với mẹ tôi',
    'with my father': 'với bố tôi',
    'with my sister': 'với chị tôi',
    'with my brother': 'với anh tôi',
    'for my family': 'cho gia đình tôi',
    'for my mom': 'cho mẹ tôi',
    'for my dad': 'cho bố tôi',
    'for my mother': 'cho mẹ tôi',
    'for my father': 'cho bố tôi',
    'for my sister': 'cho chị tôi',
    'for my brother': 'cho anh tôi',
    'for my friends': 'cho bạn bè tôi',
    'for my birthday': 'cho sinh nhật tôi',
    'about my family': 'về gia đình tôi',
    'about my school': 'về trường tôi',
    'about my friends': 'về bạn bè tôi',
    'about my life': 'về cuộc sống tôi',
    'about my day': 'về ngày của tôi',
    'my best friend': 'bạn thân nhất của tôi',
    'my good friend': 'bạn tốt của tôi',
    'my old friend': 'bạn cũ của tôi',
    'my new friend': 'bạn mới của tôi',
    'my first friend': 'người bạn đầu tiên của tôi',
    'my best friends': 'những người bạn thân nhất của tôi',
    'my good friends': 'những người bạn tốt của tôi',
    'my old friends': 'những người bạn cũ của tôi',
    'my new friends': 'những người bạn mới của tôi',
    'my family': 'gia đình tôi',
    'my mom': 'mẹ tôi',
    'my dad': 'bố tôi',
    'my mother': 'mẹ tôi',
    'my father': 'bố tôi',
    'my sister': 'chị tôi',
    'my brother': 'anh tôi',
    'my parents': 'bố mẹ tôi',
    'my grandparents': 'ông bà tôi',
    'my house': 'nhà tôi',
    'my home': 'nhà tôi',
    'my room': 'phòng tôi',
    'my school': 'trường tôi',
    'my class': 'lớp tôi',
    'my classroom': 'lớp tôi',
    'my teacher': 'giáo viên tôi',
    'my friend': 'bạn tôi',
    'my friends': 'bạn bè tôi',
    'my birthday': 'sinh nhật tôi',
    'my life': 'cuộc sống tôi',
    'my day': 'ngày của tôi',
    'my name': 'tên tôi',
    'my age': 'tuổi tôi',
    'my school': 'trường tôi',
    'my work': 'công việc tôi',
    'my favorite': 'yêu thích của tôi',
    'my favourite': 'yêu thích của tôi',
    'his family': 'gia đình anh ấy',
    'his mom': 'mẹ anh ấy',
    'his dad': 'bố anh ấy',
    'his mother': 'mẹ anh ấy',
    'his father': 'bố anh ấy',
    'his sister': 'chị anh ấy',
    'his brother': 'anh em trai anh ấy',
    'his parents': 'bố mẹ anh ấy',
    'his grandparents': 'ông bà anh ấy',
    'his house': 'nhà anh ấy',
    'his home': 'nhà anh ấy',
    'his room': 'phòng anh ấy',
    'his school': 'trường anh ấy',
    'his class': 'lớp anh ấy',
    'his teacher': 'giáo viên anh ấy',
    'his friend': 'bạn anh ấy',
    'his friends': 'bạn bè anh ấy',
    'his birthday': 'sinh nhật anh ấy',
    'his life': 'cuộc sống anh ấy',
    'his name': 'tên anh ấy',
    'his age': 'tuổi anh ấy',
    'his favorite': 'yêu thích của anh ấy',
    'his work': 'công việc anh ấy',
    'her family': 'gia đình cô ấy',
    'her mom': 'mẹ cô ấy',
    'her dad': 'bố cô ấy',
    'her mother': 'mẹ cô ấy',
    'her father': 'bố cô ấy',
    'her sister': 'chị em gái cô ấy',
    'her brother': 'anh em trai cô ấy',
    'her parents': 'bố mẹ cô ấy',
    'her grandparents': 'ông bà cô ấy',
    'her house': 'nhà cô ấy',
    'her home': 'nhà cô ấy',
    'her room': 'phòng cô ấy',
    'her school': 'trường cô ấy',
    'her class': 'lớp cô ấy',
    'her teacher': 'giáo viên cô ấy',
    'her friend': 'bạn cô ấy',
    'her friends': 'bạn bè cô ấy',
    'her birthday': 'sinh nhật cô ấy',
    'her life': 'cuộc sống cô ấy',
    'her name': 'tên cô ấy',
    'her age': 'tuổi cô ấy',
    'her favorite': 'yêu thích của cô ấy',
    'her work': 'công việc cô ấy',
    'their family': 'gia đình họ',
    'their mom': 'mẹ họ',
    'their dad': 'bố họ',
    'their mother': 'mẹ họ',
    'their father': 'bố họ',
    'their sister': 'chị em gái họ',
    'their brother': 'anh em trai họ',
    'their parents': 'bố mẹ họ',
    'their grandparents': 'ông bà họ',
    'their house': 'nhà họ',
    'their home': 'nhà họ',
    'their room': 'phòng họ',
    'their school': 'trường họ',
    'their class': 'lớp họ',
    'their teacher': 'giáo viên họ',
    'their friend': 'bạn họ',
    'their friends': 'bạn bè họ',
    'their birthday': 'sinh nhật họ',
    'their life': 'cuộc sống họ',
    'their name': 'tên họ',
    'their age': 'tuổi họ',
    'their favorite': 'yêu thích của họ',
    'their work': 'công việc họ',
    'our family': 'gia đình chúng tôi',
    'our mom': 'mẹ chúng tôi',
    'our dad': 'bố chúng tôi',
    'our mother': 'mẹ chúng tôi',
    'our father': 'bố chúng tôi',
    'our sister': 'chị em gái chúng tôi',
    'our brother': 'anh em trai chúng tôi',
    'our parents': 'bố mẹ chúng tôi',
    'our grandparents': 'ông bà chúng tôi',
    'our house': 'nhà chúng tôi',
    'our home': 'nhà chúng tôi',
    'our room': 'phòng chúng tôi',
    'our school': 'trường chúng tôi',
    'our class': 'lớp chúng tôi',
    'our teacher': 'giáo viên chúng tôi',
    'our friend': 'bạn chúng tôi',
    'our friends': 'bạn bè chúng tôi',
    'our birthday': 'sinh nhật chúng tôi',
    'our life': 'cuộc sống chúng tôi',
    'our name': 'tên chúng tôi',
    'our age': 'tuổi chúng tôi',
    'our favorite': 'yêu thích của chúng tôi',
    'our work': 'công việc chúng tôi',
    'at the end of the day': 'cuối ngày',
    'at the end of the week': 'cuối tuần',
    'at the end of the month': 'cuối tháng',
    'at the end of the year': 'cuối năm',
    'in the morning of the day': 'vào buổi sáng của ngày',
    'in the evening of the day': 'vào buổi tối của ngày',
    'in the night of the day': 'vào đêm của ngày',
    'in the afternoon of the day': 'vào buổi chiều của ngày',
    'on the morning of the day': 'vào buổi sáng của ngày',
    'on the evening of the day': 'vào buổi tối của ngày',
    'on the night of the day': 'vào đêm của ngày',
    'on the afternoon of the day': 'vào buổi chiều của ngày',
}

# Apply
entries = json.loads(path.read_text())
word_to_vi = {e['word'].lower(): e for e in entries}
auto_generated_phrases = {e['word'] for e in entries if e.get('meaning','').startswith('(cụm từ:')}

fixed = 0
for phrase, vi in COMMON.items():
    if phrase in auto_generated_phrases:
        # Find entry and update
        for e in entries:
            if e['word'].lower() == phrase and e.get('meaning','').startswith('(cụm từ:'):
                e['meaning'] = vi
                e['example'] = f"The phrase '{phrase}' is commonly used in conversation."
                fixed += 1
                break

entries.sort(key=lambda e: e.get('word','').lower())
path.write_text(json.dumps(entries, ensure_ascii=False, indent=2))
Path('public/dictionary.json').write_text(path.read_text())
print(f'fixed {fixed} Vietnamese meanings')
