import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const rootDir = process.cwd();
const handoffsDir = path.join(rootDir, '.agents', 'handoffs');

if (!fs.existsSync(handoffsDir)) {
  fs.mkdirSync(handoffsDir, { recursive: true });
}

function getGitInfo() {
  try {
    const branch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
    const lastCommit = execSync('git log -n 1 --oneline', { encoding: 'utf8' }).trim();
    const status = execSync('git status --short', { encoding: 'utf8' }).trim();
    return { branch, lastCommit, status };
  } catch (err) {
    return { branch: 'unknown', lastCommit: 'none', status: 'unknown' };
  }
}

const now = new Date();
const timestampStr = now.toISOString().replace(/[:.]/g, '-');
const readableDate = now.toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });

const { branch, lastCommit, status } = getGitInfo();

// Read arguments passed from CLI or Agent if available
const userSummaryArg = process.argv.slice(2).join(' ') || '';

const template = `# 🤝 Session Handoff Report
**Date**: ${readableDate}
**Branch**: \`${branch}\`
**Latest Commit**: \`${lastCommit}\`

---

## 1. 📌 Executive Summary
${userSummaryArg ? userSummaryArg : 'Session handoff generated by Agent.'}

---

## 2. ✅ Work Completed in This Session
- **Commits & Fixes**: \`${lastCommit}\`
- **File System State**:
${status ? status.split('\n').map(s => '  - `' + s + '`').join('\n') : '  - Clean working tree (no uncommitted changes)'}

---

## 3. 🟡 Pending / Next Steps
- Continue verifying application functionality on Cloudflare / local server.
- Run \`npm run audit:week <N>\` and \`npm run build\` before making further commits.

---

## 4. 🧪 System Verification Status
- **Git Branch**: \`${branch}\`
- **Uncommitted Files**: ${status ? status.split('\n').length : 0}

---

## 🚀 Quickstart for Next Session (\`/start\`)
Run \`/start\` at the beginning of the next session to automatically load this handoff and initialize context.
`;

const latestPath = path.join(handoffsDir, 'latest_handoff.md');
const historyPath = path.join(handoffsDir, `handoff_${timestampStr}.md`);

fs.writeFileSync(latestPath, template, 'utf8');
fs.writeFileSync(historyPath, template, 'utf8');

console.log(`[Handoff] ✅ Successfully saved handoff report to:`);
console.log(`  - Latest: ${latestPath}`);
console.log(`  - Backup: ${historyPath}`);
