/**
 * apply_handcrafted_examples.mjs
 * Replaces all bad template examples with hand-written, ESL-appropriate sentences.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DICT_PATH = resolve(__dirname, '../src/data/dictionary.json');

// Hand-written by Claude — natural, child-friendly, contextual
const GOOD_EXAMPLES = {
  // B
  'ball':         'I kick the ball into the goal!',
  'bedtime':      'My bedtime is eight o\'clock.',
  'board':        'The teacher writes on the board.',
  'breakfast':    'I eat rice and eggs for breakfast.',
  'bus':          'We take the bus to school every day.',
  'car':          'Dad drives his car to work.',
  'chicken':      'We have chicken and rice for dinner.',
  'chores':       'I do my chores before I watch TV.',
  'city':         'There are tall buildings in the city.',
  'classmates':   'My classmates and I play together at break.',
  'compositions': 'We write compositions about our families.',
  'computer':     'I use the computer to do homework.',
  'countryside':  'There are green fields in the countryside.',
  'cow':          'The cow eats grass in the field.',
  'crayon':       'She draws a rainbow with her crayon.',
  'crimes':       'The detective solves crimes in the story.',
  'crystals':     'Salt forms tiny crystals when water dries.',
  'curves':       'The road curves around the mountain.',
  // D
  'darwin\'s':    'Darwin\'s ship sailed around the world.',
  // F
  'flies':        'A fly flies around the fruit bowl.',
  'flips':        'He flips the pancake in the pan.',
  'floats':       'A leaf floats on the river.',
  'floor':        'Please pick up your bag from the floor.',
  'flows':        'The river flows into the sea.',
  // G
  'galapagos':    'Darwin visited the Galapagos Islands long ago.',
  'games':        'We play games in PE class.',
  'gas':          'Water turns into gas when it boils.',
  'germinates':   'A seed germinates when it gets water and sunlight.',
  'gives':        'She gives her friend a birthday card.',
  'glass':        'She drinks water from a glass.',
  'grabs':        'He grabs his bag and runs to the bus.',
  'grains':       'Rice and wheat are types of grains.',
  'grandma\'s':   'I love eating grandma\'s cooking.',
  'grass':        'We sit on the grass in the park.',
  'groups':       'We work in groups to solve the puzzle.',
  'guides':       'The guide shows us around the museum.',
  'halves':       'She cuts the apple into two halves.',
  'heats':        'The sun heats the water in the pool.',
  'hides':        'The cat hides under the bed.',
  'hits':         'He hits the ball with a bat.',
  'hms':          'HMS Beagle was the ship Darwin sailed on.',
  'hobbies':      'My hobbies are reading and swimming.',
  'homes':        'Many animals build their homes in trees.',
  'hooks':        'Hang your bag on the hook by the door.',
  'horns':        'The cow has two long horns.',
  'horses':       'The horses run fast across the field.',
  'houses':       'There are twenty houses on our street.',
  'humanity\'s':  'Space exploration is one of humanity\'s greatest adventures.',
  'hundreds':     'Hundreds of fish swim in the river.',
  'illness':      'She stayed home because of her illness.',
  'illustrators': 'The illustrators draw the pictures in our books.',
  'interviews':   'The reporter does interviews on TV.',
  'it\'s':        'It\'s a sunny day — let\'s go to the park!',
  'journals':     'Scientists write about their discoveries in journals.',
  'kids':         'The kids run and laugh in the playground.',
  'kilometres':   'The school is two kilometres from my house.',
  'kites':        'We fly kites on windy afternoons.',
  'lakes':        'Ducks swim on the lakes in the park.',
  'lands':        'The plane lands smoothly on the runway.',
  'landscapes':   'The artist painted beautiful landscapes of mountains and rivers.',
  'leo\'s':       'Leo\'s dog is very playful.',
  'let\'s':       'Let\'s go outside and play!',
  'logs':         'We sit on logs around the campfire.',
  'london\'s':    'London\'s red buses are famous around the world.',
  'lots':         'There are lots of books in the library.',
  'lotus':        'The lotus flower opens in the morning sun.',
  'luna\'s':      'Luna\'s cat sleeps on the sofa all day.',
  'lunch':        'I eat rice and vegetables for lunch.',
  'maps':         'We look at maps to find our way.',
  'marker':       'She draws a star with a red marker.',
  'markers':      'I use markers to colour my drawing.',
  'meals':        'Our family eats three meals a day together.',
  'meteorologists': 'Meteorologists tell us if it will rain tomorrow.',
  'minutes':      'Lunch break is thirty minutes long.',
  'miss':         'I miss my friends during the holidays.',
  'molars':       'Molars at the back of your mouth help you chew.',
  'mountains':    'We can see snow on the mountains from here.',
  'ms':           'Ms. Lan is our English teacher.',
  'mysteries':    'We love reading books full of mysteries.',
  'name':         'Write your name at the top of the page.',
  'nature\'s':    'Nature\'s colours are beautiful in autumn.',
  'newspapers':   'My dad reads newspapers every morning.',
  'noises':       'The street is full of noises and traffic.',
  'obstacles':    'She jumps over the obstacles on the course.',
  'others':       'Some kids like football; others prefer swimming.',
  'outdoors':     'We spend time outdoors every afternoon.',
  'panels':       'Each comic panel tells part of the story.',
  'papers':       'The teacher gives out papers for the test.',
  'paris':        'Paris is famous for the Eiffel Tower.',
  'park':         'We play football in the park on weekends.',
  'passengers':   'The passengers wait on the platform for the train.',
  'peanuts':      'Elephants love to eat peanuts.',
  'pencil':       'She sharpens her pencil before the exam.',
  'performs':     'The dancer performs on stage every Saturday.',
  'pets':         'Many kids have pets like dogs and cats.',
  'photos':       'We take photos on the last day of school.',
  'picnics':      'Our family has picnics in the park on Sundays.',
  'pictures':     'The book has beautiful pictures on every page.',
  'planners':     'I use a planner to remember homework deadlines.',
  'planners':     'City planners design safe roads for everyone.',
  'plant\'s':     'The plant\'s leaves turn yellow without sunlight.',
  'platforms':    'We wait on the platform for the next train.',
  'players':      'The players shake hands after the match.',
  'playground':   'Children run and shout in the playground.',
  'ponds':        'Frogs and fish live in the ponds near the school.',
  'portraits':    'She painted portraits of her whole family.',
  'poster':       'There is a science poster on the classroom wall.',
  'posters':      'We made posters about recycling for Earth Day.',
  'powders':      'Baking powder makes the cake rise.',
  'precious':     'Family time is precious — enjoy every moment.',
  'predators':    'Cheetahs are fast predators that chase zebras.',
  'presentations': 'We give presentations about our projects in class.',
  'presenters':   'The presenters speak clearly into the microphone.',
  'prints':       'He prints out his homework and gives it to the teacher.',
  'process':      'Metamorphosis is the process a caterpillar goes through.',
  'programmers':  'Programmers write code to create apps and games.',
  'project':      'Our science project is about the water cycle.',
  'psychologists': 'Psychologists help people understand their feelings.',
  'releases':     'The brain releases dopamine when we feel happy.',
  'researchers':  'Researchers study animals in the rainforest.',
  'restaurant':   'We go to a restaurant to celebrate birthdays.',
  'restaurants':  'The city has many restaurants with different foods.',
  'results':      'She was happy with her exam results.',
  'rivers':       'Fish swim in the rivers and up waterfalls.',
  'robots':       'Robots in factories help build cars.',
  'rocks':        'We collected smooth rocks from the riverbank.',
  'rows':         'The desks are in straight rows in the classroom.',
  'rules':        'Follow the rules to keep everyone safe.',
  'runners':      'The runners lined up at the start of the race.',
  // S
  'satellites':   'Satellites circle the Earth and send us signals.',
  'scales':       'A fish has shiny scales on its body.',
  'scenes':       'My favourite scenes in the film are the funny ones.',
  'schools':      'Both schools are joining the sports festival.',
  'screens':      'We watch videos on our classroom screens.',
  'seasons':      'The four seasons are spring, summer, autumn, and winter.',
  'secrets':      'Best friends share secrets with each other.',
  'seeds':        'We plant seeds in soil and water them every day.',
  'senses':       'We use our five senses to explore the world.',
  'sentences':    'Write three sentences about your weekend.',
  'series':       'We\'re reading a fantasy book series in class.',
  'sets':         'The sun sets behind the mountains in the evening.',
  'shapes':       'Triangles, circles, and squares are all shapes.',
  'shelves':      'The books are neatly arranged on the shelves.',
  'ships':        'Big ships carry goods across the ocean.',
  'shops':        'Mum buys fruit at the shops near our home.',
  'signals':      'Traffic lights use colour signals to guide drivers.',
  'situations':   'In tricky situations, stay calm and think clearly.',
  'skills':       'Reading and swimming are important life skills.',
  'slides':       'She goes down the slide at the playground.',
  'snacks':       'We eat snacks like fruit and crackers at break time.',
  'songs':        'We learn new songs in music class every week.',
  'sounds':       'I hear all kinds of sounds in the forest.',
  'spaces':       'The library has quiet spaces for reading.',
  'speeds':       'Cheetahs run at incredible speeds.',
  'spots':        'A leopard has dark spots on its fur.',
  'springs':      'Water bubbles out of springs in the mountain.',
  'stations':     'We change trains at the main station.',
  'sticks':       'He glues the sticks together to make a frame.',
  'stories':      'Grandma tells us stories before bedtime.',
  'strips':       'The zebra has black and white strips — stripes!',
  'styles':       'Artists have different styles of painting.',
  'subjects':     'My favourite subjects are English and science.',
  'supplies':     'We pack school supplies in our bags.',
  'surfaces':     'Ice has a smooth, slippery surface.',
  'swings':       'She swings higher and higher in the park.',
  // T
  'tablets':      'We use tablets in class to look up information.',
  'tales':        'Fairy tales always have a happy ending.',
  'tasks':        'She finishes all her tasks before dinner.',
  'teachers':     'Our teachers help us learn every day.',
  'teammates':    'My teammates cheered when I scored a goal.',
  'techniques':   'A painter uses different techniques for different effects.',
  'tests':        'We have spelling tests every Friday.',
  'times':        'I have been to that museum three times.',
  'tools':        'Hammers and screwdrivers are tools dad uses.',
  'towns':        'The small town has a market on Saturdays.',
  'tracks':       'The train moves along the tracks.',
  'traditions':   'Our family has special traditions for New Year.',
  'trains':       'Trains carry passengers quickly from city to city.',
  'treats':       'Mum gives us healthy treats after school.',
  'tricks':       'The dog learned to do tricks like sit and roll over.',
  'trips':        'We went on two school trips this year.',
  'types':        'There are many types of clouds in the sky.',
  // U
  'uniforms':     'We wear uniforms to school every day.',
  // V
  'vegetables':   'Eat your vegetables — they keep you healthy!',
  'verbs':        '"Run", "eat", and "sleep" are action verbs.',
  'videos':       'We watch science videos in class.',
  'views':        'From the top of the hill, the views are amazing.',
  'visitors':     'The school had visitors from another country.',
  'vitamins':     'Oranges are full of vitamins that keep us well.',
  'voices':       'The choir has beautiful voices.',
  // W
  'walls':        'The children painted murals on the school walls.',
  'waves':        'The big waves crashed on the beach.',
  'weekends':     'I play football with friends on weekends.',
  'wheels':       'The bicycle has two wheels.',
  'wings':        'Birds use their wings to fly through the air.',
  'witnesses':    'The witnesses saw what happened and told the police.',
  'women':        'The women in our village grow vegetables together.',
  'woods':        'We walk through the woods to find the stream.',
  'words':        'We learn ten new words each week.',
  'workers':      'The workers build the new school playground.',
  'worlds':       'The book takes you to amazing imaginary worlds.',
  // Y
  'years':        'We have been friends for three years.',
  // Additional
  'dangerous':    'It is dangerous to run near the swimming pool.',
  'delays':       'Bad weather causes delays on the train.',
  'destinations': 'Hanoi and Ho Chi Minh City are popular travel destinations.',
  'detectives':   'Detectives look for clues to solve the mystery.',
  'digests':      'Your stomach digests food after you eat.',
  'dinner':       'We eat dinner together as a family every evening.',
  'droplets':     'Tiny water droplets form clouds in the sky.',
  'eraser':       'She uses an eraser to rub out her mistake.',
  'everyone\'s':  'It was everyone\'s favourite day of the school year.',
  'expresses':    'She expresses her feelings through painting.',
  'farm':         'The farmer grows rice and vegetables on the farm.',
  'field':        'We play football on the grass field.',
  'fingerprints': 'Everyone has unique fingerprints — no two are the same.',
  'rides':        'She rides her bike to school every morning.',
  'routines':     'Morning routines help us start the day well.',
  'ruler':        'Use a ruler to draw a straight line.',
  'rulers':       'Each student has a pencil case with pens and rulers.',
  'scientists':   'Scientists study plants, animals, and the stars.',
  'scissors':     'Cut out the shape carefully with scissors.',
  'scores':       'Our team scores three goals in one match!',
  'sequences':    'Numbers in a pattern follow a sequence.',
  'skill':        'Playing the piano is a skill that takes practice.',
  'skyscrapers':  'New York has many tall skyscrapers.',
  'slices':       'Mum cuts the watermelon into eight slices.',
  'softens':      'Warm water softens the hard bread.',
  'solves':       'The detective solves the mystery by finding clues.',
  'sports':       'My favourite sports are swimming and badminton.',
  'stars':        'We count the stars in the sky at night.',
  'store':        'We go to the store to buy milk and bread.',
  'street':       'Children should not play on a busy street.',
  'stress':       'Taking deep breaths helps when you feel stress.',
  'supermarket':  'Mum buys fruit and vegetables at the supermarket.',
  'supermarkets': 'Big supermarkets sell food from all over the world.',
  'swims':        'She swims thirty laps every morning.',
  'sydney\'s':    'Sydney\'s Harbour Bridge is a famous landmark.',
  'talent':       'She has a real talent for drawing.',
  'talents':      'Everyone has different talents — find yours!',
  'teacher\'s':   'The teacher\'s desk is at the front of the room.',
  'teenagers':    'Teenagers often enjoy music, sports, and games.',
  'teeth':        'Brush your teeth twice a day to keep them healthy.',
  'temples':      'Visitors come from far away to see the ancient temples.',
  'that\'s':      'That\'s a great idea — let\'s try it!',
  'themselves':   'The students cleaned up the classroom themselves.',
  'tickets':      'We buy tickets before we get on the train.',
  'today\'s':     'Today\'s lesson is about the water cycle.',
  'tokyo\'s':     'Tokyo\'s trains run on time every day.',
  'toothbrush':   'I use my toothbrush to clean my teeth every night.',
  'tortoises':    'Giant tortoises on the Galapagos Islands can live for 100 years.',
  'toys':         'She puts her toys away before bedtime.',
  'transfers':    'The player transfers to a new football team.',
  'tree':         'We sit under the big tree in the school garden.',
  'uncle\'s':     'Uncle\'s house has a huge garden full of flowers.',
  'vietnam\'s':   'Vietnam\'s food is delicious — try the pho!',
  'wakes':        'She wakes up at 6 a.m. to get ready for school.',
  'wall':         'There is a world map on the classroom wall.',
  'watermelons':  'We eat cold watermelons on hot summer days.',
  'what\'s':      'What\'s inside the mystery box?',
  'whiteboard':   'The teacher draws a diagram on the whiteboard.',
  'window':       'Open the window to let in the fresh air.',
  'world\'s':     'The cheetah is the world\'s fastest land animal.',
  'zoo':          'We saw lions and elephants at the zoo.',
};

function isBadExample(ex) {
  if (!ex) return true;
  return /interesting to study/i.test(ex) ||
    /important to us/i.test(ex) ||
    /important to me/i.test(ex) ||
    /good to know/i.test(ex);
}

const dictionary = JSON.parse(readFileSync(DICT_PATH, 'utf-8'));
let fixed = 0;
const stillBad = [];

for (const entry of dictionary) {
  if (!isBadExample(entry.example)) continue;
  const good = GOOD_EXAMPLES[entry.word];
  if (good) {
    entry.example = good;
    fixed++;
  } else {
    stillBad.push(entry.word);
  }
}

writeFileSync(DICT_PATH, JSON.stringify(dictionary, null, 2), 'utf-8');
console.log(`✅ Fixed: ${fixed}`);
console.log(`❌ Still needs example: ${stillBad.length}`);
if (stillBad.length) console.log(stillBad.join(', '));
