import { writeFileSync } from 'fs';

// W19 Vocabulary: 13 words (10 core + 3 extended)
// Core 6 from Syllabus: baby, cute, little, noisy, quiet, kindergarten
// Extended 7: grow, past, young, small, photo, album, memory

const vocabAdvanced = `export default {
  vocab: [
    {
      id: 1,
      word: "baby",
      pronunciation: "/ˈbeɪ.bi/",
      definition_en: "A very young child who cannot yet walk or talk",
      definition_vi: "Một đứa trẻ rất nhỏ chưa biết đi hoặc nói",
      example_en: "I was a baby when I was one year old.",
      example_vi: "Tôi là một em bé khi tôi một tuổi.",
      collocation: "baby photos, baby sister, cute baby",
      part_of_speech: "noun",
      image_url: "/images/week19/baby.jpg",
      audio_word: "/audio/week19/vocab_baby.mp3",
      audio_definition: "/audio/week19/vocab_def_baby.mp3",
      audio_example: "/audio/week19/vocab_ex_baby.mp3",
      audio_collocation: "/audio/week19/vocab_coll_baby.mp3"
    },
    {
      id: 2,
      word: "cute",
      pronunciation: "/kjuːt/",
      definition_en: "Attractive in a pretty or endearing way",
      definition_vi: "Đáng yêu, dễ thương",
      example_en: "I was very cute when I was small.",
      example_vi: "Tôi rất dễ thương khi tôi còn bé.",
      collocation: "cute smile, cute baby, very cute",
      part_of_speech: "adjective",
      image_url: "/images/week19/cute.jpg",
      audio_word: "/audio/week19/vocab_cute.mp3",
      audio_definition: "/audio/week19/vocab_def_cute.mp3",
      audio_example: "/audio/week19/vocab_ex_cute.mp3",
      audio_collocation: "/audio/week19/vocab_coll_cute.mp3"
    },
    {
      id: 3,
      word: "little",
      pronunciation: "/ˈlɪt.əl/",
      definition_en: "Small in size or young in age",
      definition_vi: "Nhỏ bé về kích thước hoặc tuổi tác",
      example_en: "I was little when I was three.",
      example_vi: "Tôi còn nhỏ khi tôi ba tuổi.",
      collocation: "little child, little sister, very little",
      part_of_speech: "adjective",
      image_url: "/images/week19/little.jpg",
      audio_word: "/audio/week19/vocab_little.mp3",
      audio_definition: "/audio/week19/vocab_def_little.mp3",
      audio_example: "/audio/week19/vocab_ex_little.mp3",
      audio_collocation: "/audio/week19/vocab_coll_little.mp3"
    },
    {
      id: 4,
      word: "noisy",
      pronunciation: "/ˈnɔɪ.zi/",
      definition_en: "Making a lot of loud sounds",
      definition_vi: "Tạo ra nhiều tiếng ồn lớn",
      example_en: "I was a noisy baby and cried a lot.",
      example_vi: "Tôi là một em bé ồn ào và hay khóc.",
      collocation: "noisy baby, very noisy, noisy children",
      part_of_speech: "adjective",
      image_url: "/images/week19/noisy.jpg",
      audio_word: "/audio/week19/vocab_noisy.mp3",
      audio_definition: "/audio/week19/vocab_def_noisy.mp3",
      audio_example: "/audio/week19/vocab_ex_noisy.mp3",
      audio_collocation: "/audio/week19/vocab_coll_noisy.mp3"
    },
    {
      id: 5,
      word: "quiet",
      pronunciation: "/ˈkwaɪ.ət/",
      definition_en: "Making little or no noise; calm and peaceful",
      definition_vi: "Ít hoặc không tạo ra tiếng ồn; yên tĩnh và ôn hòa",
      example_en: "My little brother was very quiet when he was a baby.",
      example_vi: "Em trai tôi rất yên lặng khi em ấy còn bé.",
      collocation: "quiet baby, very quiet, quiet child",
      part_of_speech: "adjective",
      image_url: "/images/week19/quiet.jpg",
      audio_word: "/audio/week19/vocab_quiet.mp3",
      audio_definition: "/audio/week19/vocab_def_quiet.mp3",
      audio_example: "/audio/week19/vocab_ex_quiet.mp3",
      audio_collocation: "/audio/week19/vocab_coll_quiet.mp3"
    },
    {
      id: 6,
      word: "kindergarten",
      pronunciation: "/ˈkɪn.dɚ.ɡɑːr.tən/",
      definition_en: "A school or class for young children, usually ages 3-5",
      definition_vi: "Một trường hoặc lớp học cho trẻ nhỏ, thường từ 3-5 tuổi",
      example_en: "I was in kindergarten when I was five years old.",
      example_vi: "Tôi học mẫu giáo khi tôi năm tuổi.",
      collocation: "attend kindergarten, kindergarten teacher, kindergarten class",
      part_of_speech: "noun",
      image_url: "/images/week19/kindergarten.jpg",
      audio_word: "/audio/week19/vocab_kindergarten.mp3",
      audio_definition: "/audio/week19/vocab_def_kindergarten.mp3",
      audio_example: "/audio/week19/vocab_ex_kindergarten.mp3",
      audio_collocation: "/audio/week19/vocab_coll_kindergarten.mp3"
    },
    {
      id: 7,
      word: "grow",
      pronunciation: "/ɡroʊ/",
      definition_en: "To increase in size or develop over time",
      definition_vi: "Tăng kích thước hoặc phát triển theo thời gian",
      example_en: "I grew bigger every year when I was small.",
      example_vi: "Tôi lớn hơn mỗi năm khi tôi còn nhỏ.",
      collocation: "grow up, grow bigger, grow tall",
      part_of_speech: "verb",
      image_url: "/images/week19/grow.jpg",
      audio_word: "/audio/week19/vocab_grow.mp3",
      audio_definition: "/audio/week19/vocab_def_grow.mp3",
      audio_example: "/audio/week19/vocab_ex_grow.mp3",
      audio_collocation: "/audio/week19/vocab_coll_grow.mp3"
    },
    {
      id: 8,
      word: "past",
      pronunciation: "/pæst/",
      definition_en: "The time before now; what happened earlier",
      definition_vi: "Thời gian trước hiện tại; điều đã xảy ra trước đó",
      example_en: "In the past, I was little and couldn't reach the table.",
      example_vi: "Trong quá khứ, tôi còn nhỏ và không với tới bàn.",
      collocation: "in the past, past time, past memories",
      part_of_speech: "noun",
      image_url: "/images/week19/past.jpg",
      audio_word: "/audio/week19/vocab_past.mp3",
      audio_definition: "/audio/week19/vocab_def_past.mp3",
      audio_example: "/audio/week19/vocab_ex_past.mp3",
      audio_collocation: "/audio/week19/vocab_coll_past.mp3"
    },
    {
      id: 9,
      word: "young",
      pronunciation: "/jʌŋ/",
      definition_en: "Being in an early stage of life; not old",
      definition_vi: "Ở giai đoạn đầu của cuộc đời; không già",
      example_en: "I was young when I learned to walk.",
      example_vi: "Tôi còn trẻ khi tôi học đi.",
      collocation: "young child, very young, young age",
      part_of_speech: "adjective",
      image_url: "/images/week19/young.jpg",
      audio_word: "/audio/week19/vocab_young.mp3",
      audio_definition: "/audio/week19/vocab_def_young.mp3",
      audio_example: "/audio/week19/vocab_ex_young.mp3",
      audio_collocation: "/audio/week19/vocab_coll_young.mp3"
    },
    {
      id: 10,
      word: "small",
      pronunciation: "/smɔːl/",
      definition_en: "Not large in size, amount, or extent",
      definition_vi: "Không lớn về kích thước, số lượng hoặc phạm vi",
      example_en: "When I was small, I was only 80 centimeters tall.",
      example_vi: "Khi tôi còn nhỏ, tôi chỉ cao 80 centimet.",
      collocation: "small child, small baby, very small",
      part_of_speech: "adjective",
      image_url: "/images/week19/small.jpg",
      audio_word: "/audio/week19/vocab_small.mp3",
      audio_definition: "/audio/week19/vocab_def_small.mp3",
      audio_example: "/audio/week19/vocab_ex_small.mp3",
      audio_collocation: "/audio/week19/vocab_coll_small.mp3"
    },
    {
      id: 11,
      word: "photo",
      pronunciation: "/ˈfoʊ.t̬oʊ/",
      definition_en: "A picture made using a camera",
      definition_vi: "Một bức ảnh được chụp bằng máy ảnh",
      example_en: "This photo shows me when I was a baby.",
      example_vi: "Bức ảnh này cho thấy tôi khi tôi còn là em bé.",
      collocation: "baby photo, old photo, take a photo",
      part_of_speech: "noun",
      image_url: "/images/week19/photo.jpg",
      audio_word: "/audio/week19/vocab_photo.mp3",
      audio_definition: "/audio/week19/vocab_def_photo.mp3",
      audio_example: "/audio/week19/vocab_ex_photo.mp3",
      audio_collocation: "/audio/week19/vocab_coll_photo.mp3"
    },
    {
      id: 12,
      word: "album",
      pronunciation: "/ˈæl.bəm/",
      definition_en: "A book for keeping photographs or other collections",
      definition_vi: "Một cuốn sách để lưu giữ ảnh hoặc bộ sưu tập khác",
      example_en: "My mom keeps my baby photos in an album.",
      example_vi: "Mẹ tôi giữ ảnh bé của tôi trong một album.",
      collocation: "photo album, baby album, family album",
      part_of_speech: "noun",
      image_url: "/images/week19/album.jpg",
      audio_word: "/audio/week19/vocab_album.mp3",
      audio_definition: "/audio/week19/vocab_def_album.mp3",
      audio_example: "/audio/week19/vocab_ex_album.mp3",
      audio_collocation: "/audio/week19/vocab_coll_album.mp3"
    },
    {
      id: 13,
      word: "memory",
      pronunciation: "/ˈmem.ɚ.i/",
      definition_en: "Something that you remember from the past",
      definition_vi: "Điều mà bạn nhớ từ quá khứ",
      example_en: "I have a memory of my first day at kindergarten.",
      example_vi: "Tôi có ký ức về ngày đầu tiên ở mẫu giáo.",
      collocation: "childhood memory, happy memory, old memory",
      part_of_speech: "noun",
      image_url: "/images/week19/memory.jpg",
      audio_word: "/audio/week19/vocab_memory.mp3",
      audio_definition: "/audio/week19/vocab_def_memory.mp3",
      audio_example: "/audio/week19/vocab_ex_memory.mp3",
      audio_collocation: "/audio/week19/vocab_coll_memory.mp3"
    }
  ]
};
`;

// Write Advanced vocab
writeFileSync('src/data/weeks/week_19/vocab.js', vocabAdvanced.trim() + '\n', 'utf8');
console.log('✅ Advanced vocab.js created (13 words)');

// Easy mode: simplified definitions
const vocabEasy = `export default {
  vocab: [
    {
      id: 1,
      word: "baby",
      pronunciation: "/ˈbeɪ.bi/",
      definition_en: "A very young child",
      definition_vi: "Một đứa trẻ rất nhỏ",
      example_en: "I was a baby.",
      example_vi: "Tôi là một em bé.",
      collocation: "baby photos",
      part_of_speech: "noun",
      image_url: "/images/week19/baby.jpg",
      audio_word: "/audio/week19/vocab_baby.mp3",
      audio_definition: "/audio/week19/vocab_def_baby.mp3",
      audio_example: "/audio/week19/vocab_ex_baby.mp3",
      audio_collocation: "/audio/week19/vocab_coll_baby.mp3"
    },
    {
      id: 2,
      word: "cute",
      pronunciation: "/kjuːt/",
      definition_en: "Very nice to look at; sweet",
      definition_vi: "Dễ thương",
      example_en: "I was very cute.",
      example_vi: "Tôi rất dễ thương.",
      collocation: "cute baby",
      part_of_speech: "adjective",
      image_url: "/images/week19/cute.jpg",
      audio_word: "/audio/week19/vocab_cute.mp3",
      audio_definition: "/audio/week19/vocab_def_cute.mp3",
      audio_example: "/audio/week19/vocab_ex_cute.mp3",
      audio_collocation: "/audio/week19/vocab_coll_cute.mp3"
    },
    {
      id: 3,
      word: "little",
      pronunciation: "/ˈlɪt.əl/",
      definition_en: "Small; young",
      definition_vi: "Nhỏ bé",
      example_en: "I was little.",
      example_vi: "Tôi còn nhỏ.",
      collocation: "little child",
      part_of_speech: "adjective",
      image_url: "/images/week19/little.jpg",
      audio_word: "/audio/week19/vocab_little.mp3",
      audio_definition: "/audio/week19/vocab_def_little.mp3",
      audio_example: "/audio/week19/vocab_ex_little.mp3",
      audio_collocation: "/audio/week19/vocab_coll_little.mp3"
    },
    {
      id: 4,
      word: "noisy",
      pronunciation: "/ˈnɔɪ.zi/",
      definition_en: "Making a lot of loud sounds",
      definition_vi: "Ồn ào",
      example_en: "I was a noisy baby.",
      example_vi: "Tôi là một em bé ồn ào.",
      collocation: "noisy baby",
      part_of_speech: "adjective",
      image_url: "/images/week19/noisy.jpg",
      audio_word: "/audio/week19/vocab_noisy.mp3",
      audio_definition: "/audio/week19/vocab_def_noisy.mp3",
      audio_example: "/audio/week19/vocab_ex_noisy.mp3",
      audio_collocation: "/audio/week19/vocab_coll_noisy.mp3"
    },
    {
      id: 5,
      word: "quiet",
      pronunciation: "/ˈkwaɪ.ət/",
      definition_en: "Making no noise; calm",
      definition_vi: "Yên tĩnh",
      example_en: "My brother was very quiet.",
      example_vi: "Em trai tôi rất yên lặng.",
      collocation: "quiet baby",
      part_of_speech: "adjective",
      image_url: "/images/week19/quiet.jpg",
      audio_word: "/audio/week19/vocab_quiet.mp3",
      audio_definition: "/audio/week19/vocab_def_quiet.mp3",
      audio_example: "/audio/week19/vocab_ex_quiet.mp3",
      audio_collocation: "/audio/week19/vocab_coll_quiet.mp3"
    },
    {
      id: 6,
      word: "kindergarten",
      pronunciation: "/ˈkɪn.dɚ.ɡɑːr.tən/",
      definition_en: "A school for young children",
      definition_vi: "Trường mẫu giáo",
      example_en: "I was in kindergarten.",
      example_vi: "Tôi học mẫu giáo.",
      collocation: "kindergarten class",
      part_of_speech: "noun",
      image_url: "/images/week19/kindergarten.jpg",
      audio_word: "/audio/week19/vocab_kindergarten.mp3",
      audio_definition: "/audio/week19/vocab_def_kindergarten.mp3",
      audio_example: "/audio/week19/vocab_ex_kindergarten.mp3",
      audio_collocation: "/audio/week19/vocab_coll_kindergarten.mp3"
    },
    {
      id: 7,
      word: "grow",
      pronunciation: "/ɡroʊ/",
      definition_en: "To get bigger",
      definition_vi: "Lớn lên",
      example_en: "I grew bigger.",
      example_vi: "Tôi lớn hơn.",
      collocation: "grow up",
      part_of_speech: "verb",
      image_url: "/images/week19/grow.jpg",
      audio_word: "/audio/week19/vocab_grow.mp3",
      audio_definition: "/audio/week19/vocab_def_grow.mp3",
      audio_example: "/audio/week19/vocab_ex_grow.mp3",
      audio_collocation: "/audio/week19/vocab_coll_grow.mp3"
    },
    {
      id: 8,
      word: "past",
      pronunciation: "/pæst/",
      definition_en: "The time before now",
      definition_vi: "Quá khứ",
      example_en: "In the past, I was little.",
      example_vi: "Trong quá khứ, tôi còn nhỏ.",
      collocation: "in the past",
      part_of_speech: "noun",
      image_url: "/images/week19/past.jpg",
      audio_word: "/audio/week19/vocab_past.mp3",
      audio_definition: "/audio/week19/vocab_def_past.mp3",
      audio_example: "/audio/week19/vocab_ex_past.mp3",
      audio_collocation: "/audio/week19/vocab_coll_past.mp3"
    },
    {
      id: 9,
      word: "young",
      pronunciation: "/jʌŋ/",
      definition_en: "Not old",
      definition_vi: "Trẻ",
      example_en: "I was young.",
      example_vi: "Tôi còn trẻ.",
      collocation: "young child",
      part_of_speech: "adjective",
      image_url: "/images/week19/young.jpg",
      audio_word: "/audio/week19/vocab_young.mp3",
      audio_definition: "/audio/week19/vocab_def_young.mp3",
      audio_example: "/audio/week19/vocab_ex_young.mp3",
      audio_collocation: "/audio/week19/vocab_coll_young.mp3"
    },
    {
      id: 10,
      word: "small",
      pronunciation: "/smɔːl/",
      definition_en: "Not big",
      definition_vi: "Nhỏ",
      example_en: "I was small.",
      example_vi: "Tôi còn nhỏ.",
      collocation: "small child",
      part_of_speech: "adjective",
      image_url: "/images/week19/small.jpg",
      audio_word: "/audio/week19/vocab_small.mp3",
      audio_definition: "/audio/week19/vocab_def_small.mp3",
      audio_example: "/audio/week19/vocab_ex_small.mp3",
      audio_collocation: "/audio/week19/vocab_coll_small.mp3"
    },
    {
      id: 11,
      word: "photo",
      pronunciation: "/ˈfoʊ.t̬oʊ/",
      definition_en: "A picture from a camera",
      definition_vi: "Ảnh",
      example_en: "This is my baby photo.",
      example_vi: "Đây là ảnh bé của tôi.",
      collocation: "baby photo",
      part_of_speech: "noun",
      image_url: "/images/week19/photo.jpg",
      audio_word: "/audio/week19/vocab_photo.mp3",
      audio_definition: "/audio/week19/vocab_def_photo.mp3",
      audio_example: "/audio/week19/vocab_ex_photo.mp3",
      audio_collocation: "/audio/week19/vocab_coll_photo.mp3"
    },
    {
      id: 12,
      word: "album",
      pronunciation: "/ˈæl.bəm/",
      definition_en: "A book for keeping photos",
      definition_vi: "Album ảnh",
      example_en: "My mom has a photo album.",
      example_vi: "Mẹ tôi có một album ảnh.",
      collocation: "photo album",
      part_of_speech: "noun",
      image_url: "/images/week19/album.jpg",
      audio_word: "/audio/week19/vocab_album.mp3",
      audio_definition: "/audio/week19/vocab_def_album.mp3",
      audio_example: "/audio/week19/vocab_ex_album.mp3",
      audio_collocation: "/audio/week19/vocab_coll_album.mp3"
    },
    {
      id: 13,
      word: "memory",
      pronunciation: "/ˈmem.ɚ.i/",
      definition_en: "Something you remember",
      definition_vi: "Ký ức",
      example_en: "I have a happy memory.",
      example_vi: "Tôi có một ký ức vui.",
      collocation: "happy memory",
      part_of_speech: "noun",
      image_url: "/images/week19/memory.jpg",
      audio_word: "/audio/week19/vocab_memory.mp3",
      audio_definition: "/audio/week19/vocab_def_memory.mp3",
      audio_example: "/audio/week19/vocab_ex_memory.mp3",
      audio_collocation: "/audio/week19/vocab_coll_memory.mp3"
    }
  ]
};
`;

writeFileSync('src/data/weeks_easy/week_19/vocab.js', vocabEasy.trim() + '\n', 'utf8');
console.log('✅ Easy vocab.js created (13 words, simplified)');
console.log('');
console.log('=== VALIDATION ===');
