#!/usr/bin/env node
/**
 * REAL COLLOCATION GENERATOR
 * Uses natural, child-friendly collocations like real dictionaries
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DICT_PATH = path.join(__dirname, '../src/data/dictionary.json');

/**
 * REAL COLLOCATION DATABASE - Natural examples like dictionaries use
 */
function generateRealExample(entry) {
  const { word, meaning, first_taught_week, definition_en } = entry;
  const w = word.toLowerCase();
  const week = first_taught_week || 15;
  
  // ═══════════════════════════════════════════════════════════════════════
  // LEVEL 1: NATURAL COLLOCATIONS (1000+ real examples)
  // ═══════════════════════════════════════════════════════════════════════
  
  const realExamples = {
    // Common adjectives - natural collocations
    'short': 'She has short hair.',
    'straight': 'My sister has straight hair.',
    'curly': 'He has curly brown hair.',
    'long': 'My mother has very long hair.',
    'tall': 'My father is very tall.',
    'big': 'We live in a big house.',
    'small': 'I have a small dog.',
    'good': 'She is a good student.',
    'bad': 'That was a bad dream.',
    'happy': 'I am happy today.',
    'sad': 'Why are you so sad?',
    'angry': 'My teacher is angry with me.',
    'excited': 'The children are very excited about the trip.',
    'tired': 'I am tired after school.',
    'hungry': 'Are you hungry yet?',
    'thirsty': 'I am very thirsty now.',
    'funny': 'That was a funny joke.',
    'cute': 'What a cute baby!',
    'beautiful': 'She looks beautiful in that dress.',
    'ugly': 'The monster in the movie was ugly.',
    'fast': 'He can run very fast.',
    'slow': 'The turtle walks very slow.',
    'hot': 'Today is very hot.',
    'cold': 'The water is too cold.',
    'warm': 'The soup is warm and delicious.',
    'cool': 'The evening air feels cool.',
    'new': 'I got a new bike for my birthday.',
    'old': 'My grandfather is getting old.',
    'young': 'She is too young to go alone.',
    'clean': 'Please keep your room clean.',
    'dirty': 'Your hands are very dirty.',
    'full': 'The glass is full of water.',
    'empty': 'The box is empty now.',
    'easy': 'The test was very easy.',
    'difficult': 'This math problem is difficult.',
    'hard': 'The rock is very hard.',
    'soft': 'The pillow is soft and comfortable.',
    'loud': 'The music is too loud.',
    'quiet': 'Please be quiet in the library.',
    'busy': 'My mother is always busy.',
    'free': 'Are you free this afternoon?',
    'ready': 'I am ready to go now.',
    'late': 'Don\'t be late for school.',
    'early': 'I wake up early every morning.',
    
    // Colors
    'black': 'I have black shoes.',
    'white': 'She is wearing a white dress.',
    'red': 'I like red apples.',
    'blue': 'The sky is blue today.',
    'green': 'The grass is green.',
    'yellow': 'The sun is yellow.',
    'brown': 'My dog has brown fur.',
    'pink': 'She loves pink flowers.',
    'purple': 'He has a purple backpack.',
    'orange': 'Can I have an orange juice?',
    'gray': 'The elephant is gray.',
    
    // Body parts
    'head': 'I hit my head on the door.',
    'hair': 'She brushes her hair every day.',
    'face': 'Wash your face before breakfast.',
    'eyes': 'She has beautiful brown eyes.',
    'ear': 'I can hear with my ears.',
    'ears': 'The rabbit has long ears.',
    'nose': 'My nose is running.',
    'mouth': 'Open your mouth and say "Ah".',
    'tooth': 'I lost a tooth yesterday.',
    'teeth': 'Brush your teeth twice a day.',
    'hand': 'Hold my hand when we cross the street.',
    'hands': 'Wash your hands before eating.',
    'finger': 'I hurt my finger.',
    'fingers': 'She has ten fingers.',
    'arm': 'He broke his arm playing soccer.',
    'arms': 'She crossed her arms.',
    'leg': 'I hurt my leg running.',
    'legs': 'The table has four legs.',
    'foot': 'My foot hurts.',
    'feet': 'Take off your shoes and rest your feet.',
    'knee': 'I fell and hurt my knee.',
    'knees': 'Get down on your knees.',
    'shoulder': 'She tapped me on the shoulder.',
    'shoulders': 'He shrugged his shoulders.',
    'back': 'My back hurts from sitting.',
    'stomach': 'I have a stomach ache.',
    'heart': 'My heart beats fast when I run.',
    
    // Family
    'mother': 'My mother makes breakfast every day.',
    'mom': 'Mom, can I go outside?',
    'father': 'My father goes to work early.',
    'dad': 'Dad is reading the newspaper.',
    'parent': 'Ask your parent for permission.',
    'parents': 'My parents are very kind.',
    'sister': 'My sister is in high school.',
    'brother': 'My little brother is five years old.',
    'grandmother': 'Grandmother tells us bedtime stories.',
    'grandma': 'Grandma bakes the best cookies.',
    'grandfather': 'Grandfather takes us fishing.',
    'grandpa': 'Grandpa taught me how to ride a bike.',
    'aunt': 'Aunt Mary is coming to visit.',
    'uncle': 'Uncle John works in a hospital.',
    'cousin': 'My cousin lives in another city.',
    'baby': 'The baby is sleeping now.',
    'child': 'Every child needs love and care.',
    'children': 'The children are playing in the park.',
    'boy': 'That boy is my classmate.',
    'girl': 'The girl in the red dress is my friend.',
    'friend': 'She is my best friend.',
    'friends': 'I play with my friends every day.',
    
    // Home & furniture
    'home': 'I go straight home after school.',
    'house': 'We live in a small house.',
    'room': 'My room is upstairs.',
    'bedroom': 'I sleep in my bedroom.',
    'bathroom': 'The bathroom is next to the kitchen.',
    'kitchen': 'Mom is cooking in the kitchen.',
    'living room': 'We watch TV in the living room.',
    'door': 'Please close the door.',
    'window': 'Open the window for fresh air.',
    'floor': 'The toy is on the floor.',
    'ceiling': 'There is a fan on the ceiling.',
    'wall': 'Hang the picture on the wall.',
    'table': 'Put the book on the table.',
    'chair': 'Sit down on this chair.',
    'bed': 'Make your bed every morning.',
    'desk': 'I do homework at my desk.',
    'sofa': 'Dad is sitting on the sofa.',
    'cabinet': 'The dishes are in the cabinet.',
    'shelf': 'Put the books on the shelf.',
    'mirror': 'I look in the mirror every morning.',
    'lamp': 'Turn on the lamp, please.',
    'clock': 'The clock says it\'s 3 o\'clock.',
    'fridge': 'The milk is in the fridge.',
    'refrigerator': 'Keep the food in the refrigerator.',
    
    // School
    'school': 'I walk to school every day.',
    'class': 'My class starts at 8 am.',
    'classroom': 'Our classroom is on the second floor.',
    'teacher': 'My teacher is very nice.',
    'student': 'She is a good student.',
    'students': 'The students are studying quietly.',
    'book': 'I am reading an interesting book.',
    'books': 'I have many books at home.',
    'pen': 'Can I borrow your pen?',
    'pencil': 'I write with a pencil.',
    'notebook': 'Write the answer in your notebook.',
    'bag': 'My school bag is heavy.',
    'backpack': 'I carry my backpack to school.',
    'homework': 'I have a lot of homework today.',
    'test': 'We have a math test tomorrow.',
    'lesson': 'Today\'s lesson is about animals.',
    'subject': 'English is my favorite subject.',
    
    // Actions - infinitive form ONLY
    'walk': 'I walk to school.',
    'run': 'I can run fast.',
    'jump': 'Can you jump high?',
    'sit': 'Please sit down here.',
    'stand': 'Stand up when the teacher comes in.',
    'play': 'Let\'s play soccer after school.',
    'eat': 'We eat dinner at 6 pm.',
    'drink': 'Don\'t forget to drink water.',
    'sleep': 'I need to sleep early tonight.',
    'wake': 'I wake up at 7 am.',
    'get': 'What did you get for your birthday?',
    'go': 'Where do you want to go?',
    'come': 'Come here, please.',
    'bring': 'Bring your book to class.',
    'take': 'Take this medicine twice a day.',
    'give': 'Give me the ball, please.',
    'help': 'Can you help me with this?',
    'make': 'Let\'s make a cake together.',
    'do': 'What are you doing now?',
    'read': 'I like to read before bed.',
    'write': 'Write your name here.',
    'draw': 'She loves to draw pictures.',
    'paint': 'He can paint very well.',
    'sing': 'Can you sing this song?',
    'dance': 'She loves to dance.',
    'cook': 'My mom cooks delicious food.',
    'clean': 'I clean my room every weekend.',
    'wash': 'Wash the dishes after dinner.',
    'wear': 'What should I wear today?',
    'put': 'Put your toys away.',
    'open': 'Open your book to page 10.',
    'close': 'Close the door quietly.',
    'start': 'Let\'s start the game now.',
    'stop': 'Stop running in the hallway.',
    'finish': 'Finish your homework first.',
    'show': 'Show me your drawing.',
    'tell': 'Tell me a story.',
    'say': 'What did she say?',
    'talk': 'Don\'t talk during class.',
    'speak': 'Can you speak English?',
    'listen': 'Listen to the teacher carefully.',
    'hear': 'I can hear someone singing.',
    'see': 'I can see the mountains from here.',
    'look': 'Look at this picture.',
    'watch': 'I watch cartoons on weekends.',
    'feel': 'I don\'t feel well today.',
    'think': 'I think it will rain tomorrow.',
    'know': 'I know the answer to this question.',
    'learn': 'I want to learn how to swim.',
    'study': 'I study English every day.',
    'teach': 'Can you teach me how to ride a bike?',
    'understand': 'I don\'t understand this word.',
    'remember': 'I can\'t remember his name.',
    'forget': 'Don\'t forget your lunch.',
    'love': 'I love my family very much.',
    'like': 'I like ice cream.',
    'want': 'I want a new bike.',
    'need': 'I need help with my work.',
    'have': 'I have a pet dog.',
    'live': 'Where do you live?',
    'work': 'My father works in an office.',
    'buy': 'Mom will buy some fruit.',
    'sell': 'They sell fresh vegetables.',
    'find': 'I can\'t find my keys.',
    'lose': 'Don\'t lose your wallet.',
    'win': 'Our team will win the game.',
    'try': 'Try your best on the test.',
    'use': 'Can I use your pencil?',
    'wait': 'Wait for me here.',
    'meet': 'Nice to meet you.',
    'visit': 'We will visit grandma this weekend.',
    'call': 'Call me when you get home.',
    'answer': 'Please answer my question.',
    'ask': 'Don\'t be afraid to ask questions.',
    'cry': 'The baby started to cry.',
    'laugh': 'The joke made everyone laugh.',
    'smile': 'She has a beautiful smile.',
    'grow': 'Plants need water to grow.',
    'change': 'People change over time.',
    'move': 'Don\'t move, I\'ll take a picture.',
    'turn': 'Turn left at the corner.',
    'push': 'Push the door to open it.',
    'pull': 'Pull the rope harder.',
    'throw': 'Don\'t throw stones at birds.',
    'catch': 'Can you catch the ball?',
    'hold': 'Hold my hand tight.',
    'touch': 'Don\'t touch the hot stove.',
    'carry': 'Can you help me carry these books?',
    'lift': 'This box is too heavy to lift.',
    'break': 'Be careful not to break the glass.',
    'cut': 'Cut the paper along the line.',
    'build': 'They will build a new school.',
    'fix': 'Dad can fix the broken chair.',
    
    // Greetings & common phrases
    'hello': 'Hello, how are you?',
    'hi': 'Hi, nice to see you!',
    'bye': 'Bye, see you tomorrow!',
    'goodbye': 'Goodbye, have a safe trip!',
    'please': 'Can I have more water, please?',
    'thanks': 'Thanks for your help!',
    'thank': 'I want to thank you.',
    'sorry': 'I am sorry I am late.',
    'yes': 'Yes, I agree with you.',
    'no': 'No, I don\'t want to go.',
    'okay': 'Okay, let\'s do it.',
    
    // Time
    'day': 'Have a nice day!',
    'night': 'Good night, sleep well.',
    'morning': 'I exercise every morning.',
    'afternoon': 'I will see you this afternoon.',
    'evening': 'We eat dinner in the evening.',
    'today': 'What day is today?',
    'tomorrow': 'I have a test tomorrow.',
    'yesterday': 'It rained yesterday.',
    'week': 'I see my grandparents every week.',
    'month': 'My birthday is next month.',
    'year': 'I am ten years old this year.',
    'time': 'What time is it now?',
    'hour': 'I study for one hour every day.',
    'minute': 'Wait a minute, please.',
    'second': 'Just give me a second.',
    
    // Places
    'park': 'We go to the park on Sundays.',
    'playground': 'The children are at the playground.',
    'garden': 'My mom grows flowers in the garden.',
    'street': 'Don\'t play in the street.',
    'road': 'Look both ways before crossing the road.',
    'city': 'I live in a big city.',
    'town': 'This is a small quiet town.',
    'country': 'I love my country.',
    'place': 'This is my favorite place.',
    'library': 'I borrow books from the library.',
    'hospital': 'My aunt works at the hospital.',
    'store': 'We buy food at the store.',
    'shop': 'Let\'s go to the toy shop.',
    'market': 'The market is very crowded today.',
    'restaurant': 'We eat dinner at a restaurant.',
    
    // Food & drink
    'food': 'I love Chinese food.',
    'water': 'Drink plenty of water every day.',
    'milk': 'I drink milk for breakfast.',
    'juice': 'Can I have some orange juice?',
    'tea': 'Would you like some tea?',
    'coffee': 'My dad drinks coffee every morning.',
    'rice': 'We eat rice with every meal.',
    'bread': 'I had bread and jam for breakfast.',
    'cake': 'The birthday cake looks delicious.',
    'cookie': 'May I have a cookie?',
    'fruit': 'Eat fruit every day to stay healthy.',
    'apple': 'An apple a day keeps the doctor away.',
    'banana': 'Monkeys love to eat bananas.',
    'orange': 'This orange tastes very sweet.',
    'meat': 'I don\'t eat much meat.',
    'fish': 'Fish is good for your brain.',
    'chicken': 'We are having chicken for dinner.',
    'egg': 'I eat one egg every morning.',
    'vegetable': 'Eat your vegetables!',
    'pizza': 'Pizza is my favorite food.',
    'sandwich': 'I made a sandwich for lunch.',
    'soup': 'The soup is too hot to eat.',
    'salt': 'This needs a little more salt.',
    'sugar': 'Too much sugar is bad for your teeth.',
    
    // Animals
    'animal': 'What is your favorite animal?',
    'dog': 'I have a pet dog.',
    'cat': 'The cat is sleeping on the sofa.',
    'bird': 'I can hear birds singing.',
    'fish': 'There are many fish in the pond.',
    'rabbit': 'The rabbit is eating a carrot.',
    'mouse': 'The mouse ran away quickly.',
    'elephant': 'The elephant is the largest land animal.',
    'lion': 'The lion is the king of the jungle.',
    'tiger': 'Tigers are endangered animals.',
    'bear': 'Bears sleep through the winter.',
    'monkey': 'The monkey is swinging from tree to tree.',
    'horse': 'I learned to ride a horse last summer.',
    'cow': 'Cows give us milk.',
    'pig': 'The three little pigs built houses.',
    'sheep': 'Sheep have soft wool.',
    'duck': 'The ducks are swimming in the pond.',
    'chicken': 'The hen laid an egg.',
    
    // Weather
    'weather': 'The weather is nice today.',
    'sun': 'The sun is shining brightly.',
    'sunny': 'It is sunny and warm.',
    'rain': 'I think it will rain soon.',
    'rainy': 'It\'s a rainy day today.',
    'snow': 'Children love to play in the snow.',
    'snowy': 'It\'s cold and snowy outside.',
    'wind': 'The wind is blowing hard.',
    'windy': 'It\'s too windy to fly a kite.',
    'cloud': 'There are dark clouds in the sky.',
    'cloudy': 'It looks cloudy today.',
    'storm': 'There was a big storm last night.',
    'sky': 'Look at the beautiful blue sky.',
    
    // Transportation
    'car': 'My dad drives a blue car.',
    'bus': 'I take the bus to school.',
    'train': 'The train arrives at 9 o\'clock.',
    'bike': 'I got a new bike for my birthday.',
    'bicycle': 'Riding a bicycle is fun.',
    'airplane': 'The airplane is flying high.',
    'boat': 'We went on a boat ride.',
    'ship': 'The big ship sailed across the ocean.',
    
    // Clothing
    'clothes': 'Put on some warm clothes.',
    'shirt': 'He is wearing a blue shirt.',
    'pants': 'These pants are too long.',
    'dress': 'She looks pretty in that dress.',
    'skirt': 'The girl is wearing a short skirt.',
    'coat': 'Wear your coat, it\'s cold outside.',
    'jacket': 'I need a warm jacket.',
    'shoes': 'My shoes are getting old.',
    'socks': 'I need to buy new socks.',
    'hat': 'Wear a hat in the sun.',
    'cap': 'He always wears a baseball cap.',
    'scarf': 'Wrap this scarf around your neck.',
    'gloves': 'My hands are cold, I need gloves.',
    
    // Numbers & quantities
    'one': 'I have one brother.',
    'two': 'There are two apples on the table.',
    'three': 'The story is about three little pigs.',
    'many': 'There are many stars in the sky.',
    'some': 'Would you like some water?',
    'all': 'All students must wear uniforms.',
    'more': 'Can I have some more juice?',
    'most': 'Most children like chocolate.',
    'few': 'Only a few people came.',
    'little': 'I have a little money left.',
    'much': 'How much does it cost?',
    
    // Prepositions with natural contexts
    'in': 'The toys are in the box.',
    'on': 'The book is on the table.',
    'at': 'I am at school now.',
    'to': 'I go to bed at 9 pm.',
    'from': 'I am from Vietnam.',
    'for': 'This gift is for you.',
    'with': 'I live with my family.',
    'about': 'Tell me about your day.',
    'above': 'The birds are flying above us.',
    'under': 'The cat is hiding under the bed.',
    'between': 'I sit between Tom and Mary.',
    'behind': 'The ball is behind the door.',
    'next': 'Come sit next to me.',
    'near': 'The school is near my house.',
    'far': 'Is your house far from here?',
    'inside': 'Come inside, it\'s raining.',
    'outside': 'The children are playing outside.',
    'up': 'Go up the stairs.',
    'down': 'Come down from there!',
    'over': 'The bridge goes over the river.',
    'around': 'Let\'s walk around the lake.',
    'through': 'We walked through the forest.',
    'across': 'Look both ways before crossing across the street.',
    'into': 'Put the books into your bag.',
    'out': 'Take the trash out.',
    'off': 'Turn off the lights when you leave.',
    'along': 'We walked along the beach.',
    'past': 'We walked past the school.',
    'toward': 'He walked toward the door.',
    'until': 'Wait here until I come back.',
    'during': 'I fell asleep during the movie.',
    'before': 'Wash your hands before eating.',
    'after': 'We will play after we finish homework.',
    'since': 'I have known her since kindergarten.',
    
    // Pronouns in context
    'I': 'I am a student.',
    'you': 'How old are you?',
    'he': 'He is my brother.',
    'she': 'She is very kind.',
    'it': 'It is a beautiful day.',
    'we': 'We are going to the park.',
    'they': 'They are my classmates.',
    'me': 'Can you help me?',
    'him': 'I gave him a present.',
    'her': 'This is her book.',
    'us': 'Come with us!',
    'them': 'I saw them at the park.',
    'my': 'This is my favorite book.',
    'your': 'Is this your pencil?',
    'his': 'That is his backpack.',
    'our': 'This is our classroom.',
    'their': 'Their house is very big.',
    
    // Common verbs - simple collocations
    'be': 'I want to be a teacher.',
    'am': 'I am happy today.',
    'is': 'She is my best friend.',
    'are': 'We are learning English.',
    'was': 'I was sick yesterday.',
    'were': 'They were late for class.',
    'can': 'I can swim very well.',
    'will': 'I will help you tomorrow.',
    'would': 'I would like some water.',
    'should': 'You should study harder.',
    'must': 'You must wear a helmet.',
    
    // Activities (-ing forms for ESL children)
    'swimming': 'Swimming is my favorite sport.',
    'running': 'Running is good exercise.',
    'walking': 'I like walking to school.',
    'jogging': 'My dad goes jogging every morning.',
    'sitting': 'He is sitting on a chair.',
    'standing': 'She is standing near the door.',
    'dancing': 'She is taking dancing lessons.',
    'singing': 'I love singing in the shower.',
    'playing': 'The children are playing outside.',
    'eating': 'Healthy eating is important.',
    'drinking': 'She is drinking water.',
    'sleeping': 'The baby is sleeping.',
    'reading': 'Reading books helps you learn.',
    'writing': 'I enjoy writing stories.',
    'drawing': 'He is good at drawing.',
    'painting': 'Painting is a relaxing hobby.',
    'cooking': 'My mom is busy cooking dinner.',
    'flying': 'They are flying colorful kites.',
    'relaxing': 'I am relaxing at home.',
    'listening': 'She is listening to music.',
    'watching': 'We are watching TV.',
    'wearing': 'She is wearing a dress.',
    'splashing': 'The kids are splashing in the pool.',
    'laughing': 'Everyone is laughing at the joke.',
    'crying': 'The baby is crying.',
    'smiling': 'She is smiling happily.',
    'talking': 'They are talking loudly.',
    'speaking': 'He is speaking English.',
    'studying': 'I am studying for the test.',
    'learning': 'Learning new things is fun.',
    'teaching': 'She is teaching math.',
    'helping': 'He is helping his mother.',
    'working': 'Dad is working late tonight.',
    'shopping': 'Mom is shopping for food.',
    'cleaning': 'I am cleaning my room.',
    'washing': 'She is washing the dishes.',
    'jumping': 'The children are jumping rope.',
    'climbing': 'He is climbing a tree.',
    'riding': 'I am riding my bike.',
    'driving': 'My dad is driving the car.',
    'having': 'We are having a good time.',
    
    // Emotions & states
    'feeling': 'How are you feeling today?',
    'thought': 'That\'s a good thought!',
    'idea': 'I have an idea!',
    'question': 'Can I ask you a question?',
    'answer': 'I know the answer.',
    'problem': 'Let\'s solve this problem together.',
    'plan': 'What is your plan for the weekend?',
    'dream': 'I had a strange dream last night.',
    
    // Misc common words
    'thing': 'What is that thing?',
    'people': 'Many people came to the party.',
    'person': 'She is a nice person.',
    'name': 'What is your name?',
    'way': 'This is the best way to do it.',
    'example': 'Let me give you an example.',
    'story': 'Grandma tells us bedtime stories.',
    'word': 'What does this word mean?',
    'picture': 'Draw a picture of your family.',
    'sound': 'What was that sound?',
    'color': 'What is your favorite color?',
    'shape': 'What shape is this?',
    'size': 'What size do you wear?',
    'kind': 'What kind of music do you like?',
    'number': 'What is your phone number?',
    'letter': 'A is the first letter of the alphabet.',
    
    // ═══════════════════════════════════════════════════════════════════════
    // EXTENDED: Common words with no data (adverbs, plurals, misc)
    // ═══════════════════════════════════════════════════════════════════════
    
    // Adverbs
    'actually': 'Actually, I don\'t know the answer.',
    'again': 'Can you say that again?',
    'ago': 'I saw him two days ago.',
    'ahead': 'Go ahead, I\'ll wait here.',
    'almost': 'I almost forgot my homework!',
    'also': 'I can also speak English.',
    'always': 'She always arrives on time.',
    'another': 'Can I have another cookie?',
    'anyway': 'I don\'t like it, but I\'ll try anyway.',
    'apart': 'We live far apart now.',
    'around': 'Let\'s walk around the park.',
    'away': 'Please go away and leave me alone.',
    'back': 'I\'ll be back in five minutes.',
    'besides': 'Besides math, I also like science.',
    'both': 'Both of my parents work.',
    'completely': 'I completely forgot about the meeting.',
    'correctly': 'Did I spell it correctly?',
    'daily': 'I brush my teeth daily.',
    'deeply': 'She cares deeply about animals.',
    'directly': 'Go directly home after school.',
    'else': 'What else do you need?',
    'enough': 'Have you had enough to eat?',
    'especially': 'I love fruits, especially apples.',
    'eventually': 'We will arrive eventually.',
    'ever': 'Have you ever been to Paris?',
    'everywhere': 'I looked everywhere but couldn\'t find it.',
    'exactly': 'That\'s exactly what I wanted!',
    'extremely': 'The weather is extremely hot today.',
    'fairly': 'She did fairly well on the test.',
    'finally': 'We finally arrived at the beach.',
    'forward': 'I look forward to seeing you.',
    'gently': 'Hold the baby gently.',
    'hard': 'She works very hard.',
    'here': 'Come here, please.',
    'however': 'I\'m tired; however, I must finish my work.',
    'immediately': 'Come home immediately!',
    'indeed': 'That is indeed a good idea.',
    'instead': 'Let\'s play outside instead.',
    'just': 'I just finished my homework.',
    'lately': 'Have you seen her lately?',
    'later': 'I\'ll call you later.',
    'least': 'At least try your best.',
    'less': 'I want less sugar in my tea.',
    'likely': 'It will likely rain tomorrow.',
    'maybe': 'Maybe we can go tomorrow.',
    'meanwhile': 'You cook dinner; meanwhile, I\'ll set the table.',
    'more': 'I need more time.',
    'mostly': 'I mostly eat vegetables.',
    'never': 'I never eat breakfast.',
    'newly': 'This is our newly painted room.',
    'next': 'What happens next?',
    'normally': 'I normally wake up at 7 am.',
    'now': 'We need to leave now.',
    'nowhere': 'I have nowhere to go.',
    'obviously': 'Obviously, she is very talented.',
    'often': 'I often visit my grandparents.',
    'once': 'I go swimming once a week.',
    'only': 'I only have one pencil.',
    'perhaps': 'Perhaps we should wait.',
    'personally': 'Personally, I prefer tea over coffee.',
    'possibly': 'Could you possibly help me?',
    'probably': 'It will probably rain later.',
    'quickly': 'Run quickly, we\'re late!',
    'quietly': 'Please speak quietly in the library.',
    'quite': 'The movie was quite interesting.',
    'rarely': 'I rarely eat fast food.',
    'rather': 'I would rather stay home.',
    'really': 'I really like ice cream.',
    'recently': 'I saw him recently at the store.',
    'seldom': 'She seldom goes out.',
    'shortly': 'The bus will arrive shortly.',
    'slowly': 'The turtle moves very slowly.',
    'somehow': 'I will finish this somehow.',
    'sometimes': 'Sometimes I feel sad.',
    'somewhere': 'I left my keys somewhere.',
    'soon': 'Dinner will be ready soon.',
    'still': 'Are you still hungry?',
    'suddenly': 'Suddenly, the lights went out.',
    'there': 'Put the book over there.',
    'therefore': 'I studied hard; therefore, I passed.',
    'together': 'Let\'s work together.',
    'too': 'This box is too heavy.',
    'totally': 'I totally forgot about that!',
    'truly': 'I am truly sorry.',
    'twice': 'I exercise twice a week.',
    'unfortunately': 'Unfortunately, we lost the game.',
    'usually': 'I usually walk to school.',
    'very': 'The test was very difficult.',
    'well': 'She sings very well.',
    'whenever': 'Call me whenever you need help.',
    'wherever': 'I\'ll follow you wherever you go.',
    'yet': 'I haven\'t finished yet.',
    
    // Plural nouns
    'abilities': 'Everyone has different abilities.',
    'actions': 'Our actions have consequences.',
    'activities': 'We have many activities after school.',
   'adults': 'Adults and children entered the museum.',
    'adventures': 'I love reading about adventures.',
    'airports': 'Big cities have multiple airports.',
    'ages': 'People of all ages can learn.',
    'amounts': 'We need large amounts of water.',
    'ancestors': 'My ancestors came from Europe.',
    'angles': 'This triangle has three angles.',
    'areas': 'Some areas of the city are very crowded.',
    'articles': 'I read interesting articles online.',
    'atoms': 'Everything is made of tiny atoms.',
    'attempts': 'After several attempts, I finally succeeded.',
    'batteries': 'The toy needs new batteries.',
    'battles': 'History books describe many famous battles.',
    'beaches': 'We visited several beautiful beaches.',
    'beliefs': 'People have different beliefs.',
    'benefits': 'Exercise has many health benefits.',
    'beings': 'We must respect all living beings.',
    'bones': 'The human body has 206 bones.',
    'branches': 'The tree has many branches.',
    'bricks': 'The house is built with red bricks.',
    'bubbles': 'Children love blowing soap bubbles.',
    'buildings': 'There are many tall buildings downtown.',
    'causes': 'There are several causes of pollution.',
    'celebrations': 'Birthdays are happy celebrations.',
    'cells': 'Our bodies are made of millions of cells.',
    'centuries': 'This castle was built centuries ago.',
    'chances': 'Give him another chance to try.',
    'characters': 'The story has interesting characters.',
    'chemicals': 'Be careful with dangerous chemicals.',
    'choices': 'We make choices every day.',
    'circles': 'Draw three circles on the paper.',
    'citizens': 'All citizens have rights and responsibilities.',
    'clues': 'The detective found several clues.',
    'coins': 'I collect coins from different countries.',
    'colors': 'Rainbows have seven colors.',
    'conditions': 'The weather conditions are perfect today.',
    'connections': 'We have connections all over the world.',
    'contents': 'Check the contents of the box.',
    'contests': 'She won many singing contests.',
    'continents': 'There are seven continents on Earth.',
    'conversations': 'We had interesting conversations.',
    'corners': 'The room has four corners.',
    'countries': 'I want to visit many countries.',
    'couples': 'Many couples were dancing.',
    'creatures': 'The ocean has amazing creatures.',
    'cultures': 'Different countries have different cultures.',
    'dangers': 'Mountain climbing has many dangers.',
    'decades': 'My grandparents were married for decades.',
    'decisions': 'Making decisions can be difficult.',
    'degrees': 'Water boils at 100 degrees Celsius.',
    'details': 'Pay attention to the details.',
    'devices': 'Electronic devices are everywhere now.',
    'differences': 'There are many differences between us.',
    'difficulties': 'We overcame all the difficulties.',
    'directions': 'Follow the directions carefully.',
    'discoveries': 'Scientists make new discoveries every day.',
    'diseases': 'Vaccines prevent many diseases.',
    'distances': 'We measure distances in kilometers.',
    'documents': 'Keep all important documents safe.',
    'drops': 'There are drops of water on the leaves.',
    'duties': 'Students have certain duties.',
    'effects': 'The medicine has side effects.',
    'efforts': 'Thank you for all your efforts.',
    'elements': 'The periodic table shows all elements.',
    'emotions': 'Music can express different emotions.',
    'enemies': 'They became friends instead of enemies.',
    'energies': 'Solar and wind are renewable energies.',
    'engines': 'Cars have powerful engines.',
    'errors': 'Everyone makes errors sometimes.',
    'events': 'Many interesting events happened today.',
    'experiments': 'We do science experiments in class.',
    'experts': 'The experts gave us good advice.',
    'facts': 'These are important facts to remember.',
    'factors': 'Many factors affect the weather.',
    'failures': 'Failures teach us important lessons.',
    'features': 'This phone has many useful features.',
    'feelings': 'Don\'t hide your feelings.',
    'festivals': 'I love going to music festivals.',
    'figures': 'The report contains important figures.',
    'forces': 'Gravity is one of nature\'s forces.',
    'forests': 'Rainforests are home to many species.',
    'forms': 'Water exists in three forms.',
    'formulas': 'Math uses many formulas.',
    'functions': 'Each organ has different functions.',
    'gases': 'Air is made of different gases.',
    'generations': 'The tradition continues for generations.',
    'goals': 'Set realistic goals for yourself.',
    'goods': 'The store sells many goods.',
    'grades': 'I got good grades this semester.',
    'habits': 'Reading is one of my good habits.',
    'heroes': 'Firefighters are real heroes.',
    'histories': 'Every family has their own histories.',
    'hopes': 'We have high hopes for success.',
    'humans': 'Humans need water to survive.',
    'ideas': 'She has many creative ideas.',
    'images': 'The book has beautiful images.',
    'impacts': 'Pollution has serious impacts on health.',
    'industries': 'Technology industries are growing fast.',
    'insects': 'Bees and butterflies are insects.',
    'instructions': 'Follow the instructions carefully.',
    'inventions': 'Computers are great inventions.',
    'islands': 'The Philippines has thousands of islands.',
    'issues': 'We need to discuss these issues.',
    'items': 'Put all items back in their place.',
    'jobs': 'There are many different jobs in the world.',
    'journeys': 'Long journeys can be tiring.',
    'judges': 'The judges will announce the winner.',
    'languages': 'She speaks three languages.',
    'layers': 'The cake has three layers.',
    'leaders': 'Good leaders inspire others.',
    'leaves': 'The leaves fall in autumn.',
    'lessons': 'We have six lessons every day.',
    'levels': 'Video games have different levels.',
    'limits': 'There are speed limits on roads.',
    'lines': 'Wait in line for your turn.',
    'lists': 'Make a list of things to buy.',
    'locations': 'The app shows all nearby locations.',
    'machines': 'Factories use many machines.',
    'materials': 'We need art materials for class.',
    'matters': 'These matters are very important.',
    'meanings': 'Words can have multiple meanings.',
    'measures': 'The government took measures to help.',
    'medicines': 'Take your medicines on time.',
    'members': 'All family members are invited.',
    'memories': 'I have wonderful memories of that summer.',
    'messages': 'I received several messages today.',
    'methods': 'There are different methods to solve this.',
    'miles': 'The school is three miles from here.',
    'millions': 'There are millions of stars in the sky.',
    'minerals': 'Rocks contain various minerals.',
    'mistakes': 'Everyone makes mistakes.',
    'moments': 'These are precious moments.',
    'months': 'Summer vacation lasts for months.',
    'movements': 'The dancer\'s movements were graceful.',
    'muscles': 'Exercise strengthens your muscles.',
    'nations': 'The United Nations works for peace.',
    'natures': 'All creatures show their different natures.',
    'needs': 'Everyone has basic needs.',
    'neighbors': 'Our neighbors are very friendly.',
    'networks': 'Social networks connect people worldwide.',
    'notes': 'I took notes during the lecture.',
    'numbers': 'Add these numbers together.',
    'objects': 'There are several objects on the table.',
    'observations': 'Scientists make careful observations.',
    'occasions': 'We meet on special occasions.',
    'oceans': 'Earth has five major oceans.',
    'offers': 'The store has special offers today.',
    'offices': 'The building has many offices.',
    'opinions': 'Everyone has different opinions.',
    'opportunities': 'Life gives us many opportunities.',
    'options': 'We have several options to choose from.',
    'orders': 'The teacher gave us orders.',
    'organizations': 'Charity organizations help people.',
    'origins': 'The wine is of French origins.',
    'outcomes': 'Good planning leads to better outcomes.',
    'pages': 'The book has 200 pages.',
    'pairs': 'I need two pairs of socks.',
    'paragraphs': 'Write three paragraphs about your family.',
    'particles': 'Dust particles float in the air.',
    'parts': 'The machine has many moving parts.',
    'passages': 'Read the passages carefully.',
    'paths': 'There are two paths through the forest.',
    'patterns': 'The fabric has beautiful patterns.',
    'periods': 'History is divided into different periods.',
    'phases': 'The moon has different phases.',
    'pieces': 'Cut the paper into small pieces.',
    'planets': 'Eight planets orbit the sun.',
    'plants': 'Water the plants every day.',
    'points': 'You earned five points!',
    'positions': 'The players took their positions.',
    'powers': 'Superhoes have special powers.',
    'practices': 'Daily practices improve your skills.',
    'prices': 'The prices went up this month.',
    'principles': 'We live by certain principles.',
    'products': 'The store sells many products.',
    'programs': 'TV programs start at 7 pm.',
    'projects': 'We have three projects due next week.',
    'properties': 'Each element has unique properties.',
    'purposes': 'Tools serve different purposes.',
    'qualities': 'She has many good qualities.',
    'questions': 'The students asked many questions.',
    'reasons': 'There are many reasons to study.',
    'records': 'He broke all the records.',
    'regions': 'Different regions have different climates.',
    'relationships': 'Strong relationships need trust.',
    'remains': 'The remains of the castle still stand.',
    'requirements': 'Check the requirements before applying.',
    'resources': 'Natural resources must be protected.',
    'responsibilities': 'We all have responsibilities.',
    'results': 'The test results were excellent.',
    'rights': 'Everyone has equal rights.',
    'rivers': 'Many rivers flow into the ocean.',
    'roles': 'Everyone plays different roles in life.',
    'roots': 'The tree has deep roots.',
    'routes': 'There are several routes to school.',
    'rules': 'Follow the rules of the game.',
    'scenes': 'The movie has exciting scenes.',
    'schools': 'There are three schools in our town.',
    'sciences': 'Biology and chemistry are sciences.',
    'seasons': 'There are four seasons in a year.',
    'sections': 'The library has different sections.',
    'seeds': 'Plant the seeds in spring.',
    'senses': 'Humans have five senses.',
    'sentences': 'Write five sentences about your day.',
    'series': 'This is a series of books.',
    'services': 'The hotel offers good services.',
    'shapes': 'Cut out different shapes.',
    'sides': 'A cube has six sides.',
    'signals': 'Traffic signals control the flow.',
    'signs': 'Follow the road signs.',
    'situations': 'Different situations need different solutions.',
    'skills': 'Reading and writing are important skills.',
    'snacks': 'I brought some healthy snacks.',
    'solutions': 'We found solutions to all problems.',
    'sounds': 'I heard strange sounds last night.',
    'sources': 'What are your sources of information?',
    'spaces': 'There are empty spaces on the form.',
    'species': 'Many species live in the rainforest.',
    'speeds': 'Cars travel at different speeds.',
    'stages': 'Life has different stages.',
    'standards': 'The school maintains high standards.',
    'statements': 'Make clear statements.',
    'steps': 'Follow these steps carefully.',
    'stories': 'Grandma tells us bedtime stories.',
    'strategies': 'We need new strategies to win.',
    'streams': 'Small streams flow into rivers.',
    'strengths': 'Everyone has their own strengths.',
    'structures': 'Buildings are large structures.',
    'styles': 'People have different learning styles.',
    'subjects': 'Math and English are my favorite subjects.',
    'substances': 'Some substances are dangerous.',
    'suggestions': 'Do you have any suggestions?',
    'surfaces': 'Clean all surfaces regularly.',
    'symbols': 'Each culture has its own symbols.',
    'systems': 'The human body has many systems.',
    'tasks': 'Finish all your tasks on time.',
    'teams': 'Both teams played well.',
    'techniques': 'There are many painting techniques.',
    'technologies': 'New technologies change our lives.',
    'temperatures': 'Summer temperatures can be very high.',
    'terms': 'Explain it in simple terms.',
    'tests': 'We have math tests every month.',
    'theories': 'Scientists develop theories to explain things.',
    'thoughts': 'Share your thoughts with the class.',
    'thousands': 'Thousands of people attended the concert.',
    'tips': 'Here are some useful tips.',
    'titles': 'Books have interesting titles.',
    'tools': 'Carpenters use many tools.',
    'topics': 'We discussed several topics in class.',
    'trades': 'My father is skilled in several trades.',
    'traditions': 'Every culture has special traditions.',
    'trees': 'Plant more trees to help the environment.',
    'trends': 'Fashion trends change every year.',
    'trials': 'After many trials, she succeeded.',
    'tricks': 'Magicians know many tricks.',
    'trips': 'Family trips are always fun.',
    'troubles': 'Don\'t worry about small troubles.',
    'types': 'There are many types of flowers.',
    'units': 'Meters and feet are units of measurement.',
    'values': 'Family values are important.',
    'varieties': 'The store has many varieties of bread.',
    'vehicles': 'Cars and buses are vehicles.',
    'versions': 'This is the latest version.',
    'villages': 'Small villages are peaceful.',
    'voices': 'I heard voices outside.',
    'volumes': 'Libraries have volumes of books.',
    'walls': 'The walls are painted white.',
    'waves': 'Ocean waves can be very high.',
    'ways': 'There are many ways to solve it.',
    'weaknesses': 'We all have strengths and weaknesses.',
    'weapons': 'Soldiers carry weapons.',
    'weeks': 'School holidays last for two weeks.',
    'weights': 'Different objects have different weights.',
    'winds': 'Strong winds blew all day.',
    'winners': 'The winners received prizes.',
    'winters': 'Winters here are very cold.',
    'wishes': 'Make three wishes!',
    'wonders': 'The ancient wonders of the world.',
    'woods': 'We walked through the woods.',
    'words': 'Use new words in sentences.',
    'workers': 'The workers finished the project.',
    'worlds': 'Different cultures create different worlds.',
    'worries': 'Don\'t have any worries.',
    'wounds': 'The doctor treated his wounds.',
    'years': 'Many years have passed.',
    'zones': 'The city has different time zones.',
    
    // Common verbs (3rd person singular forms)
    'absorbs': 'The sponge absorbs water quickly.',
    'accepts': 'She always accepts help gratefully.',
    'acts': 'He acts in school plays.',
    'adds': 'She adds sugar to her tea.',
    'admits': 'He admits his mistakes.',
    'affects': 'The weather affects our mood.',
    'agrees': 'Everyone agrees with the plan.',
    'allows': 'Mom allows me to watch TV.',
    'appears': 'The sun appears in the morning.',
    'applies': 'This rule applies to everyone.',
    'arrives': 'The bus arrives at 8 am.',
    'asks': 'She asks good questions.',
    'believes': 'He believes in himself.',
    'belongs': 'This book belongs to me.',
    'calls': 'She calls her mom every day.',
    'carries': 'He carries his backpack to school.',
    'causes': 'Smoking causes health problems.',
    'changes': 'Everything changes over time.',
    'checks': 'She checks her email daily.',
    'chooses': 'He always chooses healthy food.',
    'closes': 'The shop closes at 6 pm.',
    'comes': 'Spring comes after winter.',
    'connects': 'This road connects the two cities.',
    'contains': 'The box contains old photos.',
    'continues': 'The rain continues all day. ',
    'controls': 'She controls her emotions well.',
    'costs': 'This toy costs ten dollars.',
    'covers': 'Snow covers the mountains.',
    'creates': 'Art creates beauty.',
    'crosses': 'He crosses the street carefully.',
    'depends': 'Success depends on hard work.',
    'describes': 'She describes the scene beautifully.',
    'develops': 'Practice develops skills.',
    'differs': 'My opinion differs from yours.',
    'discovers': 'The scientist discovers a new planet.',
    'divides': 'The river divides the city.',
    'drops': 'Be careful not to drop the glass.',
    'ends': 'School ends at 3 pm.',
    'enjoys': 'She enjoys reading books.',
    'enters': 'He enters the room quietly.',
    'exists': 'Life exists on Earth.',
    'expects': 'Mom expects me to be polite.',
    'explains': 'The teacher explains it clearly.',
    'falls': 'Rain falls from the clouds.',
    'feels': 'She feels happy today.',
    'follows': 'The dog follows its owner.',
    'forms': 'Ice forms when water freezes.',
    'grows': 'The child grows taller every year.',
    'handles': 'She handles problems calmly.',
    'happens': 'What happens next?',
    'helps': 'He helps his parents at home.',
    'holds': 'She holds the baby gently.',
    'hopes': 'Everyone hopes for good weather.',
    'hurts': 'My leg hurts when I walk.',
    'imagines': 'She imagines flying in the sky.',
    'improves': 'Practice improves performance.',
    'includes': 'The price includes breakfast.',
    'increases': 'Exercise increases energy.',
    'involves': 'This activity involves teamwork.',
    'joins': 'He joins the soccer team.',
    'jumps': 'The cat jumps very high.',
    'keeps': 'She keeps her room tidy.',
    'knows': 'He knows all the answers.',
    'lacks': 'The plan lacks details.',
    'leads': 'This path leads to the beach.',
    'learns': 'She learns something new every day.',
    'leaves': 'Dad leaves for work at 7 am.',
    'lets': 'Mom lets me play after homework.',
    'lies': 'The treasure lies buried underground.',
    'likes': 'She likes chocolate ice cream.',
    'links': 'This bridge links the two islands.',
    'lives': 'My grandma lives in the countryside.',
    'looks': 'She looks beautiful in that dress.',
    'loses': 'He never loses hope.',
    'loves': 'She loves animals very much.',
    'makes': 'Mom makes delicious cookies.',
    'marks': 'X marks the spot.',
    'matters': 'Your health matters most.',
    'means': 'This word means "happy."',
    'measures': 'The ruler measures length.',
    'meets': 'She meets her friends daily.',
    'mentions': 'He mentions you often.',
    'misses': 'She misses her old school.',
    'mixes': 'She mixes the colors together.',
    'moves': 'The train moves very fast.',
    'needs': 'Everyone needs water to live.',
    'notices': 'She always notices small details.',
    'occurs': 'This event occurs every year.',
    'offers': 'The store offers great deals.',
    'opens': 'The library opens at 9 am.',
    'orders': 'He orders pizza for dinner.',
    'owns': 'She owns a small bookshop.',
    'passes': 'Time passes quickly.',
    'pays': 'He pays for the groceries.',
    'picks': 'She picks fresh flowers.',
    'places': 'He places the book on the shelf.',
    'plans': 'She plans everything carefully.',
    'plays': 'He plays soccer every weekend.',
    'points': 'He points to the answer.',
    'prefers': 'She prefers tea over coffee.',
    'prepares': 'Mom prepares breakfast every morning.',
    'presents': 'The teacher presents a new topic.',
    'prevents': 'Exercise prevents disease.',
    'produces': 'This factory produces toys.',
    'protects': 'Sunscreen protects your skin.',
    'provides': 'The school provides free lunch.',
    'pulls': 'He pulls the door open.',
    'pushes': 'She pushes the swing.',
    'puts': 'He puts his books away.',
    'raises': 'She raises her hand to answer.',
    'reaches': 'The ladder reaches the roof.',
    'reads': 'She reads before bed.',
    'realizes': 'He realizes his mistake.',
    'receives': 'She receives many gifts.',
    'recognizes': 'I recognize that song!',
    'reduces': 'Walking reduces pollution.',
    'refers': 'The teacher refers to the textbook.',
    'reflects': 'The mirror reflects light.',
    'refuses': 'He refuses to give up.',
    'remains': 'The mystery remains unsolved.',
    'remembers': 'She always remembers birthdays.',
    'removes': 'He removes his shoes at the door.',
    'repairs': 'Dad repairs broken things.',
    'repeats': 'Please repeat that slowly.',
    'replaces': 'This battery replaces the old one.',
    'represents': 'The dove represents peace.',
    'requires': 'This job requires patience.',
    'rests': 'She rests after exercising.',
    'results': 'Hard work results in success.',
    'returns': 'He returns home at 5 pm.',
    'reveals': 'The test reveals what you know.',
    'rises': 'The sun rises in the east.',
    'runs': 'He runs five kilometers daily.',
    'saves': 'She saves money every month.',
    'says': 'He says hello every morning.',
    'searches': 'She searches for her keys.',
    'seems': 'It seems like a good idea.',
    'sends': 'She sends emails to her friends.',
    'serves': 'The restaurant serves delicious food.',
    'sets': 'The sun sets in the evening.',
    'shares': 'He shares his toys with others.',
    'shines': 'The sun shines brightly.',
    'shows': 'She shows me her drawing.',
    'sits': 'He sits in the front row.',
    'smells': 'The flower smells wonderful.',
    'smiles': 'She smiles at everyone.',
    'sounds': 'That sounds like a great plan!',
    'speaks': 'She speaks three languages.',
    'spends': 'He spends time with family.',
    'stands': 'She stands near the window.',
    'starts': 'Class starts at 8 am.',
    'stays': 'He stays home on Sundays.',
    'stops': 'The bus stops at the corner.',
    'studies': 'She studies every evening.',
    'succeeds': 'With hard work, everyone succeeds.',
    'suffers': 'She suffers from allergies.',
    'suggests': 'He suggests going to the park.',
    'supports': 'My family supports me.',
    'takes': 'She takes the bus to work.',
    'talks': 'He talks too much in class.',
    'teaches': 'My mom teaches math.',
    'tells': 'Grandma tells wonderful stories.',
    'thinks': 'She thinks before speaking.',
    'throws': 'He throws the ball high.',
    'touches': 'She gently touches the kitten.',
    'travels': 'He travels often for work.',
    'treats': 'She treats everyone kindly.',
    'tries': 'He tries his best always.',
    'turns': 'She turns off the lights.',
    'understands': 'She understands the problem.',
    'uses': 'He uses a computer daily.',
    'visits': 'She visits her grandparents often.',
    'waits': 'He waits patiently in line.',
    'walks': 'She walks to school.',
    'wants': 'He wants to be a doctor.',
    'washes': 'She washes her hands before eating.',
    'watches': 'He watches TV in the evening.',
    'wears': 'She wears glasses.',
    'wins': 'Our team wins every game.',
    'wishes': 'She wishes for good health.',
    'wonders': 'He wonders about the future.',
    'works': 'She works at a hospital.',
    'worries': 'Mom worries when I\'m late.',
    'writes': 'He writes in his diary.',
    
    // Proper nouns & places
    'africa': 'Lions live in Africa.',
    'america': 'New York is in America.',
    'asia': 'China is in Asia.',
    'europe': 'Paris is in Europe.',
    'australia': 'Kangaroos live in Australia.',
    'england': 'London is the capital of England.',
    'france': 'The Eiffel Tower is in France.',
    'india': 'Curry is popular in India.',
    'japan': 'Tokyo is the capital of Japan.',
    'brazil': 'Football is popular in Brazil.',
    'canada': 'It\'s very cold in Canada.',
    'china': 'The Great Wall is in China.',
    'mexico': 'Tacos come from Mexico.',
    'spain': 'Spanish is spoken in Spain.',
    'russia': 'Russia is the largest country.',
    
    // Common names (examples)
    'alex': 'Alex is my classmate.',
    'amy': 'Amy likes to read books.',
    'ben': 'Ben plays soccer.',
    'david': 'David is very smart.',
    'emily': 'Emily sings beautifully.',
    'jack': 'Jack is my best friend.',
    'kate': 'Kate helps her mom cook.',
    'lisa': 'Lisa has a pet dog.',
    'mike': 'Mike rides his bike to school.',
    'sarah': 'Sarah is very kind.',
    'tom': 'Tom finished his homework.',
    
    // Technical & misc
    'act': 'We must act quickly.',
    'adaptation': 'Adaptation helps animals survive.',
    'aeroplane': 'The aero plane flew over the clouds.',
    'aeroplanes': 'Aeroplanes transport passengers worldwide.',
    'algorithm': 'An algorithm is a set of steps to solve a problem.',
    'alive': 'All living things are alive.',
    'available': 'The book is available at the library.',
    'aware': 'Be aware of your surroundings.',
    'basic': 'Reading is a basic skill.',
    'calm': 'Stay calm during an emergency.',
    'capable': 'You are capable of anything.',
    'certain': 'I am certain we will win.',
    'clear': 'The instructions are very clear.',
    'common': 'This is a common mistake.',
    'complex': 'This is a complex problem.',
    'correct': 'Your answer is correct!',
    'current': 'What is the current time?',
    'dark': 'It gets dark at 6 pm.',
    'dead': 'The plant is dead because it had no water.',
    'deep': 'The ocean is very deep.',
    'digital': 'We live in a digital age.',
    'entire': 'I read the entire book.',
    'equal': 'All people are equal.',
    'familiar': 'This place looks familiar.',
    'famous': 'She is a famous singer.',
    'favorite': 'Blue is my favorite color.',
    'final': 'This is the final exam.',
    'flat': 'The table has a flat surface.',
    'fresh': 'I love the smell of fresh bread.',
    'general': 'This is a general rule.',
    'global': 'Climate change is a global issue.',
    'heavy': 'This box is too heavy.',
    'huge': 'The elephant is huge!',
    'impossible': 'Nothing is impossible if you try.',
    'individual': 'Each individual is unique.',
    'international': 'The conference was international.',
    'light': 'The box is very light.',
    'local': 'We shop at the local market.',
    'main': 'This is the main entrance.',
    'major': 'This is a major problem.',
    'modern': 'This is a modern building.',
    'national': 'Today is a national holiday.',
    'natural': 'Honey is a natural sweetener.',
    'necessary': 'Water is necessary for life.',
    'normal': 'This is perfectly normal.',
    'original': 'Is this the original painting?',
    'particular': 'I\'m looking for a particular book.',
    'perfect': 'Practice makes perfect!',
    'physical': 'Physical exercise is important.',
    'popular': 'Pizza is very popular.',
    'positive': 'Stay positive!',
    'possible': 'Everything is possible.',
    'powerful': 'Knowledge is powerful.',
    'practical': 'This is a practical solution.',
    'present': 'Stay present in the moment.',
    'previous': 'The previous lesson was easier.',
    'primary': 'I go to primary school.',
    'private': 'This is a private conversation.',
    'proper': 'Use proper grammar.',
    'public': 'This is a public park.',
    'real': 'Is this story real?',
    'regular': 'Exercise should be regular.',
    'responsible': 'Be responsible for your actions.',
    'safe': 'This place is safe.',
    'serious': 'This is a serious matter.',
    'sharp': 'Be careful, the knife is sharp.',
    'similar': 'Our ideas are similar.',
    'simple': 'The answer is simple.',
    'single': 'There isn\'t a single mistake!',
    'social': 'Humans are social animals.',
    'special': 'Today is a special day.',
    'specific': 'Be more specific.',
    'strange': 'That\'s a strange noise.',
    'strong': 'He is very strong.',
    'sudden': 'There was a sudden noise.',
    'traditional': 'This is a traditional dish.',
    'unique': 'Everyone is unique.',
    'unusual': 'That\'s very unusual!',
    'useful': 'This tool is very useful.',
    'various': 'There are various ways to do it.',
    'weak': 'The signal is weak here.',
    'whole': 'I ate the whole pizza!',
    'wide': 'The river is very wide.',
    'wild': 'Tigers are wild animals.',
    'wise': 'My grandmother is very wise.',
    'wrong': 'That answer is wrong.',
    
    // ═══════════════════════════════════════════════════════════════════════
    // EXTENDED BATCH 2: More common words
    // ═══════════════════════════════════════════════════════════════════════
    
    // More adverbs & conjunctions
    'anymore': 'I don\'t play that game anymore.',
    'anyone': 'Is anyone home?',
    'as': 'She is as tall as her brother.',
    'asleep': 'The baby is asleep.',
    'beautifully': 'She sings beautifully.',
    'brightly': 'The stars shine brightly.',
    'carefully': 'Drive carefully on icy roads.',
    'clearly': 'Speak clearly so everyone can hear.',
    'closely': 'Watch closely and you\'ll learn.',
    'comfortably': 'Sit comfortably and relax.',
    'commonly': 'This word is commonly used.',
    'constantly': 'She is constantly helping others.',
    'easily': 'He solves problems easily.',
    'effectively': 'Exercise works effectively.',
    'efficiently': 'She works very efficiently.',
    'equally': 'Share the candy equally.',
    'essentially': 'This is essentially correct.',
    'evenly': 'Spread the butter evenly.',
    'evidently': 'Evidently, he forgot about the meeting.',
    'firmly': 'Hold the rope firmly.',
    'formerly': 'This was formerly a school.',
    'fortunately': 'Fortunately, nobody was hurt.',
    'frequently': 'I visit my grandparents frequently.',
    'gladly': 'I will gladly help you.',
    'gradually': 'The weather is gradually getting warmer.',
    'greatly': 'Your help is greatly appreciated.',
    'happily': 'They lived happily ever after.',
    'hardly': 'I can hardly wait!',
    'heavily': 'It rained heavily all night.',
    'highly': 'She is a highly skilled doctor.',
    'honestly': 'Honestly, I don\'t know.',
    'hopefully': 'Hopefully, it won\'t rain.',
    'importantly': 'More importantly, everyone is safe.',
    'incredibly': 'The view is incredibly beautiful.',
    'increasingly': 'It\'s becoming increasingly difficult.',
    'indeed': 'That is indeed a good idea.',
    'independently': 'She works independently.',
    'initially': 'Initially, I was nervous.',
    'largely': 'The plan was largely successful.',
    'lightly': 'Touch it lightly.',
    'literally': 'I literally jumped with joy!',
    'locally': 'We shop locally to support small businesses.',
    'loudly': 'Don\'t talk so loudly!',
    'mainly': 'I eat mainly vegetables.',
    'naturally': 'Children learn naturally through play.',
    'nearly': 'I nearly forgot my keys!',
    'necessarily': 'It\'s not necessarily true.',
    'nicely': 'She asked nicely.',
    'oddly': 'The door was oddly quiet.',
    'officially': 'Summer officially starts in June.',
    'originally': 'I\'m originally from Canada.',
    'particularly': 'I particularly like chocolate.',
    'partly': 'The answer is only partly correct.',
    'perfectly': 'You did it perfectly!',
    'permanently': 'The stain is permanently set.',
    'physically': 'He is physically strong.',
    'plainly': 'The answer is plainly written.',
    'pleasantly': 'She smiled pleasantly.',
    'poorly': 'The team played poorly.',
    'potentially': 'This could potentially work.',
    'powerfully': 'He kicked the ball powerfully.',
    'precisely': 'That\'s precisely what I meant.',
    'previously': 'I met him previously.',
    'primarily': 'This is primarily a school.',
    'properly': 'Do your homework properly.',
    'purely': 'I did it purely for fun.',
    'rapidly': 'The fire spread rapidly.',
    'reasonably': 'He behaved reasonably well.',
    'regularly': 'I exercise regularly.',
    'relatively': 'The test was relatively easy.',
    'remarkably': 'She is remarkably talented.',
    'repeatedly': 'I\'ve told you repeatedly.',
    'respectively': 'They scored 10 and 20 points respectively.',
    'roughly': 'There are roughly 100 people here.',
    'safely': 'Drive safely!',
    'scarcely': 'I scarcely had time to eat.',
    'seriously': 'You must take this seriously.',
    'severely': 'The building was severely damaged.',
    'sharply': 'The temperature dropped sharply.',
    'shortly': 'We will arrive shortly.',
    'significantly': 'Grades improved significantly.',
    'silently': 'The cat moved silently.',
    'similarly': 'Similarly, we should also try.',
    'simply': 'It\'s simply amazing!',
    'slightly': 'I\'m slightly tired.',
    'smoothly': 'Everything went smoothly.',
    'softly': 'Speak softly in the hospital.',
    'solely': 'She is solely responsible.',
    'strongly': 'I strongly agree with you.',
    'successfully': 'She completed the task successfully.',
    'sufficiently': 'Have you eaten sufficiently?',
    'surprisingly': 'Surprisingly, he won the race.',
    'tightly': 'Hold on tightly!',
    'truly': 'This is truly amazing.',
    'typically': 'I typically wake up early.',
    'ultimately': 'Ultimately, we succeeded.',
    'undoubtedly': 'He is undoubtedly the best.',
    'unexpectedly': 'He arrived unexpectedly.',
    'unfortunately': 'Unfortunately, we lost.',
    'unlikely': 'It\'s unlikely to rain.',
    'virtually': 'The error is virtually impossible to see.',
    'widely': 'The news spread widely.',
    
    // More plural nouns
    'apartments': 'Many people live in apartments.',
    'apples': 'I eat apples every day.',
    'artists': 'Many artists paint beautiful pictures.',
    'astronauts': 'Astronauts travel to space.',
    'athletes': 'Athletes train every day.',
    'authors': 'Famous authors write great books.',
    'beans': 'Green beans are healthy.',
    'beats': 'Feel the beats of the music.',
    'beginnings': 'All great things have small beginnings.',
    'bites': 'Take small bites when you eat.',
    'blocks': 'The children play with blocks.',
    'boards': 'Write on the boards with chalk.',
    'boats': 'Many boats sail in the harbor.',
    'bottles': 'Recycle plastic bottles.',
    'boxes': 'Pack the items in boxes.',
    'boys': 'The boys are playing soccer.',
    'brains': 'Use your brains to solve problems.',
    'branches': 'Birds sit on tree branches.',
    'breads': 'The bakery sells many types of breads.',
    'bridges': 'Bridges connect two sides of a river.',
    'brothers': 'I have two brothers.',
    'brushes': 'Artists use different brushes.',
    'buckets': 'Fill the buckets with water.',
    'buses': 'School buses are yellow.',
    'buttons': 'The shirt has five buttons.',
    'cakes': 'Birthday cakes are delicious.',
    'cameras': 'Tourists carry cameras.',
    'camps': 'Summer camps are fun.',
    'candles': 'We lit ten candles on the cake.',
    'cards': 'She received many birthday cards.',
    'careers': 'People have different careers.',
    'carpets': 'The carpets are soft and warm.',
    'carrots': 'Rabbits love eating carrots.',
    'carts': 'Push the shopping carts.',
    'cases': 'Pack your belongings in cases.',
    'castles': 'Old castles have interesting histories.',
    'cats': 'Cats are independent animals.',
    'chains': 'Bicycles have chains.',
    'challenges': 'Life is full of challenges.',
    'changes': 'Seasons bring many changes.',
    'chapters': 'The book has twelve chapters.',
    'charts': 'Study the charts carefully.',
    'cheeks': 'Her cheeks turned red.',
    'chests': 'Pirates hid treasure in chests.',
    'choices': 'We make choices every day.',
    'churches': 'Many churches are very old.',
    'cities': 'Big cities have millions of people.',
    'classes': 'I have six classes today.',
    'clocks': 'All the clocks show the same time.',
    'clothes': 'Hang your clothes in the closet.',
    'clouds': 'White clouds float in the sky.',
    'clowns': 'Clowns make people laugh.',
    'clubs': 'She joined three school clubs.',
    'coaches': 'The coaches train the team.',
    'coats': 'Wear warm coats in winter.',
    'codes': 'Enter the security codes.',
    'colleges': 'Many colleges offer scholarships.',
    'colors': 'Rainbows have seven colors.',
    'computers': 'Computers help us work faster.',
    'concerts': 'Music concerts are exciting.',
    'cookies': 'Grandma bakes delicious cookies.',
    'copies': 'Make two copies of this document.',
    'cottages': 'Small cottages dot the countryside.',
    'couches': 'Comfortable couches fill the room.',
    'cousins': 'My cousins visit every summer.',
    'cows': 'Cows give us milk.',
    'crabs': 'Crabs walk sideways.',
    'cracks': 'There are cracks in the wall.',
    'crayons': 'Children color with crayons.',
    'crowds': 'Huge crowds gathered in the square.',
    'crowns': 'Kings and queens wear crowns.',
    'cups': 'Stack the cups carefully.',
    'curtains': 'Open the curtains to let sunlight in.',
    'customers': 'The store has many customers.',
    'cuts': 'Be careful, paper cuts hurt!',
    'dances': 'She performs traditional dances.',
    'daughters': 'They have two daughters.',
    'days': 'There are seven days in a week.',
    'deer': 'Deer live in the forest.',
    'desks': 'Students sit at their desks.',
    'diamonds': 'Diamonds are precious stones.',
    'diaries': 'She writes in her diary daily.',
    'dice': 'Roll the dice to play.',
    'dishes': 'Wash the dishes after dinner.',
    'doctors': 'Doctors help sick people.',
    'dogs': 'Dogs are loyal pets.',
    'dolls': 'Little girls play with dolls.',
    'dollars': 'This costs twenty dollars.',
    'dolphins': 'Dolphins are intelligent mammals.',
    'donuts': 'Donuts are sweet treats.',
    'doors': 'Close all the doors.',
    'dots': 'Connect the dots to complete the picture.',
    'dozens': 'I bought dozens of eggs.',
    'dragons': 'Fairy tales often mention dragons.',
    'dramas': 'We watch TV dramas together.',
    'drawers': 'Put the socks in the drawers.',
    'dreams': 'Chase your dreams!',
    'dresses': 'She has many beautiful dresses.',
    'drinks': 'We serve hot and cold drinks.',
    'drivers': 'Careful drivers prevent accidents.',
    'drums': 'He plays the drums in a band.',
    'ducks': 'Ducks swim in the pond.',
    'eagles': 'Eagles soar high in the sky.',
    'earrings': 'She wears diamond earrings.',
    'earthquakes': 'Earthquakes shake the ground.',
    'edges': 'Be careful near the edges.',
    'editors': 'Newspaper editors check articles.',
    'educators': 'Teachers are professional educators.',
    'eels': 'Electric eels live in rivers.',
    'eggs': 'Birds lay eggs.',
    'elbows': 'Rest your elbows on the table.',
    'elephants': 'Elephants are the largest land animals.',
    'emails': 'I check my emails daily.',
    'emergencies': 'Call 911 in emergencies.',
    'employees': 'The company has 500 employees.',
    'endings': 'Happy endings make me smile.',
    'enemies': 'Turn enemies into friends.',
    'engineers': 'Engineers design buildings.',
    'engines': 'Car engines need regular maintenance.',
    'entries': 'Submit your entries by Friday.',
    'envelopes': 'Put the letters in envelopes.',
    'environments': 'Protect natural environments.',
    'episodes': 'The series has ten episodes.',
    'equations': 'Solve these math equations.',
    'errors': 'Check for spelling errors.',
    'evenings': 'Summer evenings are pleasant.',
    'examples': 'The teacher gave several examples.',
    'exchanges': 'Cultural exchanges build understanding.',
    'excuses': 'No excuses, just do it!',
    'exercises': 'Daily exercises keep you healthy.',
    'exits': 'Emergency exits are marked.',
    'experiences': 'Travel gives you new experiences.',
    'experiments': 'Scientists conduct experiments.',
    'explanations': 'Clear explanations help understanding.',
    'explosions': 'Loud explosions scared everyone.',
    'expressions': 'Study math expressions carefully.',
    'extras': 'We ordered some extras.',
    'eyes': 'Her eyes are blue.',
    'eyebrows': 'Raise your eyebrows when surprised.',
    'faces': 'I see happy faces everywhere.',
    'factories': 'Factories produce many goods.',
    'fairs': 'County fairs have fun rides.',
    'fairies': 'Children believe in fairies.',
    'families': 'Families gather for holidays.',
    'fans': 'Sports fans cheer loudly.',
    'farms': 'Farms produce our food.',
    'farmers': 'Farmers grow crops.',
    'fathers': 'Fathers take care of their children.',
    'faults': 'Everyone has faults.',
    'feathers': 'Birds have colorful feathers.',
    'fences': 'Wooden fences surround the yard.',
    'fields': 'Cows graze in green fields.',
    'fights': 'Avoid getting into fights.',
    'files': 'Save all important files.',
    'films': 'We watch films on weekends.',
    'finances': 'Manage your finances wisely.',
    'findings': 'The research findings are interesting.',
    'fingernails': 'Keep your fingernails clean.',
    'fires': 'Firefighters put out fires.',
    'firefighters': 'Firefighters are brave.',
    'fireworks': 'Fireworks light up the night sky.',
    'flags': 'National flags represent countries.',
    'flames': 'Red and orange flames danced.',
    'flashes': 'Lightning flashes lit the sky.',
    'flights': 'Afternoon flights are cheaper.',
    'floors': 'Sweep all the floors.',
    'flowers': 'Spring brings beautiful flowers.',
    'flowers': 'Fresh flowers smell wonderful.',
    'folders': 'Organize documents in folders.',
    'folks': 'How are you folks doing?',
    'followers': 'She has many followers online.',
    'foods': 'Different countries have different foods.',
    'footballs': 'Boys play with footballs.',
    'footprints': 'We saw animal footprints in the snow.',
    'forces': 'Natural forces shape our world.',
    'foreheads': 'Wipe the sweat from your foreheads.',
    'forests': 'Dense forests cover the mountains.',
    'forks': 'Set the forks on the left.',
    'formats': 'Files come in different formats.',
    'formulas': 'Mathematical formulas solve problems.',
    'foundations': 'Strong foundations support buildings.',
    'fountains': 'Water fountains cool the plaza.',
    'foxes': 'Foxes are clever animals.',
    'frames': 'Picture frames decorate the walls.',
    'fries': 'French fries are popular.',
    'frogs': 'Frogs jump and swim.',
    'fruits': 'Eat fresh fruits daily.',
    'fuels': 'Fossil fuels power many vehicles.',
    'functions': 'Study math functions carefully.',
    
    // More food items
    'bean': 'I ate one bean.',
    'beef': 'Beef comes from cows.',
    'beet': 'Beets are red vegetables.',
    'berry': 'This berry is delicious.',
    'biscuit': 'I had a biscuit with tea.',
    'broccoli': 'Broccoli is a green vegetable.',
    'burger': 'I ordered a burger for lunch.',
    'butter': 'Spread butter on the bread.',
    'candy': 'Too much candy is bad for teeth.',
    'carrot': 'Rabbits eat carrots.',
    'cereal': 'I eat cereal for breakfast.',
    'cheese': 'This cheese tastes good.',
    'cherry': 'The cherry is sweet.',
    'chocolate': 'I love chocolate!',
    'corn': 'Corn on the cob is delicious.',
    'cream': 'Add cream to the coffee.',
    'cucumber': 'Cucumbers are cool and crisp.',
    'donut': 'I ate a donut for breakfast.',
    'flour': 'We need flour to bake bread.',
    'grape': 'I ate one grape.',
    'grapes': 'Grapes grow on vines.',
    'ham': 'Ham and cheese make a good sandwich.',
    'honey': 'Bees make honey.',
    'jam': 'I like strawberry jam on toast.',
    'lemon': 'Lemons are sour.',
    'lettuce': 'Lettuce is used in salads.',
    'mango': 'Mangoes are sweet tropical fruits.',
    'noodle': 'I ate one noodle.',
    'noodles': 'I love eating noodles.',
    'onion': 'Cutting onions makes you cry.',
    'pasta': 'Italian pasta is delicious.',
    'peach': 'This peach is ripe and juicy.',
    'pear': 'Pears are sweet fruit.',
    'pepper': 'Add pepper for flavor.',
    'pickle': 'I like sour pickles.',
    'pie': 'Apple pie is my favorite dessert.',
    'pork': 'Pork comes from pigs.',
    'potato': 'Potatoes can be baked or fried.',
    'salad': 'I eat salad every day.',
    'sausage': 'Sausages are good for breakfast.',
    'snack': 'I need a quick snack.',
    'spaghetti': 'We had spaghetti for dinner.',
    'steak': 'Dad grilled a steak.',
    'strawberry': 'Strawberries are red and sweet.',
    'toast': 'I made toast for breakfast.',
    'tomato': 'Tomatoes are red when ripe.',
    'tuna': 'Tuna fish swim in the ocean.',
    'turkey': 'We eat turkey on Thanksgiving.',
    'yogurt': 'Yogurt is good for your stomach.',
    
    // More verbs & verb forms
    'bang': 'Don\'t bang the door!',
    'barks': 'My dog barks at strangers.',
    'bat': 'He can bat very well.',
    'bats': 'Bats fly at night.',
    'beat': 'Beat the eggs well.',
    'became': 'She became a doctor.',
    'become': 'I want to become a teacher.',
    'beep': 'The car will beep when it\'s locked.',
    'began': 'The movie began at 7 pm.',
    'begin': 'Let\'s begin the lesson.',
    'begins': 'Class begins at 8 am.',
    'behave': 'Please behave nicely.',
    'behaves': 'He always behaves well.',
    'bite': 'Don\'t bite your nails.',
    'bites': 'The dog never bites.',
    'blow': 'Blow out the candles.',
    'blows': 'The wind blows hard.',
    'boil': 'Boil the water first.',
    'boils': 'Water boils at 100 degrees.',
    'borrow': 'Can I borrow your pen?',
    'borrows': 'She often borrows books.',
    'bounce': 'Watch the ball bounce.',
    'bounces': 'The ball bounces high.',
    'bow': 'Bow to show respect.',
    'bows': 'He bows politely.',
    'breathe': 'Breathe deeply and relax.',
    'breathes': 'Everyone breathes air.',
    'climb': 'Can you climb this tree?',
    'climbs': 'She climbs mountains.',
    'collect': 'I collect stamps.',
    'collects': 'He collects coins.',
    'combine': 'Combine all ingredients.',
    'combines': 'She combines flavors well.',
    'compare': 'Compare these two answers.',
    'compares': 'He compares prices before buying.',
    'compete': 'Athletes compete for medals.',
    'competes': 'She competes in many races.',
    
    // Animals, objects & misc
    'author': 'The author wrote many books.',
    'beagle': 'A beagle is a type of dog.',
    'bench': 'Sit on this bench and rest.',
    'better': 'This is better than before.',
    'best': 'You are the best!',
    'bigger': 'My house is bigger than yours.',
    'biggest': 'He has the biggest room.',
    'bird': 'The bird sings beautifully.',
    'birdhouse': 'We built a birdhouse for birds.',
    'blanket': 'Cover yourself with a blanket.',
    'bloom': 'Flowers bloom in spring.',
    'blooms': 'The rose blooms beautifully.',
    'blossom': 'Cherry trees blossom in April.',
    'blossoms': 'Spring brings beautiful blossoms.',
    'boat': 'We took a boat ride.',
    'bookmark': 'Use a bookmark to save your place.',
    'bookstore': 'Buy books at the bookstore.',
    'boot': 'I wear one boot.',
    'boots': 'Wear boots when it rains.',
    'bottle': 'Fill the water bottle.',
    'bottom': 'Look at the bottom of the page.',
    'bouquet': 'She received a bouquet of roses.',
    'bowl': 'Pour cereal in the bowl.',
    'bowls': 'Wash the bowls after eating.',
    'box': 'Put it in the box.',
    'bracelet': 'She wears a silver bracelet.',
    'brain': 'Your brain controls your body.',
    'brave': 'Firefighters are very brave.',
    'breakfast': 'Breakfast is the most important meal.',
    'breeze': 'A cool breeze blew gently.',
    'brick': 'Each brick helps build the wall.',
    'bridge': 'A bridge crosses the river.',
    'bright': 'The sun is very bright.',
    'broke': 'I broke my pencil.',
    'broken': 'The toy is broken.',
    'brook': 'A small brook flows nearby.',
    'broom': 'Sweep the floor with a broom.',
    'brought': 'She brought cookies to share.',
    'brush': 'Brush your teeth twice daily.',
    'bubble': 'Blow a big bubble!',
    'bucket': 'Fill the bucket with water.',
    'build': 'Let\'s build a sand castle.',
    'builds': 'He builds model airplanes.',
    'built': 'They built a new school.',
    'bull': 'A bull is a male cow.',
    'bump': 'I felt a bump on the road.',
    'bumps': 'The road has many bumps.',
    'bunch': 'Buy a bunch of bananas.',
    'bunny': 'The bunny hops around.',
    'burn': 'Don\'t burn yourself.',
    'burns': 'The fire burns brightly.',
    'burst': 'The balloon will burst!',
    'bursts': 'The bubble bursts easily.',
    'bury': 'Dogs bury bones.',
    'bus': 'Take the bus to school.',
    'bush': 'A bird hides in the bush.',
    'bushes': 'Trim the bushes in the garden.',
    'busy': 'I am very busy today.',
    'button': 'Press the red button.',
    
    // Verbs: become, began, begin
    'became': 'He became a famous singer.',
    'becomes': 'Water becomes ice when frozen.',
    
    // ═══════════════════════════════════════════════════════════════════════
    // FINAL BATCH: Remaining common words (C words continuation)
    // ═══════════════════════════════════════════════════════════════════════
    
    'bikes': 'Many kids ride bikes to school.',
    'blood': 'Blood carries oxygen in our body.',
    'bodies': 'Our bodies need rest and exercise.',
    'body': 'Take care of your body.',
    'body\'s': 'The body\'s temperature should be normal.',
    'border': 'Draw a border around the picture.',
    'botanic': 'We visited the botanic garden.',
    'brilliant': 'That was a brilliant idea!',
    'broadcast': 'The news will broadcast at 6 pm.',
    'bumpy': 'The road was very bumpy.',
    'butterfly': 'A colorful butterfly flew by.',
    'butterflies': 'Butterflies have beautiful wings.',
    'calcium': 'Milk contains calcium for strong bones.',
    'calligraphy': 'Calligraphy is beautiful handwriting.',
    'calmly': 'She spoke calmly during the emergency.',
    'came': 'They came to visit us.',
    'cannot': 'I cannot swim yet.',
    'canvas': 'Artists paint on canvas.',
    'captions': 'Read the captions under the pictures.',
    'carbohydrates': 'Bread and rice have carbohydrates.',
    'care': 'Take care of yourself.',
    'careful': 'Be careful when crossing the street.',
    'cartoons': 'Children love watching cartoons.',
    'cave': 'Bats live in dark caves.',
    'caves': 'Limestone caves are fascinating.',
    'center': 'The playground is in the center of the park.',
    'central': 'We live in the central part of the city.',
    'chain': 'The dog is on a chain.',
    'challenge': 'This puzzle is quite a challenge.',
    'champion': 'She is the swimming champion.',
    'champions': 'Olympic champions train hard.',
    'charles': 'Charles is my friend\'s name.',
    'charlie': 'Charlie loves playing soccer.',
    'chart': 'Look at the chart on the wall.',
    'charts': 'Study the charts in the textbook.',
    'chase': 'The cat will chase the mouse.',
    'chases': 'The dog chases its tail.',
    'cheap': 'This toy is very cheap.',
    'cheaper': 'Apples are cheaper than oranges.',
    'cheapest': 'This is the cheapest option.',
    'cheer': 'Let\'s cheer for our team!',
    'cheers': 'The crowd cheers loudly.',
    'chemical': 'Be careful with chemical products.',
    'chemicals': 'Some chemicals are dangerous.',
    'chest': 'Place your hand on your chest.',
    'chew': 'Chew your food well.',
    'chews': 'He chews slowly.',
    'chill': 'Chill the juice before serving.',
    'chilly': 'It\'s a chilly morning.',
    'chimpanzee': 'A chimpanzee is a type of ape.',
    'chimpanzees': 'Chimpanzees are very intelligent.',
    'chip': 'I ate one potato chip.',
    'chips': 'Chips are salty snacks.',
    'chocolate': 'I love chocolate ice cream!',
    'choice': 'It was the right choice.',
    'chop': 'Chop the vegetables finely.',
    'chops': 'She chops wood for the fire.',
    'chose': 'I chose the blue one.',
    'chosen': 'You were chosen for the team.',
    'citrus': 'Lemons and oranges are citrus fruits.',
    'clap': 'Clap your hands!',
    'claps': 'Everyone claps when she sings.',
    'classic': 'This is a classic story.',
    'claw': 'The cat has a sharp claw.',
    'claws': 'Eagles have strong claws.',
    'clay': 'We made pots from clay.',
    'cleaner': 'This cleaner works well.',
    'cleaners': 'The cleaners come every week.',
    'cleaning': 'I am cleaning my room.',
    'cleans': 'She cleans every Saturday.',
    'clever': 'That was a clever solution!',
    'cliff': 'Don\'t stand too close to the cliff.',
    'cliffs': 'Sea birds nest on cliffs.',
    'climate': 'The climate is changing.',
    'climates': 'Different regions have different climates.',
    'climbed': 'We climbed to the top.',
    'climber': 'He is an expert climber.',
    'climbers': 'Mountain climbers need training.',
    'climbing': 'Rock climbing is exciting.',
    'clip': 'Use a clip to hold papers together.',
    'clips': 'Hair clips come in many colors.',
    'closet': 'Hang your coat in the closet.',
    'closets': 'Both closets are full.',
    'cloth': 'Wipe it with a soft cloth.',
    'cloths': 'Use these cloths for cleaning.',
    'clown': 'The clown made everyone laugh.',
    'club': 'I joined the chess club.',
    'clue': 'I have no clue!',
    'clues': 'Find the clues to solve the mystery.',
    'clumsy': 'I am sometimes clumsy.',
    'coach': 'The coach trains the team.',
    'coastal': 'We live in a coastal town.',
    'code': 'Enter the secret code.',
    'codes': 'Security codes protect information.',
    'coin': 'I found a coin on the ground.',
    'colder': 'Today is colder than yesterday.',
    'coldest': 'December is the coldest month.',
    'collar': 'The dog has a red collar.',
    'collars': 'Pet collars have name tags.',
    'collected': 'I collected all the toys.',
    'collecting': 'Stamp collecting is his hobby.',
    'collection': 'He has a large coin collection.',
    'collections': 'Museums have art collections.',
    'college': 'She will go to college next year.',
    'colored': 'Use colored pencils.',
    'colorful': 'The garden is very colorful.',
    'coloring': 'I enjoy coloring books.',
    'comb': 'Comb your hair before school.',
    'combs': 'She combs her hair daily.',
    'comfortable': 'This chair is very comfortable.',
    'comic': 'I read a comic book.',
    'comics': 'Comics make me laugh.',
    'coming': 'Are you coming to the party?',
    'command': 'Follow the teacher\'s command.',
    'commands': 'The captain gives commands.',
    'comment': 'Please leave a comment.',
    'comments': 'Read all the comments.',
    'commercial': 'We saw a funny commercial on TV.',
    'commercials': 'TV commercials can be annoying.',
    'community': 'Help your local community.',
    'communities': 'Different communities have unique customs.',
    'companion': 'A dog is a faithful companion.',
    'companions': 'Good companions enrich life.',
    'company': 'My dad works for a big company.',
    'companies': 'Many companies hire graduates.',
    'comparison': 'Make a comparison of the two.',
    'comparisons': 'Comparisons help us understand.',
    'compass': 'Use a compass to find north.',
    'compete': 'Athletes compete for medals.',
    'competed': 'She competed in the race.',
    'competes': 'He competes in tennis.',
    'competing': 'They are competing for first place.',
    'competition': 'The competition was tough.',
    'competitions': 'She wins many competitions.',
    'competitive': 'He is very competitive.',
    'competitor': 'Each competitor did well.',
    'competitors': 'All competitors shook hands.',
    'complained': 'He complained about the noise.',
    'complaining': 'Stop complaining!',
    'complains': 'She never complains.',
    'complaint': 'File complaint if necessary.',
    'complaints': 'The manager handles complaints.',
    'complete': 'Complete your homework first.',
    'completed': 'I completed all tasks.',
    'completely': 'I completely forgot!',
    'completes': 'She always completes her work.',
    'completing': 'I am completing the project.',
    'complex': 'This is a complex problem.',
    'complicated': 'Math can be complicated.',
    'compose': 'Compose a short poem.',
    'composed': 'Mozart composed beautiful music.',
    'composer': 'Beethoven was a great composer.',
    'composers': 'Famous composers created symphonies.',
    'computer': 'I use the computer for homework.',
    'computers': 'Computers help us work faster.',
    'concentrate': 'Concentrate on your studies.',
    'concentrated': 'She concentrated during the test.',
    'concentrates': 'He concentrates well.',
    'concentrating': 'I am concentrating now.',
    'concentration': 'This requires concentration.',
    'concept': 'Explain this concept clearly.',
    'concepts': 'We learned many concepts.',
    'concern': 'Your safety is my concern.',
    'concerned': 'I am concerned about you.',
    'concerning': 'This is concerning news.',
    'concerns': 'She concerns herself with others.',
    'concert': 'We went to a concert.',
    'concerts': 'Music concerts are exciting.',
    'conclude': 'In conclusion, I agree.',
    'concluded': 'The meeting concluded at 5 pm.',
    'concludes': 'The story concludes happily.',
    'conclusion': 'What is your conclusion?',
    'conclusions': 'Draw conclusions from the data.',
    'concrete': 'The floor is made of concrete.',
    'condition': 'The car is in good condition.',
    'conduct': 'Conduct yourself properly.',
    'conducted': 'They conducted an experiment.',
    'conducting': 'She is conducting research.',
    'conducts': 'The orchestra conductor leads.',
    'cone': 'Ice cream comes in a cone.',
    'cones': 'Pine cones fall from trees.',
    'confidence': 'Have confidence in yourself!',
    'confident': 'She feels confident.',
    'confirm': 'Please confirm your appointment.',
    'confirmed': 'The news was confirmed.',
    'confirms': 'This confirms the theory.',
    'conflict': 'Avoid conflict when possible.',
    'conflicts': 'Conflicts can be resolved.',
    'confused': 'I am confused.',
    'confusing': 'This is confusing.',
    'confusion': 'There was some confusion.',
    'connect': 'Connect the two wires.',
    'connected': 'Everything is connected.',
    'connecting': 'I am connecting to WiFi.',
    'connection': 'Check your internet connection.',
    'connections': 'Make strong connections.',
    'conquer': 'Conquer your fears!',
    'conquered': 'He conquered the challenge.',
    'conquers': 'Bravery conquers fear.',
    'conscious': 'Be conscious of your actions.',
    'consequence': 'Every action has a consequence.',
    'consequences': 'Think about consequences.',
    'conservation': 'Wildlife conservation matters.',
    'consider': 'Please consider this.',
    'considerable': 'That\'s considerable progress.',
    'considerably': 'Prices rose considerably.',
    'consideration': 'Take this into consideration.',
    'considered': 'She considered all options.',
    'considering': 'I am considering your offer.',
    'considers': 'He considers everyone\'s opinion.',
    'consist': 'Healthy meals consist of vegetables.',
    'consisted': 'The meal consisted of soup.',
    'consisting': 'A team consisting of experts.',
    'consists': 'Water consists of H2O.',
    'constant': 'Change is constant.',
    'constantly': 'She constantly improves.',
    'construct': 'Construct a model.',
    'constructed': 'They constructed a bridge.',
    'constructing': 'Workers are constructing.',
    'construction': 'Construction takes time.',
    'constructs': 'He constructs airplanes.',
    'consult': 'Consult a doctor.',
    'consulted': 'I consulted an expert.',
    'consulting': 'She is consulting notes.',
    'consults': 'He consults the dictionary.',
    'consume': 'Don\'t consume too much sugar.',
    'consumed': 'The fire consumed wood.',
    'consumer': 'Every consumer has rights.',
    'consumers': 'Consumers buy products.',
    'consumes': 'This consumes energy.',
    'contact': 'Stay in contact.',
    'contacted': 'She contacted me.',
    'contacting': 'I am contacting support.',
    'contacts': 'He has many contacts.',
    'contain': 'Does this contain nuts?',
    'contained': 'The box contained photos.',
    'container': 'Use a sealed container.',
    'containers': 'Store food in containers.',
    'containing': 'Boxes containing books.',
    'content': 'I am content.',
    'context': 'Understand words in context.',
    'continent': 'Asia is a huge continent.',
    'continue': 'Let\'s continue tomorrow.',
    'continued': 'The rain continued.',
    'continuing': 'Keep continuing.',
    'continuous': 'Continuous practice helps.',
    'contract': 'Sign the contract.',
    'contracts': 'Read contracts carefully.',
    'contrast': 'Notice the contrast.',
    'contribute': 'Everyone should contribute.',
    'contributed': 'She contributed greatly.',
    'contributes': 'Exercise contributes to health.',
    'contributing': 'Thanks for contributing.',
    'contribution': 'Your contribution helps.',
    'contributions': 'Many contributions were made.',
    'conversation': 'We had a nice conversation.',
    'conversations': 'Phone conversations connect us.',
    'convert': 'Convert meters to feet.',
    'converted': 'We converted the garage.',
    'converting': 'I am converting files.',
    'converts': 'This converts energy.',
    'convey': 'Words convey ideas.',
    'conveyed': 'He conveyed thanks.',
    'conveys': 'Her smile conveys joy.',
    'convince': 'Try to convince me.',
    'convinced': 'I am convinced.',
    'convincing': 'That\'s convincing!',
    'cooked': 'She cooked dinner.',
    'cooking': 'I enjoy cooking.',
    'cooks': 'Mom cooks well.',
    'cool': 'This drink is cool.',
    'cooled': 'The soup cooled.',
    'cooler': 'Today is cooler.',
    'coolest': 'That\'s the coolest!',
    'cooling': 'The pie is cooling.',
    'cools': 'The fan cools the room.',
    'cooperate': 'Please cooperate.',
    'cooperation': 'Teamwork needs cooperation.',
    'cooperative': 'He is cooperative.',
    'coordinate': 'Coordinate your efforts.',
    'coordinates': 'Find the coordinates.',
    'copied': 'I copied the notes.',
    'copies': 'Make three copies.',
    'copy': 'Copy this sentence.',
    'copying': 'Stop copying!',
    'coral': 'Coral reefs are beautiful.',
    'core': 'Earth has a hot core.',
    'corner': 'Wait at the corner.',
    'corners': 'The room has four corners.',
    'corrected': 'Teacher corrected mistakes.',
    'correcting': 'I am correcting errors.',
    'correction': 'Make the correction.',
    'corrections': 'Check all corrections.',
    'correspond': 'Numbers correspond to dates.',
    'corridor': 'Walk in the corridor quietly.',
    'corridors': 'School corridors are wide.',
    'costly': 'That was a costly mistake.',
    'cough': 'Cover when you cough.',
    'coughed': 'He coughed loudly.',
    'coughs': 'She coughs sometimes.',
    'could': 'I could help tomorrow.',
    'couldn\'t': 'I couldn\'t find it.',
    'count': 'Count to ten.',
    'counted': 'I counted the coins.',
    'counter': 'Put it on the counter.',
    'counting': 'She is counting money.',
    'countless': 'Stars are countless.',
    
  };
  
  // Check exact match first
  if (realExamples[w]) {
    return realExamples[w];
  }
  
  // ═══════════════════════════════════════════════════════════════════════
  // LEVEL 2: PATTERN-BASED NATURAL COLLOCATIONS
  // ═══════════════════════════════════════════════════════════════════════
  
  const def = (definition_en || '').toLowerCase();
  
  // Detect word type
  const isVerb = def.startsWith('to ') || def.includes(' verb');
  const isNoun = def.match(/^(a |an |the )/) || def.includes(' noun');
  const isAdjective = def.includes('adjective') || def.includes('describing');
  const isAdverb = def.includes('adverb') || w.endsWith('ly');
  
  // Handle plurals - use singular form example
  if (w.endsWith('s') && w.length > 3 && !isNoun) {
    const singular = w.endsWith('ies') ? w.slice(0, -3) + 'y' :
                    w.endsWith('es') ? w.slice(0, -2) :
                    w.slice(0, -1);
    if (realExamples[singular]) {
      return realExamples[singular].replace(new RegExp(`\\b${singular}\\b`, 'gi'), w);
    }
  }
  
  // Handle past tense - use present form
  if (w.endsWith('ed') && w.length > 3) {
    const present = w.endsWith('ied') ? w.slice(0, -3) + 'y' :
                   w.slice(0, -2);
    if (realExamples[present]) {
      return `Yesterday, ${realExamples[present].toLowerCase()}`;
    }
  }
  
  // Handle -ing forms - use base verb
  if (w.endsWith('ing') && w.length > 4) {
    const base = w.endsWith('ing') ? w.slice(0, -3) : w;
    if (realExamples[base]) {
      return `They are ${w} now.`;
    }
  }
  
  // NATURAL PATTERNS by type
  if (isVerb && meaning) {
    if (week <= 5) return `Let\'s ${w} together.`;
    return `I want to ${w} more often.`;
  }
  
  if (isNoun && meaning) {
    if (week <= 5) return `I see a ${w}.`;
    return `The ${w} is over there.`;
  }
  
  if (isAdjective && meaning) {
    if (week <= 5) return `It is ${w}.`;
    return `She looks very ${w}.`;
  }
  
  if (isAdverb && meaning) {
    if (week <= 5) return `He speaks ${w}.`;
    return `She does her work ${w}.`;
  }
  
  // FALLBACK - minimal but natural
  if (meaning || definition_en) {
    return `This is about ${w}.`;
  }
  
  return null;
}

async function main() {
  console.log('🔄 Replacing ALL bad examples with REAL collocations...\n');

  const dictData = await fs.readFile(DICT_PATH, 'utf-8');
  const dictionary = JSON.parse(dictData);

  let updated = 0;
  let kept = 0;

  for (const entry of dictionary) {
    const currentExample = entry.example;
    
    // Keep good examples (not generic patterns)
    if (currentExample && 
        !currentExample.includes('I like this') &&
        !currentExample.includes('This involves') &&
        !currentExample.includes('are interesting to study') &&
        !currentExample.includes('This helps us daily') &&
        !currentExample.includes('is something we should know') &&
        !currentExample.includes('Understanding') &&
        !currentExample.includes('essential for success') &&
        !currentExample.includes('at the moment.') &&
        !currentExample.includes('important for everyone')) {
      kept++;
      continue;
    }

    // Replace bad example with real collocation
    const newExample = generateRealExample(entry);
    if (newExample && newExample !== currentExample) {
      entry.example = newExample;
      updated++;
      
      if (updated % 100 === 0) {
        console.log(`✅ Rewrote ${updated} examples...`);
      }
    }
  }

  // Save
  await fs.writeFile(
    DICT_PATH,
    JSON.stringify(dictionary, null, 2),
    'utf-8'
  );

  const newSize = (await fs.stat(DICT_PATH)).size / 1024;

  console.log(`\n✅ COMPLETE!`);
  console.log(`   🔄 Rewrote: ${updated} examples with REAL collocations`);
  console.log(`   ✓  Kept: ${kept} already good examples`);
  console.log(`   💾 File size: ${newSize.toFixed(1)}KB`);
  
  // Show samples
  console.log(`\n📖 Sample REAL examples:`);
  const samples = [
    dictionary.find(e => e.word.toLowerCase() === 'short'),
    dictionary.find(e => e.word.toLowerCase() === 'straight'),
    dictionary.find(e => e.word.toLowerCase() === 'black'),
    dictionary.find(e => e.word.toLowerCase() === 'head'),
    dictionary.find(e => e.word.toLowerCase() === 'wear'),
    dictionary.find(e => e.word.toLowerCase() === 'walk'),
    dictionary.find(e => e.word.toLowerCase() === 'happy'),
    dictionary.find(e => e.word.toLowerCase() === 'big'),
  ].filter(Boolean);
  
  samples.forEach(e => {
    console.log(`   ${e.word.padEnd(18)} | "${e.example}"`);
  });
}

main().catch(console.error);
