#!/usr/bin/env python3
import pathlib

lines = [
    "1. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_journey.jpg. Cute 3D render of a happy family of four walking cheerfully along a wide open road toward a glowing golden sunset on the horizon, mountains in the distance, each person carrying a colourful suitcase or backpack, birds flying overhead, warm adventurous lighting, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "2. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_airport.jpg. Cute 3D render of a modern international airport terminal interior with tall curved glass walls, bright sunlight streaming in, a wide polished floor with cheerful travellers pulling luggage, large passenger aircraft visible through the windows on the tarmac outside, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "3. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_passenger.jpg. Cute 3D render of a young child of about eight sitting in a window seat on an aeroplane, face pressed gently to the oval window, gazing out at fluffy white clouds and bright blue sky with wide-eyed wonder, seatbelt fastened, warm sunlight on their face, cosy cabin interior, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "4. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_departure.jpg. Cute 3D render of an airport departure gate with a glass jet bridge leading to a parked white passenger plane outside, a small happy queue of travellers with carry-on bags walking toward the bridge entrance, golden late-afternoon light through the windows, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "5. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_arrival.jpg. Cute 3D render of a bright airport arrivals hall where a family is joyfully reuniting — grandparents opening their arms wide to hug two running children, colorful balloons in hand, warm overhead lighting, other smiling travellers in the background, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "6. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_ticket.jpg. Cute 3D render of a child holding a colourful airline boarding pass in both small hands, the ticket is striped with warm orange and blue, close-up framing against a soft white background, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "7. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_luggage.jpg. Cute 3D render of a neat row of five colourful suitcases and travel bags of different sizes lined up on a shiny airport floor — red, blue, yellow, green, and purple — bright overhead lights reflecting on the floor, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "8. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_platform.jpg. Cute 3D render of a busy train station platform on a sunny day, a sleek modern train pulling in from the left, a mother holding a child's hand, a student with a backpack waiting on the platform, warm natural light streaming in, pigeons on the platform floor, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "9. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_destination.jpg. Cute 3D render of a happy family stepping out of a yellow taxi in front of a beautiful seaside hotel, palm trees swaying, turquoise ocean visible in the background, the family smiling and pointing at the view, bright sunny day, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "10. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_route.jpg. Cute 3D render of a bird's-eye illustrated map showing a winding road connecting two small colourful towns, a dotted travel path traced across green hills and a small river between them, tiny house and tree icons, flat illustration style, soft warm palette, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "11. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_delay.jpg. Cute 3D render of three tired travellers sitting in a row of airport waiting chairs — a woman checking her watch, a man slumped with arms crossed, a child leaning on a parent's shoulder — large windows behind showing an overcast sky, bored and weary expressions, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "12. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_vehicle.jpg. Cute 3D render of five types of transport together in one cheerful scene — a passenger plane in the sky, a train on tracks, a red bus on a road, a family car, and a bicycle — bright primary colours, friendly cartoon style, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "13. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: vocab_adventure.jpg. Cute 3D render of a young girl standing at the open door of an aeroplane high above the clouds, arms spread wide with joy, a small backpack on her back, brilliant golden sunrise light all around, clouds far below, a vast sky ahead, triumphant and free, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "14. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: wordpower_go_on_journey.jpg. [COLLOCATION: go on a journey] Cute 3D render of a cheerful family of three walking side-by-side down a scenic country road at sunrise, rolling hills on both sides, each carrying a bright coloured travel bag, smiling and looking ahead together, birds in the warm morning sky, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "15. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: wordpower_fly_above.jpg. [COLLOCATION: fly above the clouds] Cute 3D render of a large white passenger aeroplane soaring majestically above a thick layer of fluffy white cumulus clouds, clear vivid blue sky above, bright sunlight glinting off the silver wings, seen from a slightly below-side angle, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "16. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: wordpower_adventure.jpg. [COLLOCATION: go on an adventure] Cute 3D render of a young child sprinting excitedly along a jungle trail, small backpack bouncing, arms pumping, lush green tropical plants on both sides, colourful birds and butterflies around them, dappled golden sunlight filtering through the canopy, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "17. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: wordpower_run_gate.jpg. [COLLOCATION: run to the gate] Cute 3D render of a young boy sprinting through a bright airport corridor, small wheeled suitcase trailing behind him, jacket flying open, one hand stretched forward toward a gate door ahead, other passengers watching in surprise, urgent and comic energy, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "18. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: wordpower_destination.jpg. [COLLOCATION: arrive at the destination] Cute 3D render of a smiling family stepping out of a taxi in front of a beautiful coastal hotel, ocean waves visible behind the building, palm trees framing the scene, the children pointing excitedly at the beach, bright midday sun, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "19. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: wordpower_board_plane.jpg. [COLLOCATION: board the plane] Cute 3D render of a line of happy passengers walking up an outdoor staircase attached to a large white passenger aeroplane, a smiling flight attendant in blue uniform welcoming them at the top of the stairs, sunny blue sky behind, cheerful and inviting scene, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "20. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: read_cover_w29.jpg. Cute 3D render of a sleek passenger aeroplane lifting off a tropical airport runway at sunset, palm trees lining the runway edges, a family of four waving from an observation terrace in the foreground, colourful sky of orange and pink, joyful and warm energy, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
    "21. Hãy tạo các hình ảnh 3D sống động sau đây. Filename: explore_cover_w29.jpg. Cute 3D render of two excited children standing in front of a large glowing world globe, dotted flight routes curving across the surface connecting continents, small aeroplane icons along each route, warm orange and teal lighting, sense of wonder and exploration, Pixar animation style, vibrant colors, soft studio lighting, clean background. No text or letters in the image.",
]

out = pathlib.Path("/Users/binhnguyen/Downloads/Engquest3k/Production_FINAL/IMAGE PROMPTS/week_29_image_prompts.txt")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Written {len(lines)} lines.")
print("No-text count:", sum(1 for l in lines if "No text or letters" in l))
