// tools/image_pipeline/audit.mjs
//
// Audit existing W30-35 images and identify which ones need regeneration
// based on heuristics: file size, age, manual flags.
//
// Usage:
//   node tools/image_pipeline/audit.mjs [--week 30..35] [--size-threshold 30]
//
// Heuristics:
//   - File missing on disk (regen needed)
//   - File < --size-threshold KB (likely abstract / sparse image from bad gen)
//   - File generated by FLUX.1-schnell (was producing text in image; see commit log)
//
// Outputs:
//   - Per-week list of files to regenerate
//   - Total count
//   - One-line command to regenerate them all once API quota resets

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');

// CLI
const args = process.argv.slice(2);
const opts = { weeks: [], sizeThreshold: 30, manualFlags: [] };
for (let i = 0; i < args.length; i++) {
  if (args[i] === '--week') {
    const v = args[++i];
    if (v.includes('..')) {
      const [f, t] = v.split('..').map(Number);
      for (let w = f; w <= t; w++) opts.weeks.push(w);
    } else {
      opts.weeks.push(...v.split(',').map(Number));
    }
  } else if (args[i] === '--size-threshold') {
    opts.sizeThreshold = parseInt(args[++i], 10);
  }
}
const targetWeeks = opts.weeks.length ? opts.weeks : [30,31,32,33,34,35];

const SLOTS = ['read_cover','explore_cover','math_cover','logic_lab','grammar_cover',
               'word_match_cover','vocab','word_power'];

const toRegen = [];

console.log(`🔍 Audit W${targetWeeks.join(',W')} images (size threshold: ${opts.sizeThreshold}KB)\n`);

for (const week of targetWeeks) {
  const weekFiles = [];
  for (const modeTag of ['ADV', 'EASY']) {
    const base = modeTag === 'EASY'
      ? path.join(ROOT, 'src', 'data', 'weeks_easy', `week_${String(week).padStart(2,'0')}`)
      : path.join(ROOT, 'src', 'data', 'weeks',      `week_${week.toString().padStart(2,'0')}`);
    if (!fs.existsSync(base)) continue;

    for (const fname of fs.readdirSync(base).filter(f => f.endsWith('.js'))) {
      const fp = path.join(base, fname);
      const raw = fs.readFileSync(fp, 'utf-8');
      const re = fname === 'word_match.js'
        ? /image:\s*["']([^"']+)["']/g
        : /image_url:\s*["']([^"']+)["']/g;
      const refs = [...raw.matchAll(re)]
        .map(m => m[1])
        .map(p => p.startsWith('https://pub-6b5486dcbb554a6694b6c7032a43dcae.r2.dev/') ? '/' + p.slice(52) : p)
        .filter(p => !p.includes('barmodel_'));
      for (const ref of refs) {
        if (ref.includes('mission') || ref.includes('story_')) continue;
        if (ref.includes('sparktalk_')) continue;
        const localPath = path.join(ROOT, 'public', ref);
        if (!fs.existsSync(localPath)) {
          weekFiles.push({ ref, localPath, mode: modeTag, reason: 'missing' });
        } else {
          const stat = fs.statSync(localPath);
          const sizeKB = stat.size / 1024;
          if (sizeKB < opts.sizeThreshold) {
            weekFiles.push({ ref, localPath, mode: modeTag, reason: `small (${sizeKB.toFixed(0)}KB)`, sizeKB });
          }
        }
      }
    }
  }
  if (weekFiles.length) {
    console.log(`── W${String(week).padStart(2,'0')}: ${weekFiles.length} files to regenerate ──`);
    weekFiles.forEach(f => {
      console.log(`  [${f.mode}] ${f.ref}  → ${f.reason}`);
    });
    toRegen.push(...weekFiles);
  } else {
    console.log(`── W${String(week).padStart(2,'0')}: ✅ all complete`);
  }
}

console.log(`\n📊 Total files to regenerate: ${toRegen.length}`);

if (toRegen.length > 0) {
  const onlyList = [...new Set(toRegen.map(f => path.basename(f.ref)))].join(',');
  const weekList = [...new Set(toRegen.map(f => {
    const m = f.ref.match(/week(\d+)/);
    return m ? parseInt(m[1]) : 0;
  }))].sort();

  console.log(`\n📋 Run this when API quota is available:\n`);
  console.log(`  IMG_MODEL=sd3-medium node tools/image_pipeline/orchestrator.mjs \\`);
  console.log(`    --week ${Math.min(...weekList)}..${Math.max(...weekList)} \\`);
  console.log(`    --only "${onlyList}" --force`);
  console.log(`\n  # Then upload + update sources:\n`);
  console.log(`  node tools/image_pipeline/upload_only.mjs --week ${Math.min(...weekList)}..${Math.max(...weekList)}\n`);
}
